// Code generated by ent, DO NOT EDIT.

package assignment

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the assignment type in the database.
	Label = "assignment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "assignment_id"
	// FieldWorker holds the string denoting the worker field in the database.
	FieldWorker = "worker"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLeaseExpiresAt holds the string denoting the lease_expires_at field in the database.
	FieldLeaseExpiresAt = "lease_expires_at"
	// FieldWorkspace holds the string denoting the workspace field in the database.
	FieldWorkspace = "workspace"
	// FieldHandoff holds the string denoting the handoff field in the database.
	FieldHandoff = "handoff"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRoadmapItem holds the string denoting the roadmap_item edge name in mutations.
	EdgeRoadmapItem = "roadmap_item"
	// RoadmapItemFieldID holds the string denoting the ID field of the RoadmapItem.
	RoadmapItemFieldID = "rmi_id"
	// Table holds the table name of the assignment in the database.
	Table = "assignments"
	// RoadmapItemTable is the table that holds the roadmap_item relation/edge.
	RoadmapItemTable = "assignments"
	// RoadmapItemInverseTable is the table name for the RoadmapItem entity.
	// It exists in this package in order to avoid circular dependency with the "roadmapitem" package.
	RoadmapItemInverseTable = "roadmap_items"
	// RoadmapItemColumn is the table column denoting the roadmap_item relation/edge.
	RoadmapItemColumn = "roadmap_item_assignments"
)

// Columns holds all SQL columns for assignment fields.
var Columns = []string{
	FieldID,
	FieldWorker,
	FieldStatus,
	FieldLeaseExpiresAt,
	FieldWorkspace,
	FieldHandoff,
	FieldCreatedAt,
	FieldCompletedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "assignments"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"roadmap_item_assignments",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// WorkerValidator is a validator for the "worker" field. It is called by the builders before save.
	WorkerValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// WorkspaceValidator is a validator for the "workspace" field. It is called by the builders before save.
	WorkspaceValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Assignment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByWorker orders the results by the worker field.
func ByWorker(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorker, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLeaseExpiresAt orders the results by the lease_expires_at field.
func ByLeaseExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseExpiresAt, opts...).ToFunc()
}

// ByWorkspace orders the results by the workspace field.
func ByWorkspace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkspace, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRoadmapItemField orders the results by roadmap_item field.
func ByRoadmapItemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoadmapItemStep(), sql.OrderByField(field, opts...))
	}
}
func newRoadmapItemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoadmapItemInverseTable, RoadmapItemFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RoadmapItemTable, RoadmapItemColumn),
	)
}
