// Code generated by ent, DO NOT EDIT.

package repositorydependency

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the repositorydependency type in the database.
	Label = "repository_dependency"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceRepositoryID holds the string denoting the source_repository_id field in the database.
	FieldSourceRepositoryID = "source_repository_id"
	// FieldTargetRepositoryID holds the string denoting the target_repository_id field in the database.
	FieldTargetRepositoryID = "target_repository_id"
	// FieldDependencyType holds the string denoting the dependency_type field in the database.
	FieldDependencyType = "dependency_type"
	// Table holds the table name of the repositorydependency in the database.
	Table = "repository_dependencies"
)

// Columns holds all SQL columns for repositorydependency fields.
var Columns = []string{
	FieldID,
	FieldSourceRepositoryID,
	FieldTargetRepositoryID,
	FieldDependencyType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SourceRepositoryIDValidator is a validator for the "source_repository_id" field. It is called by the builders before save.
	SourceRepositoryIDValidator func(string) error
	// TargetRepositoryIDValidator is a validator for the "target_repository_id" field. It is called by the builders before save.
	TargetRepositoryIDValidator func(string) error
	// DependencyTypeValidator is a validator for the "dependency_type" field. It is called by the builders before save.
	DependencyTypeValidator func(string) error
)

// OrderOption defines the ordering options for the RepositoryDependency queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourceRepositoryID orders the results by the source_repository_id field.
func BySourceRepositoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceRepositoryID, opts...).ToFunc()
}

// ByTargetRepositoryID orders the results by the target_repository_id field.
func ByTargetRepositoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetRepositoryID, opts...).ToFunc()
}

// ByDependencyType orders the results by the dependency_type field.
func ByDependencyType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDependencyType, opts...).ToFunc()
}
