// Code generated by ent, DO NOT EDIT.

package repositorydependency

import (
	"entgo.io/ent/dialect/sql"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldLTE(FieldID, id))
}

// SourceRepositoryID applies equality check predicate on the "source_repository_id" field. It's identical to SourceRepositoryIDEQ.
func SourceRepositoryID(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldEQ(FieldSourceRepositoryID, v))
}

// TargetRepositoryID applies equality check predicate on the "target_repository_id" field. It's identical to TargetRepositoryIDEQ.
func TargetRepositoryID(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldEQ(FieldTargetRepositoryID, v))
}

// DependencyType applies equality check predicate on the "dependency_type" field. It's identical to DependencyTypeEQ.
func DependencyType(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldEQ(FieldDependencyType, v))
}

// SourceRepositoryIDEQ applies the EQ predicate on the "source_repository_id" field.
func SourceRepositoryIDEQ(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldEQ(FieldSourceRepositoryID, v))
}

// SourceRepositoryIDNEQ applies the NEQ predicate on the "source_repository_id" field.
func SourceRepositoryIDNEQ(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldNEQ(FieldSourceRepositoryID, v))
}

// SourceRepositoryIDIn applies the In predicate on the "source_repository_id" field.
func SourceRepositoryIDIn(vs ...string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldIn(FieldSourceRepositoryID, vs...))
}

// SourceRepositoryIDNotIn applies the NotIn predicate on the "source_repository_id" field.
func SourceRepositoryIDNotIn(vs ...string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldNotIn(FieldSourceRepositoryID, vs...))
}

// SourceRepositoryIDGT applies the GT predicate on the "source_repository_id" field.
func SourceRepositoryIDGT(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldGT(FieldSourceRepositoryID, v))
}

// SourceRepositoryIDGTE applies the GTE predicate on the "source_repository_id" field.
func SourceRepositoryIDGTE(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldGTE(FieldSourceRepositoryID, v))
}

// SourceRepositoryIDLT applies the LT predicate on the "source_repository_id" field.
func SourceRepositoryIDLT(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldLT(FieldSourceRepositoryID, v))
}

// SourceRepositoryIDLTE applies the LTE predicate on the "source_repository_id" field.
func SourceRepositoryIDLTE(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldLTE(FieldSourceRepositoryID, v))
}

// SourceRepositoryIDContains applies the Contains predicate on the "source_repository_id" field.
func SourceRepositoryIDContains(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldContains(FieldSourceRepositoryID, v))
}

// SourceRepositoryIDHasPrefix applies the HasPrefix predicate on the "source_repository_id" field.
func SourceRepositoryIDHasPrefix(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldHasPrefix(FieldSourceRepositoryID, v))
}

// SourceRepositoryIDHasSuffix applies the HasSuffix predicate on the "source_repository_id" field.
func SourceRepositoryIDHasSuffix(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldHasSuffix(FieldSourceRepositoryID, v))
}

// SourceRepositoryIDEqualFold applies the EqualFold predicate on the "source_repository_id" field.
func SourceRepositoryIDEqualFold(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldEqualFold(FieldSourceRepositoryID, v))
}

// SourceRepositoryIDContainsFold applies the ContainsFold predicate on the "source_repository_id" field.
func SourceRepositoryIDContainsFold(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldContainsFold(FieldSourceRepositoryID, v))
}

// TargetRepositoryIDEQ applies the EQ predicate on the "target_repository_id" field.
func TargetRepositoryIDEQ(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldEQ(FieldTargetRepositoryID, v))
}

// TargetRepositoryIDNEQ applies the NEQ predicate on the "target_repository_id" field.
func TargetRepositoryIDNEQ(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldNEQ(FieldTargetRepositoryID, v))
}

// TargetRepositoryIDIn applies the In predicate on the "target_repository_id" field.
func TargetRepositoryIDIn(vs ...string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldIn(FieldTargetRepositoryID, vs...))
}

// TargetRepositoryIDNotIn applies the NotIn predicate on the "target_repository_id" field.
func TargetRepositoryIDNotIn(vs ...string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldNotIn(FieldTargetRepositoryID, vs...))
}

// TargetRepositoryIDGT applies the GT predicate on the "target_repository_id" field.
func TargetRepositoryIDGT(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldGT(FieldTargetRepositoryID, v))
}

// TargetRepositoryIDGTE applies the GTE predicate on the "target_repository_id" field.
func TargetRepositoryIDGTE(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldGTE(FieldTargetRepositoryID, v))
}

// TargetRepositoryIDLT applies the LT predicate on the "target_repository_id" field.
func TargetRepositoryIDLT(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldLT(FieldTargetRepositoryID, v))
}

// TargetRepositoryIDLTE applies the LTE predicate on the "target_repository_id" field.
func TargetRepositoryIDLTE(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldLTE(FieldTargetRepositoryID, v))
}

// TargetRepositoryIDContains applies the Contains predicate on the "target_repository_id" field.
func TargetRepositoryIDContains(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldContains(FieldTargetRepositoryID, v))
}

// TargetRepositoryIDHasPrefix applies the HasPrefix predicate on the "target_repository_id" field.
func TargetRepositoryIDHasPrefix(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldHasPrefix(FieldTargetRepositoryID, v))
}

// TargetRepositoryIDHasSuffix applies the HasSuffix predicate on the "target_repository_id" field.
func TargetRepositoryIDHasSuffix(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldHasSuffix(FieldTargetRepositoryID, v))
}

// TargetRepositoryIDEqualFold applies the EqualFold predicate on the "target_repository_id" field.
func TargetRepositoryIDEqualFold(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldEqualFold(FieldTargetRepositoryID, v))
}

// TargetRepositoryIDContainsFold applies the ContainsFold predicate on the "target_repository_id" field.
func TargetRepositoryIDContainsFold(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldContainsFold(FieldTargetRepositoryID, v))
}

// DependencyTypeEQ applies the EQ predicate on the "dependency_type" field.
func DependencyTypeEQ(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldEQ(FieldDependencyType, v))
}

// DependencyTypeNEQ applies the NEQ predicate on the "dependency_type" field.
func DependencyTypeNEQ(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldNEQ(FieldDependencyType, v))
}

// DependencyTypeIn applies the In predicate on the "dependency_type" field.
func DependencyTypeIn(vs ...string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldIn(FieldDependencyType, vs...))
}

// DependencyTypeNotIn applies the NotIn predicate on the "dependency_type" field.
func DependencyTypeNotIn(vs ...string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldNotIn(FieldDependencyType, vs...))
}

// DependencyTypeGT applies the GT predicate on the "dependency_type" field.
func DependencyTypeGT(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldGT(FieldDependencyType, v))
}

// DependencyTypeGTE applies the GTE predicate on the "dependency_type" field.
func DependencyTypeGTE(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldGTE(FieldDependencyType, v))
}

// DependencyTypeLT applies the LT predicate on the "dependency_type" field.
func DependencyTypeLT(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldLT(FieldDependencyType, v))
}

// DependencyTypeLTE applies the LTE predicate on the "dependency_type" field.
func DependencyTypeLTE(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldLTE(FieldDependencyType, v))
}

// DependencyTypeContains applies the Contains predicate on the "dependency_type" field.
func DependencyTypeContains(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldContains(FieldDependencyType, v))
}

// DependencyTypeHasPrefix applies the HasPrefix predicate on the "dependency_type" field.
func DependencyTypeHasPrefix(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldHasPrefix(FieldDependencyType, v))
}

// DependencyTypeHasSuffix applies the HasSuffix predicate on the "dependency_type" field.
func DependencyTypeHasSuffix(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldHasSuffix(FieldDependencyType, v))
}

// DependencyTypeEqualFold applies the EqualFold predicate on the "dependency_type" field.
func DependencyTypeEqualFold(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldEqualFold(FieldDependencyType, v))
}

// DependencyTypeContainsFold applies the ContainsFold predicate on the "dependency_type" field.
func DependencyTypeContainsFold(v string) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.FieldContainsFold(FieldDependencyType, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RepositoryDependency) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RepositoryDependency) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RepositoryDependency) predicate.RepositoryDependency {
	return predicate.RepositoryDependency(sql.NotPredicates(p))
}
