// Code generated by ent, DO NOT EDIT.

package devxperiodreport

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the devxperiodreport type in the database.
	Label = "dev_xperiod_report"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrganization holds the string denoting the organization field in the database.
	FieldOrganization = "organization"
	// FieldRepositoryID holds the string denoting the repository_id field in the database.
	FieldRepositoryID = "repository_id"
	// FieldPersonID holds the string denoting the person_id field in the database.
	FieldPersonID = "person_id"
	// FieldPeriodType holds the string denoting the period_type field in the database.
	FieldPeriodType = "period_type"
	// FieldPeriodLabel holds the string denoting the period_label field in the database.
	FieldPeriodLabel = "period_label"
	// FieldPeriodStart holds the string denoting the period_start field in the database.
	FieldPeriodStart = "period_start"
	// FieldPeriodEnd holds the string denoting the period_end field in the database.
	FieldPeriodEnd = "period_end"
	// FieldMetrics holds the string denoting the metrics field in the database.
	FieldMetrics = "metrics"
	// FieldByModel holds the string denoting the by_model field in the database.
	FieldByModel = "by_model"
	// FieldCoverageScore holds the string denoting the coverage_score field in the database.
	FieldCoverageScore = "coverage_score"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the devxperiodreport in the database.
	Table = "dev_xperiod_reports"
)

// Columns holds all SQL columns for devxperiodreport fields.
var Columns = []string{
	FieldID,
	FieldOrganization,
	FieldRepositoryID,
	FieldPersonID,
	FieldPeriodType,
	FieldPeriodLabel,
	FieldPeriodStart,
	FieldPeriodEnd,
	FieldMetrics,
	FieldByModel,
	FieldCoverageScore,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the DevXPeriodReport queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrganization orders the results by the organization field.
func ByOrganization(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganization, opts...).ToFunc()
}

// ByRepositoryID orders the results by the repository_id field.
func ByRepositoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositoryID, opts...).ToFunc()
}

// ByPersonID orders the results by the person_id field.
func ByPersonID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPersonID, opts...).ToFunc()
}

// ByPeriodType orders the results by the period_type field.
func ByPeriodType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodType, opts...).ToFunc()
}

// ByPeriodLabel orders the results by the period_label field.
func ByPeriodLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodLabel, opts...).ToFunc()
}

// ByPeriodStart orders the results by the period_start field.
func ByPeriodStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodStart, opts...).ToFunc()
}

// ByPeriodEnd orders the results by the period_end field.
func ByPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodEnd, opts...).ToFunc()
}

// ByCoverageScore orders the results by the coverage_score field.
func ByCoverageScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverageScore, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
