// Code generated by ent, DO NOT EDIT.

package capabilitymodel

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the capabilitymodel type in the database.
	Label = "capability_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "model_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldDimensions holds the string denoting the dimensions field in the database.
	FieldDimensions = "dimensions"
	// FieldMaxLevel holds the string denoting the max_level field in the database.
	FieldMaxLevel = "max_level"
	// EdgeAssessments holds the string denoting the assessments edge name in mutations.
	EdgeAssessments = "assessments"
	// MaturityAssessmentFieldID holds the string denoting the ID field of the MaturityAssessment.
	MaturityAssessmentFieldID = "assessment_id"
	// Table holds the table name of the capabilitymodel in the database.
	Table = "capability_models"
	// AssessmentsTable is the table that holds the assessments relation/edge.
	AssessmentsTable = "maturity_assessments"
	// AssessmentsInverseTable is the table name for the MaturityAssessment entity.
	// It exists in this package in order to avoid circular dependency with the "maturityassessment" package.
	AssessmentsInverseTable = "maturity_assessments"
	// AssessmentsColumn is the table column denoting the assessments relation/edge.
	AssessmentsColumn = "capability_model_assessments"
)

// Columns holds all SQL columns for capabilitymodel fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldDimensions,
	FieldMaxLevel,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultMaxLevel holds the default value on creation for the "max_level" field.
	DefaultMaxLevel int
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the CapabilityModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByMaxLevel orders the results by the max_level field.
func ByMaxLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxLevel, opts...).ToFunc()
}

// ByAssessmentsCount orders the results by assessments count.
func ByAssessmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAssessmentsStep(), opts...)
	}
}

// ByAssessments orders the results by assessments terms.
func ByAssessments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssessmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAssessmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssessmentsInverseTable, MaturityAssessmentFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AssessmentsTable, AssessmentsColumn),
	)
}
