// Code generated by ent, DO NOT EDIT.

package capabilitymodel

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldEQ(FieldDescription, v))
}

// MaxLevel applies equality check predicate on the "max_level" field. It's identical to MaxLevelEQ.
func MaxLevel(v int) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldEQ(FieldMaxLevel, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldContainsFold(FieldDescription, v))
}

// DimensionsIsNil applies the IsNil predicate on the "dimensions" field.
func DimensionsIsNil() predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldIsNull(FieldDimensions))
}

// DimensionsNotNil applies the NotNil predicate on the "dimensions" field.
func DimensionsNotNil() predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldNotNull(FieldDimensions))
}

// MaxLevelEQ applies the EQ predicate on the "max_level" field.
func MaxLevelEQ(v int) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldEQ(FieldMaxLevel, v))
}

// MaxLevelNEQ applies the NEQ predicate on the "max_level" field.
func MaxLevelNEQ(v int) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldNEQ(FieldMaxLevel, v))
}

// MaxLevelIn applies the In predicate on the "max_level" field.
func MaxLevelIn(vs ...int) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldIn(FieldMaxLevel, vs...))
}

// MaxLevelNotIn applies the NotIn predicate on the "max_level" field.
func MaxLevelNotIn(vs ...int) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldNotIn(FieldMaxLevel, vs...))
}

// MaxLevelGT applies the GT predicate on the "max_level" field.
func MaxLevelGT(v int) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldGT(FieldMaxLevel, v))
}

// MaxLevelGTE applies the GTE predicate on the "max_level" field.
func MaxLevelGTE(v int) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldGTE(FieldMaxLevel, v))
}

// MaxLevelLT applies the LT predicate on the "max_level" field.
func MaxLevelLT(v int) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldLT(FieldMaxLevel, v))
}

// MaxLevelLTE applies the LTE predicate on the "max_level" field.
func MaxLevelLTE(v int) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.FieldLTE(FieldMaxLevel, v))
}

// HasAssessments applies the HasEdge predicate on the "assessments" edge.
func HasAssessments() predicate.CapabilityModel {
	return predicate.CapabilityModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssessmentsTable, AssessmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssessmentsWith applies the HasEdge predicate on the "assessments" edge with a given conditions (other predicates).
func HasAssessmentsWith(preds ...predicate.MaturityAssessment) predicate.CapabilityModel {
	return predicate.CapabilityModel(func(s *sql.Selector) {
		step := newAssessmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CapabilityModel) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CapabilityModel) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CapabilityModel) predicate.CapabilityModel {
	return predicate.CapabilityModel(sql.NotPredicates(p))
}
