// Code generated by ent, DO NOT EDIT.

package prismdocument

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldContainsFold(FieldID, id))
}

// Organization applies equality check predicate on the "organization" field. It's identical to OrganizationEQ.
func Organization(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldOrganization, v))
}

// RepositoryID applies equality check predicate on the "repository_id" field. It's identical to RepositoryIDEQ.
func RepositoryID(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldRepositoryID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldDescription, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrganizationEQ applies the EQ predicate on the "organization" field.
func OrganizationEQ(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldOrganization, v))
}

// OrganizationNEQ applies the NEQ predicate on the "organization" field.
func OrganizationNEQ(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNEQ(FieldOrganization, v))
}

// OrganizationIn applies the In predicate on the "organization" field.
func OrganizationIn(vs ...string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIn(FieldOrganization, vs...))
}

// OrganizationNotIn applies the NotIn predicate on the "organization" field.
func OrganizationNotIn(vs ...string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotIn(FieldOrganization, vs...))
}

// OrganizationGT applies the GT predicate on the "organization" field.
func OrganizationGT(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGT(FieldOrganization, v))
}

// OrganizationGTE applies the GTE predicate on the "organization" field.
func OrganizationGTE(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGTE(FieldOrganization, v))
}

// OrganizationLT applies the LT predicate on the "organization" field.
func OrganizationLT(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLT(FieldOrganization, v))
}

// OrganizationLTE applies the LTE predicate on the "organization" field.
func OrganizationLTE(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLTE(FieldOrganization, v))
}

// OrganizationContains applies the Contains predicate on the "organization" field.
func OrganizationContains(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldContains(FieldOrganization, v))
}

// OrganizationHasPrefix applies the HasPrefix predicate on the "organization" field.
func OrganizationHasPrefix(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldHasPrefix(FieldOrganization, v))
}

// OrganizationHasSuffix applies the HasSuffix predicate on the "organization" field.
func OrganizationHasSuffix(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldHasSuffix(FieldOrganization, v))
}

// OrganizationIsNil applies the IsNil predicate on the "organization" field.
func OrganizationIsNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIsNull(FieldOrganization))
}

// OrganizationNotNil applies the NotNil predicate on the "organization" field.
func OrganizationNotNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotNull(FieldOrganization))
}

// OrganizationEqualFold applies the EqualFold predicate on the "organization" field.
func OrganizationEqualFold(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEqualFold(FieldOrganization, v))
}

// OrganizationContainsFold applies the ContainsFold predicate on the "organization" field.
func OrganizationContainsFold(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldContainsFold(FieldOrganization, v))
}

// RepositoryIDEQ applies the EQ predicate on the "repository_id" field.
func RepositoryIDEQ(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldRepositoryID, v))
}

// RepositoryIDNEQ applies the NEQ predicate on the "repository_id" field.
func RepositoryIDNEQ(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNEQ(FieldRepositoryID, v))
}

// RepositoryIDIn applies the In predicate on the "repository_id" field.
func RepositoryIDIn(vs ...string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIn(FieldRepositoryID, vs...))
}

// RepositoryIDNotIn applies the NotIn predicate on the "repository_id" field.
func RepositoryIDNotIn(vs ...string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotIn(FieldRepositoryID, vs...))
}

// RepositoryIDGT applies the GT predicate on the "repository_id" field.
func RepositoryIDGT(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGT(FieldRepositoryID, v))
}

// RepositoryIDGTE applies the GTE predicate on the "repository_id" field.
func RepositoryIDGTE(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGTE(FieldRepositoryID, v))
}

// RepositoryIDLT applies the LT predicate on the "repository_id" field.
func RepositoryIDLT(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLT(FieldRepositoryID, v))
}

// RepositoryIDLTE applies the LTE predicate on the "repository_id" field.
func RepositoryIDLTE(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLTE(FieldRepositoryID, v))
}

// RepositoryIDContains applies the Contains predicate on the "repository_id" field.
func RepositoryIDContains(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldContains(FieldRepositoryID, v))
}

// RepositoryIDHasPrefix applies the HasPrefix predicate on the "repository_id" field.
func RepositoryIDHasPrefix(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldHasPrefix(FieldRepositoryID, v))
}

// RepositoryIDHasSuffix applies the HasSuffix predicate on the "repository_id" field.
func RepositoryIDHasSuffix(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldHasSuffix(FieldRepositoryID, v))
}

// RepositoryIDIsNil applies the IsNil predicate on the "repository_id" field.
func RepositoryIDIsNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIsNull(FieldRepositoryID))
}

// RepositoryIDNotNil applies the NotNil predicate on the "repository_id" field.
func RepositoryIDNotNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotNull(FieldRepositoryID))
}

// RepositoryIDEqualFold applies the EqualFold predicate on the "repository_id" field.
func RepositoryIDEqualFold(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEqualFold(FieldRepositoryID, v))
}

// RepositoryIDContainsFold applies the ContainsFold predicate on the "repository_id" field.
func RepositoryIDContainsFold(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldContainsFold(FieldRepositoryID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldContainsFold(FieldDescription, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionIsNil applies the IsNil predicate on the "version" field.
func VersionIsNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIsNull(FieldVersion))
}

// VersionNotNil applies the NotNil predicate on the "version" field.
func VersionNotNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotNull(FieldVersion))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldContainsFold(FieldVersion, v))
}

// DomainsIsNil applies the IsNil predicate on the "domains" field.
func DomainsIsNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIsNull(FieldDomains))
}

// DomainsNotNil applies the NotNil predicate on the "domains" field.
func DomainsNotNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotNull(FieldDomains))
}

// LayersIsNil applies the IsNil predicate on the "layers" field.
func LayersIsNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIsNull(FieldLayers))
}

// LayersNotNil applies the NotNil predicate on the "layers" field.
func LayersNotNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotNull(FieldLayers))
}

// MetricsIsNil applies the IsNil predicate on the "metrics" field.
func MetricsIsNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIsNull(FieldMetrics))
}

// MetricsNotNil applies the NotNil predicate on the "metrics" field.
func MetricsNotNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotNull(FieldMetrics))
}

// MaturityIsNil applies the IsNil predicate on the "maturity" field.
func MaturityIsNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIsNull(FieldMaturity))
}

// MaturityNotNil applies the NotNil predicate on the "maturity" field.
func MaturityNotNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotNull(FieldMaturity))
}

// SliStateIsNil applies the IsNil predicate on the "sli_state" field.
func SliStateIsNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIsNull(FieldSliState))
}

// SliStateNotNil applies the NotNil predicate on the "sli_state" field.
func SliStateNotNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotNull(FieldSliState))
}

// MaturityStateIsNil applies the IsNil predicate on the "maturity_state" field.
func MaturityStateIsNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIsNull(FieldMaturityState))
}

// MaturityStateNotNil applies the NotNil predicate on the "maturity_state" field.
func MaturityStateNotNil() predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotNull(FieldMaturityState))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PRISMDocument) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PRISMDocument) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PRISMDocument) predicate.PRISMDocument {
	return predicate.PRISMDocument(sql.NotPredicates(p))
}
