// Code generated by ent, DO NOT EDIT.

package initiativedependency

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the initiativedependency type in the database.
	Label = "initiative_dependency"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceInitiativeID holds the string denoting the source_initiative_id field in the database.
	FieldSourceInitiativeID = "source_initiative_id"
	// FieldTargetInitiativeID holds the string denoting the target_initiative_id field in the database.
	FieldTargetInitiativeID = "target_initiative_id"
	// FieldRelationship holds the string denoting the relationship field in the database.
	FieldRelationship = "relationship"
	// Table holds the table name of the initiativedependency in the database.
	Table = "initiative_dependencies"
)

// Columns holds all SQL columns for initiativedependency fields.
var Columns = []string{
	FieldID,
	FieldSourceInitiativeID,
	FieldTargetInitiativeID,
	FieldRelationship,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SourceInitiativeIDValidator is a validator for the "source_initiative_id" field. It is called by the builders before save.
	SourceInitiativeIDValidator func(string) error
	// TargetInitiativeIDValidator is a validator for the "target_initiative_id" field. It is called by the builders before save.
	TargetInitiativeIDValidator func(string) error
	// RelationshipValidator is a validator for the "relationship" field. It is called by the builders before save.
	RelationshipValidator func(string) error
)

// OrderOption defines the ordering options for the InitiativeDependency queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourceInitiativeID orders the results by the source_initiative_id field.
func BySourceInitiativeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceInitiativeID, opts...).ToFunc()
}

// ByTargetInitiativeID orders the results by the target_initiative_id field.
func ByTargetInitiativeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetInitiativeID, opts...).ToFunc()
}

// ByRelationship orders the results by the relationship field.
func ByRelationship(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelationship, opts...).ToFunc()
}
