// Code generated by ent, DO NOT EDIT.

package initiativedependency

import (
	"entgo.io/ent/dialect/sql"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEQ(FieldTenantID, v))
}

// SourceInitiativeID applies equality check predicate on the "source_initiative_id" field. It's identical to SourceInitiativeIDEQ.
func SourceInitiativeID(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEQ(FieldSourceInitiativeID, v))
}

// TargetInitiativeID applies equality check predicate on the "target_initiative_id" field. It's identical to TargetInitiativeIDEQ.
func TargetInitiativeID(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEQ(FieldTargetInitiativeID, v))
}

// Relationship applies equality check predicate on the "relationship" field. It's identical to RelationshipEQ.
func Relationship(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEQ(FieldRelationship, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldNotNull(FieldTenantID))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldContainsFold(FieldTenantID, v))
}

// SourceInitiativeIDEQ applies the EQ predicate on the "source_initiative_id" field.
func SourceInitiativeIDEQ(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEQ(FieldSourceInitiativeID, v))
}

// SourceInitiativeIDNEQ applies the NEQ predicate on the "source_initiative_id" field.
func SourceInitiativeIDNEQ(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldNEQ(FieldSourceInitiativeID, v))
}

// SourceInitiativeIDIn applies the In predicate on the "source_initiative_id" field.
func SourceInitiativeIDIn(vs ...string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldIn(FieldSourceInitiativeID, vs...))
}

// SourceInitiativeIDNotIn applies the NotIn predicate on the "source_initiative_id" field.
func SourceInitiativeIDNotIn(vs ...string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldNotIn(FieldSourceInitiativeID, vs...))
}

// SourceInitiativeIDGT applies the GT predicate on the "source_initiative_id" field.
func SourceInitiativeIDGT(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldGT(FieldSourceInitiativeID, v))
}

// SourceInitiativeIDGTE applies the GTE predicate on the "source_initiative_id" field.
func SourceInitiativeIDGTE(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldGTE(FieldSourceInitiativeID, v))
}

// SourceInitiativeIDLT applies the LT predicate on the "source_initiative_id" field.
func SourceInitiativeIDLT(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldLT(FieldSourceInitiativeID, v))
}

// SourceInitiativeIDLTE applies the LTE predicate on the "source_initiative_id" field.
func SourceInitiativeIDLTE(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldLTE(FieldSourceInitiativeID, v))
}

// SourceInitiativeIDContains applies the Contains predicate on the "source_initiative_id" field.
func SourceInitiativeIDContains(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldContains(FieldSourceInitiativeID, v))
}

// SourceInitiativeIDHasPrefix applies the HasPrefix predicate on the "source_initiative_id" field.
func SourceInitiativeIDHasPrefix(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldHasPrefix(FieldSourceInitiativeID, v))
}

// SourceInitiativeIDHasSuffix applies the HasSuffix predicate on the "source_initiative_id" field.
func SourceInitiativeIDHasSuffix(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldHasSuffix(FieldSourceInitiativeID, v))
}

// SourceInitiativeIDEqualFold applies the EqualFold predicate on the "source_initiative_id" field.
func SourceInitiativeIDEqualFold(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEqualFold(FieldSourceInitiativeID, v))
}

// SourceInitiativeIDContainsFold applies the ContainsFold predicate on the "source_initiative_id" field.
func SourceInitiativeIDContainsFold(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldContainsFold(FieldSourceInitiativeID, v))
}

// TargetInitiativeIDEQ applies the EQ predicate on the "target_initiative_id" field.
func TargetInitiativeIDEQ(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEQ(FieldTargetInitiativeID, v))
}

// TargetInitiativeIDNEQ applies the NEQ predicate on the "target_initiative_id" field.
func TargetInitiativeIDNEQ(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldNEQ(FieldTargetInitiativeID, v))
}

// TargetInitiativeIDIn applies the In predicate on the "target_initiative_id" field.
func TargetInitiativeIDIn(vs ...string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldIn(FieldTargetInitiativeID, vs...))
}

// TargetInitiativeIDNotIn applies the NotIn predicate on the "target_initiative_id" field.
func TargetInitiativeIDNotIn(vs ...string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldNotIn(FieldTargetInitiativeID, vs...))
}

// TargetInitiativeIDGT applies the GT predicate on the "target_initiative_id" field.
func TargetInitiativeIDGT(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldGT(FieldTargetInitiativeID, v))
}

// TargetInitiativeIDGTE applies the GTE predicate on the "target_initiative_id" field.
func TargetInitiativeIDGTE(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldGTE(FieldTargetInitiativeID, v))
}

// TargetInitiativeIDLT applies the LT predicate on the "target_initiative_id" field.
func TargetInitiativeIDLT(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldLT(FieldTargetInitiativeID, v))
}

// TargetInitiativeIDLTE applies the LTE predicate on the "target_initiative_id" field.
func TargetInitiativeIDLTE(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldLTE(FieldTargetInitiativeID, v))
}

// TargetInitiativeIDContains applies the Contains predicate on the "target_initiative_id" field.
func TargetInitiativeIDContains(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldContains(FieldTargetInitiativeID, v))
}

// TargetInitiativeIDHasPrefix applies the HasPrefix predicate on the "target_initiative_id" field.
func TargetInitiativeIDHasPrefix(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldHasPrefix(FieldTargetInitiativeID, v))
}

// TargetInitiativeIDHasSuffix applies the HasSuffix predicate on the "target_initiative_id" field.
func TargetInitiativeIDHasSuffix(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldHasSuffix(FieldTargetInitiativeID, v))
}

// TargetInitiativeIDEqualFold applies the EqualFold predicate on the "target_initiative_id" field.
func TargetInitiativeIDEqualFold(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEqualFold(FieldTargetInitiativeID, v))
}

// TargetInitiativeIDContainsFold applies the ContainsFold predicate on the "target_initiative_id" field.
func TargetInitiativeIDContainsFold(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldContainsFold(FieldTargetInitiativeID, v))
}

// RelationshipEQ applies the EQ predicate on the "relationship" field.
func RelationshipEQ(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEQ(FieldRelationship, v))
}

// RelationshipNEQ applies the NEQ predicate on the "relationship" field.
func RelationshipNEQ(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldNEQ(FieldRelationship, v))
}

// RelationshipIn applies the In predicate on the "relationship" field.
func RelationshipIn(vs ...string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldIn(FieldRelationship, vs...))
}

// RelationshipNotIn applies the NotIn predicate on the "relationship" field.
func RelationshipNotIn(vs ...string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldNotIn(FieldRelationship, vs...))
}

// RelationshipGT applies the GT predicate on the "relationship" field.
func RelationshipGT(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldGT(FieldRelationship, v))
}

// RelationshipGTE applies the GTE predicate on the "relationship" field.
func RelationshipGTE(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldGTE(FieldRelationship, v))
}

// RelationshipLT applies the LT predicate on the "relationship" field.
func RelationshipLT(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldLT(FieldRelationship, v))
}

// RelationshipLTE applies the LTE predicate on the "relationship" field.
func RelationshipLTE(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldLTE(FieldRelationship, v))
}

// RelationshipContains applies the Contains predicate on the "relationship" field.
func RelationshipContains(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldContains(FieldRelationship, v))
}

// RelationshipHasPrefix applies the HasPrefix predicate on the "relationship" field.
func RelationshipHasPrefix(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldHasPrefix(FieldRelationship, v))
}

// RelationshipHasSuffix applies the HasSuffix predicate on the "relationship" field.
func RelationshipHasSuffix(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldHasSuffix(FieldRelationship, v))
}

// RelationshipEqualFold applies the EqualFold predicate on the "relationship" field.
func RelationshipEqualFold(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldEqualFold(FieldRelationship, v))
}

// RelationshipContainsFold applies the ContainsFold predicate on the "relationship" field.
func RelationshipContainsFold(v string) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.FieldContainsFold(FieldRelationship, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InitiativeDependency) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InitiativeDependency) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InitiativeDependency) predicate.InitiativeDependency {
	return predicate.InitiativeDependency(sql.NotPredicates(p))
}
