// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ProductBuildersHQ/visionstudio/ent/initiativeworkflow"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
)

// InitiativeWorkflowUpdate is the builder for updating InitiativeWorkflow entities.
type InitiativeWorkflowUpdate struct {
	config
	hooks    []Hook
	mutation *InitiativeWorkflowMutation
}

// Where appends a list predicates to the InitiativeWorkflowUpdate builder.
func (_u *InitiativeWorkflowUpdate) Where(ps ...predicate.InitiativeWorkflow) *InitiativeWorkflowUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *InitiativeWorkflowUpdate) SetWorkflowID(v string) *InitiativeWorkflowUpdate {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *InitiativeWorkflowUpdate) SetNillableWorkflowID(v *string) *InitiativeWorkflowUpdate {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetSelectedAt sets the "selected_at" field.
func (_u *InitiativeWorkflowUpdate) SetSelectedAt(v time.Time) *InitiativeWorkflowUpdate {
	_u.mutation.SetSelectedAt(v)
	return _u
}

// SetNillableSelectedAt sets the "selected_at" field if the given value is not nil.
func (_u *InitiativeWorkflowUpdate) SetNillableSelectedAt(v *time.Time) *InitiativeWorkflowUpdate {
	if v != nil {
		_u.SetSelectedAt(*v)
	}
	return _u
}

// Mutation returns the InitiativeWorkflowMutation object of the builder.
func (_u *InitiativeWorkflowUpdate) Mutation() *InitiativeWorkflowMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InitiativeWorkflowUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InitiativeWorkflowUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InitiativeWorkflowUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InitiativeWorkflowUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InitiativeWorkflowUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(initiativeworkflow.Table, initiativeworkflow.Columns, sqlgraph.NewFieldSpec(initiativeworkflow.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WorkflowID(); ok {
		_spec.SetField(initiativeworkflow.FieldWorkflowID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SelectedAt(); ok {
		_spec.SetField(initiativeworkflow.FieldSelectedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{initiativeworkflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InitiativeWorkflowUpdateOne is the builder for updating a single InitiativeWorkflow entity.
type InitiativeWorkflowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InitiativeWorkflowMutation
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *InitiativeWorkflowUpdateOne) SetWorkflowID(v string) *InitiativeWorkflowUpdateOne {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *InitiativeWorkflowUpdateOne) SetNillableWorkflowID(v *string) *InitiativeWorkflowUpdateOne {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetSelectedAt sets the "selected_at" field.
func (_u *InitiativeWorkflowUpdateOne) SetSelectedAt(v time.Time) *InitiativeWorkflowUpdateOne {
	_u.mutation.SetSelectedAt(v)
	return _u
}

// SetNillableSelectedAt sets the "selected_at" field if the given value is not nil.
func (_u *InitiativeWorkflowUpdateOne) SetNillableSelectedAt(v *time.Time) *InitiativeWorkflowUpdateOne {
	if v != nil {
		_u.SetSelectedAt(*v)
	}
	return _u
}

// Mutation returns the InitiativeWorkflowMutation object of the builder.
func (_u *InitiativeWorkflowUpdateOne) Mutation() *InitiativeWorkflowMutation {
	return _u.mutation
}

// Where appends a list predicates to the InitiativeWorkflowUpdate builder.
func (_u *InitiativeWorkflowUpdateOne) Where(ps ...predicate.InitiativeWorkflow) *InitiativeWorkflowUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InitiativeWorkflowUpdateOne) Select(field string, fields ...string) *InitiativeWorkflowUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InitiativeWorkflow entity.
func (_u *InitiativeWorkflowUpdateOne) Save(ctx context.Context) (*InitiativeWorkflow, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InitiativeWorkflowUpdateOne) SaveX(ctx context.Context) *InitiativeWorkflow {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InitiativeWorkflowUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InitiativeWorkflowUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InitiativeWorkflowUpdateOne) sqlSave(ctx context.Context) (_node *InitiativeWorkflow, err error) {
	_spec := sqlgraph.NewUpdateSpec(initiativeworkflow.Table, initiativeworkflow.Columns, sqlgraph.NewFieldSpec(initiativeworkflow.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InitiativeWorkflow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, initiativeworkflow.FieldID)
		for _, f := range fields {
			if !initiativeworkflow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != initiativeworkflow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WorkflowID(); ok {
		_spec.SetField(initiativeworkflow.FieldWorkflowID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SelectedAt(); ok {
		_spec.SetField(initiativeworkflow.FieldSelectedAt, field.TypeTime, value)
	}
	_node = &InitiativeWorkflow{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{initiativeworkflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
