// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ProductBuildersHQ/visionstudio/ent/initiativedependency"
)

// InitiativeDependencyCreate is the builder for creating a InitiativeDependency entity.
type InitiativeDependencyCreate struct {
	config
	mutation *InitiativeDependencyMutation
	hooks    []Hook
}

// SetSourceInitiativeID sets the "source_initiative_id" field.
func (_c *InitiativeDependencyCreate) SetSourceInitiativeID(v string) *InitiativeDependencyCreate {
	_c.mutation.SetSourceInitiativeID(v)
	return _c
}

// SetTargetInitiativeID sets the "target_initiative_id" field.
func (_c *InitiativeDependencyCreate) SetTargetInitiativeID(v string) *InitiativeDependencyCreate {
	_c.mutation.SetTargetInitiativeID(v)
	return _c
}

// SetRelationship sets the "relationship" field.
func (_c *InitiativeDependencyCreate) SetRelationship(v string) *InitiativeDependencyCreate {
	_c.mutation.SetRelationship(v)
	return _c
}

// Mutation returns the InitiativeDependencyMutation object of the builder.
func (_c *InitiativeDependencyCreate) Mutation() *InitiativeDependencyMutation {
	return _c.mutation
}

// Save creates the InitiativeDependency in the database.
func (_c *InitiativeDependencyCreate) Save(ctx context.Context) (*InitiativeDependency, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InitiativeDependencyCreate) SaveX(ctx context.Context) *InitiativeDependency {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InitiativeDependencyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InitiativeDependencyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InitiativeDependencyCreate) check() error {
	if _, ok := _c.mutation.SourceInitiativeID(); !ok {
		return &ValidationError{Name: "source_initiative_id", err: errors.New(`ent: missing required field "InitiativeDependency.source_initiative_id"`)}
	}
	if v, ok := _c.mutation.SourceInitiativeID(); ok {
		if err := initiativedependency.SourceInitiativeIDValidator(v); err != nil {
			return &ValidationError{Name: "source_initiative_id", err: fmt.Errorf(`ent: validator failed for field "InitiativeDependency.source_initiative_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetInitiativeID(); !ok {
		return &ValidationError{Name: "target_initiative_id", err: errors.New(`ent: missing required field "InitiativeDependency.target_initiative_id"`)}
	}
	if v, ok := _c.mutation.TargetInitiativeID(); ok {
		if err := initiativedependency.TargetInitiativeIDValidator(v); err != nil {
			return &ValidationError{Name: "target_initiative_id", err: fmt.Errorf(`ent: validator failed for field "InitiativeDependency.target_initiative_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Relationship(); !ok {
		return &ValidationError{Name: "relationship", err: errors.New(`ent: missing required field "InitiativeDependency.relationship"`)}
	}
	if v, ok := _c.mutation.Relationship(); ok {
		if err := initiativedependency.RelationshipValidator(v); err != nil {
			return &ValidationError{Name: "relationship", err: fmt.Errorf(`ent: validator failed for field "InitiativeDependency.relationship": %w`, err)}
		}
	}
	return nil
}

func (_c *InitiativeDependencyCreate) sqlSave(ctx context.Context) (*InitiativeDependency, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InitiativeDependencyCreate) createSpec() (*InitiativeDependency, *sqlgraph.CreateSpec) {
	var (
		_node = &InitiativeDependency{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(initiativedependency.Table, sqlgraph.NewFieldSpec(initiativedependency.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SourceInitiativeID(); ok {
		_spec.SetField(initiativedependency.FieldSourceInitiativeID, field.TypeString, value)
		_node.SourceInitiativeID = value
	}
	if value, ok := _c.mutation.TargetInitiativeID(); ok {
		_spec.SetField(initiativedependency.FieldTargetInitiativeID, field.TypeString, value)
		_node.TargetInitiativeID = value
	}
	if value, ok := _c.mutation.Relationship(); ok {
		_spec.SetField(initiativedependency.FieldRelationship, field.TypeString, value)
		_node.Relationship = value
	}
	return _node, _spec
}

// InitiativeDependencyCreateBulk is the builder for creating many InitiativeDependency entities in bulk.
type InitiativeDependencyCreateBulk struct {
	config
	err      error
	builders []*InitiativeDependencyCreate
}

// Save creates the InitiativeDependency entities in the database.
func (_c *InitiativeDependencyCreateBulk) Save(ctx context.Context) ([]*InitiativeDependency, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InitiativeDependency, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InitiativeDependencyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InitiativeDependencyCreateBulk) SaveX(ctx context.Context) []*InitiativeDependency {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InitiativeDependencyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InitiativeDependencyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
