// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ProductBuildersHQ/visionstudio/ent/initiativeworkflow"
)

// InitiativeWorkflow is the model entity for the InitiativeWorkflow schema.
type InitiativeWorkflow struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// WorkflowID holds the value of the "workflow_id" field.
	WorkflowID string `json:"workflow_id,omitempty"`
	// SelectedAt holds the value of the "selected_at" field.
	SelectedAt   time.Time `json:"selected_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InitiativeWorkflow) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case initiativeworkflow.FieldID, initiativeworkflow.FieldWorkflowID:
			values[i] = new(sql.NullString)
		case initiativeworkflow.FieldSelectedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InitiativeWorkflow fields.
func (_m *InitiativeWorkflow) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case initiativeworkflow.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case initiativeworkflow.FieldWorkflowID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_id", values[i])
			} else if value.Valid {
				_m.WorkflowID = value.String
			}
		case initiativeworkflow.FieldSelectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field selected_at", values[i])
			} else if value.Valid {
				_m.SelectedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InitiativeWorkflow.
// This includes values selected through modifiers, order, etc.
func (_m *InitiativeWorkflow) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InitiativeWorkflow.
// Note that you need to call InitiativeWorkflow.Unwrap() before calling this method if this InitiativeWorkflow
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InitiativeWorkflow) Update() *InitiativeWorkflowUpdateOne {
	return NewInitiativeWorkflowClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InitiativeWorkflow entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InitiativeWorkflow) Unwrap() *InitiativeWorkflow {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InitiativeWorkflow is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InitiativeWorkflow) String() string {
	var builder strings.Builder
	builder.WriteString("InitiativeWorkflow(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("workflow_id=")
	builder.WriteString(_m.WorkflowID)
	builder.WriteString(", ")
	builder.WriteString("selected_at=")
	builder.WriteString(_m.SelectedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InitiativeWorkflows is a parsable slice of InitiativeWorkflow.
type InitiativeWorkflows []*InitiativeWorkflow
