// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ProductBuildersHQ/visionstudio/ent/initiativedependency"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
)

// InitiativeDependencyUpdate is the builder for updating InitiativeDependency entities.
type InitiativeDependencyUpdate struct {
	config
	hooks    []Hook
	mutation *InitiativeDependencyMutation
}

// Where appends a list predicates to the InitiativeDependencyUpdate builder.
func (_u *InitiativeDependencyUpdate) Where(ps ...predicate.InitiativeDependency) *InitiativeDependencyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceInitiativeID sets the "source_initiative_id" field.
func (_u *InitiativeDependencyUpdate) SetSourceInitiativeID(v string) *InitiativeDependencyUpdate {
	_u.mutation.SetSourceInitiativeID(v)
	return _u
}

// SetNillableSourceInitiativeID sets the "source_initiative_id" field if the given value is not nil.
func (_u *InitiativeDependencyUpdate) SetNillableSourceInitiativeID(v *string) *InitiativeDependencyUpdate {
	if v != nil {
		_u.SetSourceInitiativeID(*v)
	}
	return _u
}

// SetTargetInitiativeID sets the "target_initiative_id" field.
func (_u *InitiativeDependencyUpdate) SetTargetInitiativeID(v string) *InitiativeDependencyUpdate {
	_u.mutation.SetTargetInitiativeID(v)
	return _u
}

// SetNillableTargetInitiativeID sets the "target_initiative_id" field if the given value is not nil.
func (_u *InitiativeDependencyUpdate) SetNillableTargetInitiativeID(v *string) *InitiativeDependencyUpdate {
	if v != nil {
		_u.SetTargetInitiativeID(*v)
	}
	return _u
}

// SetRelationship sets the "relationship" field.
func (_u *InitiativeDependencyUpdate) SetRelationship(v string) *InitiativeDependencyUpdate {
	_u.mutation.SetRelationship(v)
	return _u
}

// SetNillableRelationship sets the "relationship" field if the given value is not nil.
func (_u *InitiativeDependencyUpdate) SetNillableRelationship(v *string) *InitiativeDependencyUpdate {
	if v != nil {
		_u.SetRelationship(*v)
	}
	return _u
}

// Mutation returns the InitiativeDependencyMutation object of the builder.
func (_u *InitiativeDependencyUpdate) Mutation() *InitiativeDependencyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InitiativeDependencyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InitiativeDependencyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InitiativeDependencyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InitiativeDependencyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InitiativeDependencyUpdate) check() error {
	if v, ok := _u.mutation.SourceInitiativeID(); ok {
		if err := initiativedependency.SourceInitiativeIDValidator(v); err != nil {
			return &ValidationError{Name: "source_initiative_id", err: fmt.Errorf(`ent: validator failed for field "InitiativeDependency.source_initiative_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetInitiativeID(); ok {
		if err := initiativedependency.TargetInitiativeIDValidator(v); err != nil {
			return &ValidationError{Name: "target_initiative_id", err: fmt.Errorf(`ent: validator failed for field "InitiativeDependency.target_initiative_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Relationship(); ok {
		if err := initiativedependency.RelationshipValidator(v); err != nil {
			return &ValidationError{Name: "relationship", err: fmt.Errorf(`ent: validator failed for field "InitiativeDependency.relationship": %w`, err)}
		}
	}
	return nil
}

func (_u *InitiativeDependencyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(initiativedependency.Table, initiativedependency.Columns, sqlgraph.NewFieldSpec(initiativedependency.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceInitiativeID(); ok {
		_spec.SetField(initiativedependency.FieldSourceInitiativeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetInitiativeID(); ok {
		_spec.SetField(initiativedependency.FieldTargetInitiativeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Relationship(); ok {
		_spec.SetField(initiativedependency.FieldRelationship, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{initiativedependency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InitiativeDependencyUpdateOne is the builder for updating a single InitiativeDependency entity.
type InitiativeDependencyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InitiativeDependencyMutation
}

// SetSourceInitiativeID sets the "source_initiative_id" field.
func (_u *InitiativeDependencyUpdateOne) SetSourceInitiativeID(v string) *InitiativeDependencyUpdateOne {
	_u.mutation.SetSourceInitiativeID(v)
	return _u
}

// SetNillableSourceInitiativeID sets the "source_initiative_id" field if the given value is not nil.
func (_u *InitiativeDependencyUpdateOne) SetNillableSourceInitiativeID(v *string) *InitiativeDependencyUpdateOne {
	if v != nil {
		_u.SetSourceInitiativeID(*v)
	}
	return _u
}

// SetTargetInitiativeID sets the "target_initiative_id" field.
func (_u *InitiativeDependencyUpdateOne) SetTargetInitiativeID(v string) *InitiativeDependencyUpdateOne {
	_u.mutation.SetTargetInitiativeID(v)
	return _u
}

// SetNillableTargetInitiativeID sets the "target_initiative_id" field if the given value is not nil.
func (_u *InitiativeDependencyUpdateOne) SetNillableTargetInitiativeID(v *string) *InitiativeDependencyUpdateOne {
	if v != nil {
		_u.SetTargetInitiativeID(*v)
	}
	return _u
}

// SetRelationship sets the "relationship" field.
func (_u *InitiativeDependencyUpdateOne) SetRelationship(v string) *InitiativeDependencyUpdateOne {
	_u.mutation.SetRelationship(v)
	return _u
}

// SetNillableRelationship sets the "relationship" field if the given value is not nil.
func (_u *InitiativeDependencyUpdateOne) SetNillableRelationship(v *string) *InitiativeDependencyUpdateOne {
	if v != nil {
		_u.SetRelationship(*v)
	}
	return _u
}

// Mutation returns the InitiativeDependencyMutation object of the builder.
func (_u *InitiativeDependencyUpdateOne) Mutation() *InitiativeDependencyMutation {
	return _u.mutation
}

// Where appends a list predicates to the InitiativeDependencyUpdate builder.
func (_u *InitiativeDependencyUpdateOne) Where(ps ...predicate.InitiativeDependency) *InitiativeDependencyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InitiativeDependencyUpdateOne) Select(field string, fields ...string) *InitiativeDependencyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InitiativeDependency entity.
func (_u *InitiativeDependencyUpdateOne) Save(ctx context.Context) (*InitiativeDependency, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InitiativeDependencyUpdateOne) SaveX(ctx context.Context) *InitiativeDependency {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InitiativeDependencyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InitiativeDependencyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InitiativeDependencyUpdateOne) check() error {
	if v, ok := _u.mutation.SourceInitiativeID(); ok {
		if err := initiativedependency.SourceInitiativeIDValidator(v); err != nil {
			return &ValidationError{Name: "source_initiative_id", err: fmt.Errorf(`ent: validator failed for field "InitiativeDependency.source_initiative_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetInitiativeID(); ok {
		if err := initiativedependency.TargetInitiativeIDValidator(v); err != nil {
			return &ValidationError{Name: "target_initiative_id", err: fmt.Errorf(`ent: validator failed for field "InitiativeDependency.target_initiative_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Relationship(); ok {
		if err := initiativedependency.RelationshipValidator(v); err != nil {
			return &ValidationError{Name: "relationship", err: fmt.Errorf(`ent: validator failed for field "InitiativeDependency.relationship": %w`, err)}
		}
	}
	return nil
}

func (_u *InitiativeDependencyUpdateOne) sqlSave(ctx context.Context) (_node *InitiativeDependency, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(initiativedependency.Table, initiativedependency.Columns, sqlgraph.NewFieldSpec(initiativedependency.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InitiativeDependency.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, initiativedependency.FieldID)
		for _, f := range fields {
			if !initiativedependency.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != initiativedependency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceInitiativeID(); ok {
		_spec.SetField(initiativedependency.FieldSourceInitiativeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetInitiativeID(); ok {
		_spec.SetField(initiativedependency.FieldTargetInitiativeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Relationship(); ok {
		_spec.SetField(initiativedependency.FieldRelationship, field.TypeString, value)
	}
	_node = &InitiativeDependency{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{initiativedependency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
