// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ProductBuildersHQ/visionstudio/ent/initiative"
	"github.com/ProductBuildersHQ/visionstudio/ent/judgeresult"
	"github.com/ProductBuildersHQ/visionstudio/ent/judgerubric"
)

// JudgeResultCreate is the builder for creating a JudgeResult entity.
type JudgeResultCreate struct {
	config
	mutation *JudgeResultMutation
	hooks    []Hook
}

// SetInitiativeID sets the "initiative_id" field.
func (_c *JudgeResultCreate) SetInitiativeID(v string) *JudgeResultCreate {
	_c.mutation.SetInitiativeID(v)
	return _c
}

// SetSpecPath sets the "spec_path" field.
func (_c *JudgeResultCreate) SetSpecPath(v string) *JudgeResultCreate {
	_c.mutation.SetSpecPath(v)
	return _c
}

// SetScore sets the "score" field.
func (_c *JudgeResultCreate) SetScore(v float64) *JudgeResultCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_c *JudgeResultCreate) SetNillableScore(v *float64) *JudgeResultCreate {
	if v != nil {
		_c.SetScore(*v)
	}
	return _c
}

// SetRationale sets the "rationale" field.
func (_c *JudgeResultCreate) SetRationale(v string) *JudgeResultCreate {
	_c.mutation.SetRationale(v)
	return _c
}

// SetNillableRationale sets the "rationale" field if the given value is not nil.
func (_c *JudgeResultCreate) SetNillableRationale(v *string) *JudgeResultCreate {
	if v != nil {
		_c.SetRationale(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *JudgeResultCreate) SetModel(v string) *JudgeResultCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *JudgeResultCreate) SetNillableModel(v *string) *JudgeResultCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetEvaluatedAt sets the "evaluated_at" field.
func (_c *JudgeResultCreate) SetEvaluatedAt(v time.Time) *JudgeResultCreate {
	_c.mutation.SetEvaluatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *JudgeResultCreate) SetID(v string) *JudgeResultCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetRubricID sets the "rubric" edge to the JudgeRubric entity by ID.
func (_c *JudgeResultCreate) SetRubricID(id string) *JudgeResultCreate {
	_c.mutation.SetRubricID(id)
	return _c
}

// SetNillableRubricID sets the "rubric" edge to the JudgeRubric entity by ID if the given value is not nil.
func (_c *JudgeResultCreate) SetNillableRubricID(id *string) *JudgeResultCreate {
	if id != nil {
		_c = _c.SetRubricID(*id)
	}
	return _c
}

// SetRubric sets the "rubric" edge to the JudgeRubric entity.
func (_c *JudgeResultCreate) SetRubric(v *JudgeRubric) *JudgeResultCreate {
	return _c.SetRubricID(v.ID)
}

// SetInitiative sets the "initiative" edge to the Initiative entity.
func (_c *JudgeResultCreate) SetInitiative(v *Initiative) *JudgeResultCreate {
	return _c.SetInitiativeID(v.ID)
}

// Mutation returns the JudgeResultMutation object of the builder.
func (_c *JudgeResultCreate) Mutation() *JudgeResultMutation {
	return _c.mutation
}

// Save creates the JudgeResult in the database.
func (_c *JudgeResultCreate) Save(ctx context.Context) (*JudgeResult, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JudgeResultCreate) SaveX(ctx context.Context) *JudgeResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JudgeResultCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JudgeResultCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JudgeResultCreate) check() error {
	if _, ok := _c.mutation.InitiativeID(); !ok {
		return &ValidationError{Name: "initiative_id", err: errors.New(`ent: missing required field "JudgeResult.initiative_id"`)}
	}
	if v, ok := _c.mutation.InitiativeID(); ok {
		if err := judgeresult.InitiativeIDValidator(v); err != nil {
			return &ValidationError{Name: "initiative_id", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.initiative_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SpecPath(); !ok {
		return &ValidationError{Name: "spec_path", err: errors.New(`ent: missing required field "JudgeResult.spec_path"`)}
	}
	if v, ok := _c.mutation.SpecPath(); ok {
		if err := judgeresult.SpecPathValidator(v); err != nil {
			return &ValidationError{Name: "spec_path", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.spec_path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := judgeresult.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EvaluatedAt(); !ok {
		return &ValidationError{Name: "evaluated_at", err: errors.New(`ent: missing required field "JudgeResult.evaluated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := judgeresult.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.id": %w`, err)}
		}
	}
	if len(_c.mutation.InitiativeIDs()) == 0 {
		return &ValidationError{Name: "initiative", err: errors.New(`ent: missing required edge "JudgeResult.initiative"`)}
	}
	return nil
}

func (_c *JudgeResultCreate) sqlSave(ctx context.Context) (*JudgeResult, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected JudgeResult.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JudgeResultCreate) createSpec() (*JudgeResult, *sqlgraph.CreateSpec) {
	var (
		_node = &JudgeResult{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(judgeresult.Table, sqlgraph.NewFieldSpec(judgeresult.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.SpecPath(); ok {
		_spec.SetField(judgeresult.FieldSpecPath, field.TypeString, value)
		_node.SpecPath = value
	}
	if value, ok := _c.mutation.Score(); ok {
		_spec.SetField(judgeresult.FieldScore, field.TypeFloat64, value)
		_node.Score = value
	}
	if value, ok := _c.mutation.Rationale(); ok {
		_spec.SetField(judgeresult.FieldRationale, field.TypeString, value)
		_node.Rationale = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(judgeresult.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.EvaluatedAt(); ok {
		_spec.SetField(judgeresult.FieldEvaluatedAt, field.TypeTime, value)
		_node.EvaluatedAt = value
	}
	if nodes := _c.mutation.RubricIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   judgeresult.RubricTable,
			Columns: []string{judgeresult.RubricColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(judgerubric.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.judge_rubric_results = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InitiativeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   judgeresult.InitiativeTable,
			Columns: []string{judgeresult.InitiativeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(initiative.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InitiativeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// JudgeResultCreateBulk is the builder for creating many JudgeResult entities in bulk.
type JudgeResultCreateBulk struct {
	config
	err      error
	builders []*JudgeResultCreate
}

// Save creates the JudgeResult entities in the database.
func (_c *JudgeResultCreateBulk) Save(ctx context.Context) ([]*JudgeResult, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*JudgeResult, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JudgeResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JudgeResultCreateBulk) SaveX(ctx context.Context) []*JudgeResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JudgeResultCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JudgeResultCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
