// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ProductBuildersHQ/visionstudio/ent/initiative"
	"github.com/ProductBuildersHQ/visionstudio/ent/judgeresult"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
)

// JudgeResultUpdate is the builder for updating JudgeResult entities.
type JudgeResultUpdate struct {
	config
	hooks    []Hook
	mutation *JudgeResultMutation
}

// Where appends a list predicates to the JudgeResultUpdate builder.
func (_u *JudgeResultUpdate) Where(ps ...predicate.JudgeResult) *JudgeResultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInitiativeID sets the "initiative_id" field.
func (_u *JudgeResultUpdate) SetInitiativeID(v string) *JudgeResultUpdate {
	_u.mutation.SetInitiativeID(v)
	return _u
}

// SetNillableInitiativeID sets the "initiative_id" field if the given value is not nil.
func (_u *JudgeResultUpdate) SetNillableInitiativeID(v *string) *JudgeResultUpdate {
	if v != nil {
		_u.SetInitiativeID(*v)
	}
	return _u
}

// SetSpecPath sets the "spec_path" field.
func (_u *JudgeResultUpdate) SetSpecPath(v string) *JudgeResultUpdate {
	_u.mutation.SetSpecPath(v)
	return _u
}

// SetNillableSpecPath sets the "spec_path" field if the given value is not nil.
func (_u *JudgeResultUpdate) SetNillableSpecPath(v *string) *JudgeResultUpdate {
	if v != nil {
		_u.SetSpecPath(*v)
	}
	return _u
}

// SetSpecType sets the "spec_type" field.
func (_u *JudgeResultUpdate) SetSpecType(v string) *JudgeResultUpdate {
	_u.mutation.SetSpecType(v)
	return _u
}

// SetNillableSpecType sets the "spec_type" field if the given value is not nil.
func (_u *JudgeResultUpdate) SetNillableSpecType(v *string) *JudgeResultUpdate {
	if v != nil {
		_u.SetSpecType(*v)
	}
	return _u
}

// ClearSpecType clears the value of the "spec_type" field.
func (_u *JudgeResultUpdate) ClearSpecType() *JudgeResultUpdate {
	_u.mutation.ClearSpecType()
	return _u
}

// SetEvaluatedAt sets the "evaluated_at" field.
func (_u *JudgeResultUpdate) SetEvaluatedAt(v time.Time) *JudgeResultUpdate {
	_u.mutation.SetEvaluatedAt(v)
	return _u
}

// SetNillableEvaluatedAt sets the "evaluated_at" field if the given value is not nil.
func (_u *JudgeResultUpdate) SetNillableEvaluatedAt(v *time.Time) *JudgeResultUpdate {
	if v != nil {
		_u.SetEvaluatedAt(*v)
	}
	return _u
}

// SetReport sets the "report" field.
func (_u *JudgeResultUpdate) SetReport(v map[string]interface{}) *JudgeResultUpdate {
	_u.mutation.SetReport(v)
	return _u
}

// ClearReport clears the value of the "report" field.
func (_u *JudgeResultUpdate) ClearReport() *JudgeResultUpdate {
	_u.mutation.ClearReport()
	return _u
}

// SetIntScore sets the "int_score" field.
func (_u *JudgeResultUpdate) SetIntScore(v int) *JudgeResultUpdate {
	_u.mutation.ResetIntScore()
	_u.mutation.SetIntScore(v)
	return _u
}

// SetNillableIntScore sets the "int_score" field if the given value is not nil.
func (_u *JudgeResultUpdate) SetNillableIntScore(v *int) *JudgeResultUpdate {
	if v != nil {
		_u.SetIntScore(*v)
	}
	return _u
}

// AddIntScore adds value to the "int_score" field.
func (_u *JudgeResultUpdate) AddIntScore(v int) *JudgeResultUpdate {
	_u.mutation.AddIntScore(v)
	return _u
}

// ClearIntScore clears the value of the "int_score" field.
func (_u *JudgeResultUpdate) ClearIntScore() *JudgeResultUpdate {
	_u.mutation.ClearIntScore()
	return _u
}

// SetPass sets the "pass" field.
func (_u *JudgeResultUpdate) SetPass(v bool) *JudgeResultUpdate {
	_u.mutation.SetPass(v)
	return _u
}

// SetNillablePass sets the "pass" field if the given value is not nil.
func (_u *JudgeResultUpdate) SetNillablePass(v *bool) *JudgeResultUpdate {
	if v != nil {
		_u.SetPass(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *JudgeResultUpdate) SetModel(v string) *JudgeResultUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *JudgeResultUpdate) SetNillableModel(v *string) *JudgeResultUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *JudgeResultUpdate) ClearModel() *JudgeResultUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetRubricID sets the "rubric_id" field.
func (_u *JudgeResultUpdate) SetRubricID(v string) *JudgeResultUpdate {
	_u.mutation.SetRubricID(v)
	return _u
}

// SetNillableRubricID sets the "rubric_id" field if the given value is not nil.
func (_u *JudgeResultUpdate) SetNillableRubricID(v *string) *JudgeResultUpdate {
	if v != nil {
		_u.SetRubricID(*v)
	}
	return _u
}

// ClearRubricID clears the value of the "rubric_id" field.
func (_u *JudgeResultUpdate) ClearRubricID() *JudgeResultUpdate {
	_u.mutation.ClearRubricID()
	return _u
}

// SetInitiative sets the "initiative" edge to the Initiative entity.
func (_u *JudgeResultUpdate) SetInitiative(v *Initiative) *JudgeResultUpdate {
	return _u.SetInitiativeID(v.ID)
}

// Mutation returns the JudgeResultMutation object of the builder.
func (_u *JudgeResultUpdate) Mutation() *JudgeResultMutation {
	return _u.mutation
}

// ClearInitiative clears the "initiative" edge to the Initiative entity.
func (_u *JudgeResultUpdate) ClearInitiative() *JudgeResultUpdate {
	_u.mutation.ClearInitiative()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JudgeResultUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JudgeResultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JudgeResultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JudgeResultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JudgeResultUpdate) check() error {
	if v, ok := _u.mutation.InitiativeID(); ok {
		if err := judgeresult.InitiativeIDValidator(v); err != nil {
			return &ValidationError{Name: "initiative_id", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.initiative_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpecPath(); ok {
		if err := judgeresult.SpecPathValidator(v); err != nil {
			return &ValidationError{Name: "spec_path", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.spec_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpecType(); ok {
		if err := judgeresult.SpecTypeValidator(v); err != nil {
			return &ValidationError{Name: "spec_type", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.spec_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := judgeresult.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RubricID(); ok {
		if err := judgeresult.RubricIDValidator(v); err != nil {
			return &ValidationError{Name: "rubric_id", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.rubric_id": %w`, err)}
		}
	}
	if _u.mutation.InitiativeCleared() && len(_u.mutation.InitiativeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JudgeResult.initiative"`)
	}
	return nil
}

func (_u *JudgeResultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(judgeresult.Table, judgeresult.Columns, sqlgraph.NewFieldSpec(judgeresult.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SpecPath(); ok {
		_spec.SetField(judgeresult.FieldSpecPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecType(); ok {
		_spec.SetField(judgeresult.FieldSpecType, field.TypeString, value)
	}
	if _u.mutation.SpecTypeCleared() {
		_spec.ClearField(judgeresult.FieldSpecType, field.TypeString)
	}
	if value, ok := _u.mutation.EvaluatedAt(); ok {
		_spec.SetField(judgeresult.FieldEvaluatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Report(); ok {
		_spec.SetField(judgeresult.FieldReport, field.TypeJSON, value)
	}
	if _u.mutation.ReportCleared() {
		_spec.ClearField(judgeresult.FieldReport, field.TypeJSON)
	}
	if value, ok := _u.mutation.IntScore(); ok {
		_spec.SetField(judgeresult.FieldIntScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntScore(); ok {
		_spec.AddField(judgeresult.FieldIntScore, field.TypeInt, value)
	}
	if _u.mutation.IntScoreCleared() {
		_spec.ClearField(judgeresult.FieldIntScore, field.TypeInt)
	}
	if value, ok := _u.mutation.Pass(); ok {
		_spec.SetField(judgeresult.FieldPass, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(judgeresult.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(judgeresult.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.RubricID(); ok {
		_spec.SetField(judgeresult.FieldRubricID, field.TypeString, value)
	}
	if _u.mutation.RubricIDCleared() {
		_spec.ClearField(judgeresult.FieldRubricID, field.TypeString)
	}
	if _u.mutation.InitiativeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   judgeresult.InitiativeTable,
			Columns: []string{judgeresult.InitiativeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(initiative.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InitiativeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   judgeresult.InitiativeTable,
			Columns: []string{judgeresult.InitiativeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(initiative.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{judgeresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JudgeResultUpdateOne is the builder for updating a single JudgeResult entity.
type JudgeResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JudgeResultMutation
}

// SetInitiativeID sets the "initiative_id" field.
func (_u *JudgeResultUpdateOne) SetInitiativeID(v string) *JudgeResultUpdateOne {
	_u.mutation.SetInitiativeID(v)
	return _u
}

// SetNillableInitiativeID sets the "initiative_id" field if the given value is not nil.
func (_u *JudgeResultUpdateOne) SetNillableInitiativeID(v *string) *JudgeResultUpdateOne {
	if v != nil {
		_u.SetInitiativeID(*v)
	}
	return _u
}

// SetSpecPath sets the "spec_path" field.
func (_u *JudgeResultUpdateOne) SetSpecPath(v string) *JudgeResultUpdateOne {
	_u.mutation.SetSpecPath(v)
	return _u
}

// SetNillableSpecPath sets the "spec_path" field if the given value is not nil.
func (_u *JudgeResultUpdateOne) SetNillableSpecPath(v *string) *JudgeResultUpdateOne {
	if v != nil {
		_u.SetSpecPath(*v)
	}
	return _u
}

// SetSpecType sets the "spec_type" field.
func (_u *JudgeResultUpdateOne) SetSpecType(v string) *JudgeResultUpdateOne {
	_u.mutation.SetSpecType(v)
	return _u
}

// SetNillableSpecType sets the "spec_type" field if the given value is not nil.
func (_u *JudgeResultUpdateOne) SetNillableSpecType(v *string) *JudgeResultUpdateOne {
	if v != nil {
		_u.SetSpecType(*v)
	}
	return _u
}

// ClearSpecType clears the value of the "spec_type" field.
func (_u *JudgeResultUpdateOne) ClearSpecType() *JudgeResultUpdateOne {
	_u.mutation.ClearSpecType()
	return _u
}

// SetEvaluatedAt sets the "evaluated_at" field.
func (_u *JudgeResultUpdateOne) SetEvaluatedAt(v time.Time) *JudgeResultUpdateOne {
	_u.mutation.SetEvaluatedAt(v)
	return _u
}

// SetNillableEvaluatedAt sets the "evaluated_at" field if the given value is not nil.
func (_u *JudgeResultUpdateOne) SetNillableEvaluatedAt(v *time.Time) *JudgeResultUpdateOne {
	if v != nil {
		_u.SetEvaluatedAt(*v)
	}
	return _u
}

// SetReport sets the "report" field.
func (_u *JudgeResultUpdateOne) SetReport(v map[string]interface{}) *JudgeResultUpdateOne {
	_u.mutation.SetReport(v)
	return _u
}

// ClearReport clears the value of the "report" field.
func (_u *JudgeResultUpdateOne) ClearReport() *JudgeResultUpdateOne {
	_u.mutation.ClearReport()
	return _u
}

// SetIntScore sets the "int_score" field.
func (_u *JudgeResultUpdateOne) SetIntScore(v int) *JudgeResultUpdateOne {
	_u.mutation.ResetIntScore()
	_u.mutation.SetIntScore(v)
	return _u
}

// SetNillableIntScore sets the "int_score" field if the given value is not nil.
func (_u *JudgeResultUpdateOne) SetNillableIntScore(v *int) *JudgeResultUpdateOne {
	if v != nil {
		_u.SetIntScore(*v)
	}
	return _u
}

// AddIntScore adds value to the "int_score" field.
func (_u *JudgeResultUpdateOne) AddIntScore(v int) *JudgeResultUpdateOne {
	_u.mutation.AddIntScore(v)
	return _u
}

// ClearIntScore clears the value of the "int_score" field.
func (_u *JudgeResultUpdateOne) ClearIntScore() *JudgeResultUpdateOne {
	_u.mutation.ClearIntScore()
	return _u
}

// SetPass sets the "pass" field.
func (_u *JudgeResultUpdateOne) SetPass(v bool) *JudgeResultUpdateOne {
	_u.mutation.SetPass(v)
	return _u
}

// SetNillablePass sets the "pass" field if the given value is not nil.
func (_u *JudgeResultUpdateOne) SetNillablePass(v *bool) *JudgeResultUpdateOne {
	if v != nil {
		_u.SetPass(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *JudgeResultUpdateOne) SetModel(v string) *JudgeResultUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *JudgeResultUpdateOne) SetNillableModel(v *string) *JudgeResultUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *JudgeResultUpdateOne) ClearModel() *JudgeResultUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetRubricID sets the "rubric_id" field.
func (_u *JudgeResultUpdateOne) SetRubricID(v string) *JudgeResultUpdateOne {
	_u.mutation.SetRubricID(v)
	return _u
}

// SetNillableRubricID sets the "rubric_id" field if the given value is not nil.
func (_u *JudgeResultUpdateOne) SetNillableRubricID(v *string) *JudgeResultUpdateOne {
	if v != nil {
		_u.SetRubricID(*v)
	}
	return _u
}

// ClearRubricID clears the value of the "rubric_id" field.
func (_u *JudgeResultUpdateOne) ClearRubricID() *JudgeResultUpdateOne {
	_u.mutation.ClearRubricID()
	return _u
}

// SetInitiative sets the "initiative" edge to the Initiative entity.
func (_u *JudgeResultUpdateOne) SetInitiative(v *Initiative) *JudgeResultUpdateOne {
	return _u.SetInitiativeID(v.ID)
}

// Mutation returns the JudgeResultMutation object of the builder.
func (_u *JudgeResultUpdateOne) Mutation() *JudgeResultMutation {
	return _u.mutation
}

// ClearInitiative clears the "initiative" edge to the Initiative entity.
func (_u *JudgeResultUpdateOne) ClearInitiative() *JudgeResultUpdateOne {
	_u.mutation.ClearInitiative()
	return _u
}

// Where appends a list predicates to the JudgeResultUpdate builder.
func (_u *JudgeResultUpdateOne) Where(ps ...predicate.JudgeResult) *JudgeResultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JudgeResultUpdateOne) Select(field string, fields ...string) *JudgeResultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated JudgeResult entity.
func (_u *JudgeResultUpdateOne) Save(ctx context.Context) (*JudgeResult, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JudgeResultUpdateOne) SaveX(ctx context.Context) *JudgeResult {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JudgeResultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JudgeResultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JudgeResultUpdateOne) check() error {
	if v, ok := _u.mutation.InitiativeID(); ok {
		if err := judgeresult.InitiativeIDValidator(v); err != nil {
			return &ValidationError{Name: "initiative_id", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.initiative_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpecPath(); ok {
		if err := judgeresult.SpecPathValidator(v); err != nil {
			return &ValidationError{Name: "spec_path", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.spec_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpecType(); ok {
		if err := judgeresult.SpecTypeValidator(v); err != nil {
			return &ValidationError{Name: "spec_type", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.spec_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := judgeresult.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RubricID(); ok {
		if err := judgeresult.RubricIDValidator(v); err != nil {
			return &ValidationError{Name: "rubric_id", err: fmt.Errorf(`ent: validator failed for field "JudgeResult.rubric_id": %w`, err)}
		}
	}
	if _u.mutation.InitiativeCleared() && len(_u.mutation.InitiativeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JudgeResult.initiative"`)
	}
	return nil
}

func (_u *JudgeResultUpdateOne) sqlSave(ctx context.Context) (_node *JudgeResult, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(judgeresult.Table, judgeresult.Columns, sqlgraph.NewFieldSpec(judgeresult.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "JudgeResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, judgeresult.FieldID)
		for _, f := range fields {
			if !judgeresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != judgeresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SpecPath(); ok {
		_spec.SetField(judgeresult.FieldSpecPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecType(); ok {
		_spec.SetField(judgeresult.FieldSpecType, field.TypeString, value)
	}
	if _u.mutation.SpecTypeCleared() {
		_spec.ClearField(judgeresult.FieldSpecType, field.TypeString)
	}
	if value, ok := _u.mutation.EvaluatedAt(); ok {
		_spec.SetField(judgeresult.FieldEvaluatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Report(); ok {
		_spec.SetField(judgeresult.FieldReport, field.TypeJSON, value)
	}
	if _u.mutation.ReportCleared() {
		_spec.ClearField(judgeresult.FieldReport, field.TypeJSON)
	}
	if value, ok := _u.mutation.IntScore(); ok {
		_spec.SetField(judgeresult.FieldIntScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntScore(); ok {
		_spec.AddField(judgeresult.FieldIntScore, field.TypeInt, value)
	}
	if _u.mutation.IntScoreCleared() {
		_spec.ClearField(judgeresult.FieldIntScore, field.TypeInt)
	}
	if value, ok := _u.mutation.Pass(); ok {
		_spec.SetField(judgeresult.FieldPass, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(judgeresult.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(judgeresult.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.RubricID(); ok {
		_spec.SetField(judgeresult.FieldRubricID, field.TypeString, value)
	}
	if _u.mutation.RubricIDCleared() {
		_spec.ClearField(judgeresult.FieldRubricID, field.TypeString)
	}
	if _u.mutation.InitiativeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   judgeresult.InitiativeTable,
			Columns: []string{judgeresult.InitiativeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(initiative.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InitiativeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   judgeresult.InitiativeTable,
			Columns: []string{judgeresult.InitiativeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(initiative.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &JudgeResult{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{judgeresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
