// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ProductBuildersHQ/visionstudio/ent/organization"
	"github.com/ProductBuildersHQ/visionstudio/ent/person"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
	"github.com/ProductBuildersHQ/visionstudio/ent/repository"
)

// OrganizationUpdate is the builder for updating Organization entities.
type OrganizationUpdate struct {
	config
	hooks    []Hook
	mutation *OrganizationMutation
}

// Where appends a list predicates to the OrganizationUpdate builder.
func (_u *OrganizationUpdate) Where(ps ...predicate.Organization) *OrganizationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLogin sets the "login" field.
func (_u *OrganizationUpdate) SetLogin(v string) *OrganizationUpdate {
	_u.mutation.SetLogin(v)
	return _u
}

// SetNillableLogin sets the "login" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableLogin(v *string) *OrganizationUpdate {
	if v != nil {
		_u.SetLogin(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *OrganizationUpdate) SetKind(v string) *OrganizationUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableKind(v *string) *OrganizationUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *OrganizationUpdate) SetDisplayName(v string) *OrganizationUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableDisplayName(v *string) *OrganizationUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *OrganizationUpdate) ClearDisplayName() *OrganizationUpdate {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetWebsite sets the "website" field.
func (_u *OrganizationUpdate) SetWebsite(v string) *OrganizationUpdate {
	_u.mutation.SetWebsite(v)
	return _u
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableWebsite(v *string) *OrganizationUpdate {
	if v != nil {
		_u.SetWebsite(*v)
	}
	return _u
}

// ClearWebsite clears the value of the "website" field.
func (_u *OrganizationUpdate) ClearWebsite() *OrganizationUpdate {
	_u.mutation.ClearWebsite()
	return _u
}

// SetReleasePageURL sets the "release_page_url" field.
func (_u *OrganizationUpdate) SetReleasePageURL(v string) *OrganizationUpdate {
	_u.mutation.SetReleasePageURL(v)
	return _u
}

// SetNillableReleasePageURL sets the "release_page_url" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableReleasePageURL(v *string) *OrganizationUpdate {
	if v != nil {
		_u.SetReleasePageURL(*v)
	}
	return _u
}

// ClearReleasePageURL clears the value of the "release_page_url" field.
func (_u *OrganizationUpdate) ClearReleasePageURL() *OrganizationUpdate {
	_u.mutation.ClearReleasePageURL()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *OrganizationUpdate) SetCreatedAt(v time.Time) *OrganizationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableCreatedAt(v *time.Time) *OrganizationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrganizationUpdate) SetUpdatedAt(v time.Time) *OrganizationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableUpdatedAt(v *time.Time) *OrganizationUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddRepositoryIDs adds the "repositories" edge to the Repository entity by IDs.
func (_u *OrganizationUpdate) AddRepositoryIDs(ids ...string) *OrganizationUpdate {
	_u.mutation.AddRepositoryIDs(ids...)
	return _u
}

// AddRepositories adds the "repositories" edges to the Repository entity.
func (_u *OrganizationUpdate) AddRepositories(v ...*Repository) *OrganizationUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRepositoryIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the Person entity by IDs.
func (_u *OrganizationUpdate) AddMemberIDs(ids ...string) *OrganizationUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the Person entity.
func (_u *OrganizationUpdate) AddMembers(v ...*Person) *OrganizationUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the OrganizationMutation object of the builder.
func (_u *OrganizationUpdate) Mutation() *OrganizationMutation {
	return _u.mutation
}

// ClearRepositories clears all "repositories" edges to the Repository entity.
func (_u *OrganizationUpdate) ClearRepositories() *OrganizationUpdate {
	_u.mutation.ClearRepositories()
	return _u
}

// RemoveRepositoryIDs removes the "repositories" edge to Repository entities by IDs.
func (_u *OrganizationUpdate) RemoveRepositoryIDs(ids ...string) *OrganizationUpdate {
	_u.mutation.RemoveRepositoryIDs(ids...)
	return _u
}

// RemoveRepositories removes "repositories" edges to Repository entities.
func (_u *OrganizationUpdate) RemoveRepositories(v ...*Repository) *OrganizationUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRepositoryIDs(ids...)
}

// ClearMembers clears all "members" edges to the Person entity.
func (_u *OrganizationUpdate) ClearMembers() *OrganizationUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to Person entities by IDs.
func (_u *OrganizationUpdate) RemoveMemberIDs(ids ...string) *OrganizationUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to Person entities.
func (_u *OrganizationUpdate) RemoveMembers(v ...*Person) *OrganizationUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrganizationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrganizationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationUpdate) check() error {
	if v, ok := _u.mutation.Login(); ok {
		if err := organization.LoginValidator(v); err != nil {
			return &ValidationError{Name: "login", err: fmt.Errorf(`ent: validator failed for field "Organization.login": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := organization.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Organization.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := organization.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Organization.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Website(); ok {
		if err := organization.WebsiteValidator(v); err != nil {
			return &ValidationError{Name: "website", err: fmt.Errorf(`ent: validator failed for field "Organization.website": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReleasePageURL(); ok {
		if err := organization.ReleasePageURLValidator(v); err != nil {
			return &ValidationError{Name: "release_page_url", err: fmt.Errorf(`ent: validator failed for field "Organization.release_page_url": %w`, err)}
		}
	}
	return nil
}

func (_u *OrganizationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organization.Table, organization.Columns, sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Login(); ok {
		_spec.SetField(organization.FieldLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(organization.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(organization.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(organization.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.Website(); ok {
		_spec.SetField(organization.FieldWebsite, field.TypeString, value)
	}
	if _u.mutation.WebsiteCleared() {
		_spec.ClearField(organization.FieldWebsite, field.TypeString)
	}
	if value, ok := _u.mutation.ReleasePageURL(); ok {
		_spec.SetField(organization.FieldReleasePageURL, field.TypeString, value)
	}
	if _u.mutation.ReleasePageURLCleared() {
		_spec.ClearField(organization.FieldReleasePageURL, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(organization.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(organization.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.RepositoriesTable,
			Columns: []string{organization.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepositoriesIDs(); len(nodes) > 0 && !_u.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.RepositoriesTable,
			Columns: []string{organization.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepositoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.RepositoriesTable,
			Columns: []string{organization.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   organization.MembersTable,
			Columns: organization.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   organization.MembersTable,
			Columns: organization.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   organization.MembersTable,
			Columns: organization.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrganizationUpdateOne is the builder for updating a single Organization entity.
type OrganizationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrganizationMutation
}

// SetLogin sets the "login" field.
func (_u *OrganizationUpdateOne) SetLogin(v string) *OrganizationUpdateOne {
	_u.mutation.SetLogin(v)
	return _u
}

// SetNillableLogin sets the "login" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableLogin(v *string) *OrganizationUpdateOne {
	if v != nil {
		_u.SetLogin(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *OrganizationUpdateOne) SetKind(v string) *OrganizationUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableKind(v *string) *OrganizationUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *OrganizationUpdateOne) SetDisplayName(v string) *OrganizationUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableDisplayName(v *string) *OrganizationUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *OrganizationUpdateOne) ClearDisplayName() *OrganizationUpdateOne {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetWebsite sets the "website" field.
func (_u *OrganizationUpdateOne) SetWebsite(v string) *OrganizationUpdateOne {
	_u.mutation.SetWebsite(v)
	return _u
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableWebsite(v *string) *OrganizationUpdateOne {
	if v != nil {
		_u.SetWebsite(*v)
	}
	return _u
}

// ClearWebsite clears the value of the "website" field.
func (_u *OrganizationUpdateOne) ClearWebsite() *OrganizationUpdateOne {
	_u.mutation.ClearWebsite()
	return _u
}

// SetReleasePageURL sets the "release_page_url" field.
func (_u *OrganizationUpdateOne) SetReleasePageURL(v string) *OrganizationUpdateOne {
	_u.mutation.SetReleasePageURL(v)
	return _u
}

// SetNillableReleasePageURL sets the "release_page_url" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableReleasePageURL(v *string) *OrganizationUpdateOne {
	if v != nil {
		_u.SetReleasePageURL(*v)
	}
	return _u
}

// ClearReleasePageURL clears the value of the "release_page_url" field.
func (_u *OrganizationUpdateOne) ClearReleasePageURL() *OrganizationUpdateOne {
	_u.mutation.ClearReleasePageURL()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *OrganizationUpdateOne) SetCreatedAt(v time.Time) *OrganizationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableCreatedAt(v *time.Time) *OrganizationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrganizationUpdateOne) SetUpdatedAt(v time.Time) *OrganizationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableUpdatedAt(v *time.Time) *OrganizationUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddRepositoryIDs adds the "repositories" edge to the Repository entity by IDs.
func (_u *OrganizationUpdateOne) AddRepositoryIDs(ids ...string) *OrganizationUpdateOne {
	_u.mutation.AddRepositoryIDs(ids...)
	return _u
}

// AddRepositories adds the "repositories" edges to the Repository entity.
func (_u *OrganizationUpdateOne) AddRepositories(v ...*Repository) *OrganizationUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRepositoryIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the Person entity by IDs.
func (_u *OrganizationUpdateOne) AddMemberIDs(ids ...string) *OrganizationUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the Person entity.
func (_u *OrganizationUpdateOne) AddMembers(v ...*Person) *OrganizationUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the OrganizationMutation object of the builder.
func (_u *OrganizationUpdateOne) Mutation() *OrganizationMutation {
	return _u.mutation
}

// ClearRepositories clears all "repositories" edges to the Repository entity.
func (_u *OrganizationUpdateOne) ClearRepositories() *OrganizationUpdateOne {
	_u.mutation.ClearRepositories()
	return _u
}

// RemoveRepositoryIDs removes the "repositories" edge to Repository entities by IDs.
func (_u *OrganizationUpdateOne) RemoveRepositoryIDs(ids ...string) *OrganizationUpdateOne {
	_u.mutation.RemoveRepositoryIDs(ids...)
	return _u
}

// RemoveRepositories removes "repositories" edges to Repository entities.
func (_u *OrganizationUpdateOne) RemoveRepositories(v ...*Repository) *OrganizationUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRepositoryIDs(ids...)
}

// ClearMembers clears all "members" edges to the Person entity.
func (_u *OrganizationUpdateOne) ClearMembers() *OrganizationUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to Person entities by IDs.
func (_u *OrganizationUpdateOne) RemoveMemberIDs(ids ...string) *OrganizationUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to Person entities.
func (_u *OrganizationUpdateOne) RemoveMembers(v ...*Person) *OrganizationUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Where appends a list predicates to the OrganizationUpdate builder.
func (_u *OrganizationUpdateOne) Where(ps ...predicate.Organization) *OrganizationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrganizationUpdateOne) Select(field string, fields ...string) *OrganizationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Organization entity.
func (_u *OrganizationUpdateOne) Save(ctx context.Context) (*Organization, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationUpdateOne) SaveX(ctx context.Context) *Organization {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrganizationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationUpdateOne) check() error {
	if v, ok := _u.mutation.Login(); ok {
		if err := organization.LoginValidator(v); err != nil {
			return &ValidationError{Name: "login", err: fmt.Errorf(`ent: validator failed for field "Organization.login": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := organization.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Organization.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := organization.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Organization.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Website(); ok {
		if err := organization.WebsiteValidator(v); err != nil {
			return &ValidationError{Name: "website", err: fmt.Errorf(`ent: validator failed for field "Organization.website": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReleasePageURL(); ok {
		if err := organization.ReleasePageURLValidator(v); err != nil {
			return &ValidationError{Name: "release_page_url", err: fmt.Errorf(`ent: validator failed for field "Organization.release_page_url": %w`, err)}
		}
	}
	return nil
}

func (_u *OrganizationUpdateOne) sqlSave(ctx context.Context) (_node *Organization, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organization.Table, organization.Columns, sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Organization.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organization.FieldID)
		for _, f := range fields {
			if !organization.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != organization.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Login(); ok {
		_spec.SetField(organization.FieldLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(organization.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(organization.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(organization.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.Website(); ok {
		_spec.SetField(organization.FieldWebsite, field.TypeString, value)
	}
	if _u.mutation.WebsiteCleared() {
		_spec.ClearField(organization.FieldWebsite, field.TypeString)
	}
	if value, ok := _u.mutation.ReleasePageURL(); ok {
		_spec.SetField(organization.FieldReleasePageURL, field.TypeString, value)
	}
	if _u.mutation.ReleasePageURLCleared() {
		_spec.ClearField(organization.FieldReleasePageURL, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(organization.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(organization.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.RepositoriesTable,
			Columns: []string{organization.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepositoriesIDs(); len(nodes) > 0 && !_u.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.RepositoriesTable,
			Columns: []string{organization.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepositoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.RepositoriesTable,
			Columns: []string{organization.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   organization.MembersTable,
			Columns: organization.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   organization.MembersTable,
			Columns: organization.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   organization.MembersTable,
			Columns: organization.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Organization{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
