// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/ProductBuildersHQ/visionstudio/ent/organization"
	"github.com/ProductBuildersHQ/visionstudio/ent/person"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
)

// PersonUpdate is the builder for updating Person entities.
type PersonUpdate struct {
	config
	hooks    []Hook
	mutation *PersonMutation
}

// Where appends a list predicates to the PersonUpdate builder.
func (_u *PersonUpdate) Where(ps ...predicate.Person) *PersonUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGithubLogin sets the "github_login" field.
func (_u *PersonUpdate) SetGithubLogin(v string) *PersonUpdate {
	_u.mutation.SetGithubLogin(v)
	return _u
}

// SetNillableGithubLogin sets the "github_login" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableGithubLogin(v *string) *PersonUpdate {
	if v != nil {
		_u.SetGithubLogin(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *PersonUpdate) SetDisplayName(v string) *PersonUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableDisplayName(v *string) *PersonUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *PersonUpdate) ClearDisplayName() *PersonUpdate {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetEmailIdentities sets the "email_identities" field.
func (_u *PersonUpdate) SetEmailIdentities(v []string) *PersonUpdate {
	_u.mutation.SetEmailIdentities(v)
	return _u
}

// AppendEmailIdentities appends value to the "email_identities" field.
func (_u *PersonUpdate) AppendEmailIdentities(v []string) *PersonUpdate {
	_u.mutation.AppendEmailIdentities(v)
	return _u
}

// ClearEmailIdentities clears the value of the "email_identities" field.
func (_u *PersonUpdate) ClearEmailIdentities() *PersonUpdate {
	_u.mutation.ClearEmailIdentities()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PersonUpdate) SetCreatedAt(v time.Time) *PersonUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableCreatedAt(v *time.Time) *PersonUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PersonUpdate) SetUpdatedAt(v time.Time) *PersonUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableUpdatedAt(v *time.Time) *PersonUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddOrganizationIDs adds the "organizations" edge to the Organization entity by IDs.
func (_u *PersonUpdate) AddOrganizationIDs(ids ...string) *PersonUpdate {
	_u.mutation.AddOrganizationIDs(ids...)
	return _u
}

// AddOrganizations adds the "organizations" edges to the Organization entity.
func (_u *PersonUpdate) AddOrganizations(v ...*Organization) *PersonUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrganizationIDs(ids...)
}

// Mutation returns the PersonMutation object of the builder.
func (_u *PersonUpdate) Mutation() *PersonMutation {
	return _u.mutation
}

// ClearOrganizations clears all "organizations" edges to the Organization entity.
func (_u *PersonUpdate) ClearOrganizations() *PersonUpdate {
	_u.mutation.ClearOrganizations()
	return _u
}

// RemoveOrganizationIDs removes the "organizations" edge to Organization entities by IDs.
func (_u *PersonUpdate) RemoveOrganizationIDs(ids ...string) *PersonUpdate {
	_u.mutation.RemoveOrganizationIDs(ids...)
	return _u
}

// RemoveOrganizations removes "organizations" edges to Organization entities.
func (_u *PersonUpdate) RemoveOrganizations(v ...*Organization) *PersonUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrganizationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PersonUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PersonUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonUpdate) check() error {
	if v, ok := _u.mutation.GithubLogin(); ok {
		if err := person.GithubLoginValidator(v); err != nil {
			return &ValidationError{Name: "github_login", err: fmt.Errorf(`ent: validator failed for field "Person.github_login": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := person.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Person.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *PersonUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(person.Table, person.Columns, sqlgraph.NewFieldSpec(person.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GithubLogin(); ok {
		_spec.SetField(person.FieldGithubLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(person.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(person.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.EmailIdentities(); ok {
		_spec.SetField(person.FieldEmailIdentities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmailIdentities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, person.FieldEmailIdentities, value)
		})
	}
	if _u.mutation.EmailIdentitiesCleared() {
		_spec.ClearField(person.FieldEmailIdentities, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(person.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(person.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.OrganizationsTable,
			Columns: person.OrganizationsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrganizationsIDs(); len(nodes) > 0 && !_u.mutation.OrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.OrganizationsTable,
			Columns: person.OrganizationsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.OrganizationsTable,
			Columns: person.OrganizationsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{person.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PersonUpdateOne is the builder for updating a single Person entity.
type PersonUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PersonMutation
}

// SetGithubLogin sets the "github_login" field.
func (_u *PersonUpdateOne) SetGithubLogin(v string) *PersonUpdateOne {
	_u.mutation.SetGithubLogin(v)
	return _u
}

// SetNillableGithubLogin sets the "github_login" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableGithubLogin(v *string) *PersonUpdateOne {
	if v != nil {
		_u.SetGithubLogin(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *PersonUpdateOne) SetDisplayName(v string) *PersonUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableDisplayName(v *string) *PersonUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *PersonUpdateOne) ClearDisplayName() *PersonUpdateOne {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetEmailIdentities sets the "email_identities" field.
func (_u *PersonUpdateOne) SetEmailIdentities(v []string) *PersonUpdateOne {
	_u.mutation.SetEmailIdentities(v)
	return _u
}

// AppendEmailIdentities appends value to the "email_identities" field.
func (_u *PersonUpdateOne) AppendEmailIdentities(v []string) *PersonUpdateOne {
	_u.mutation.AppendEmailIdentities(v)
	return _u
}

// ClearEmailIdentities clears the value of the "email_identities" field.
func (_u *PersonUpdateOne) ClearEmailIdentities() *PersonUpdateOne {
	_u.mutation.ClearEmailIdentities()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PersonUpdateOne) SetCreatedAt(v time.Time) *PersonUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableCreatedAt(v *time.Time) *PersonUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PersonUpdateOne) SetUpdatedAt(v time.Time) *PersonUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableUpdatedAt(v *time.Time) *PersonUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddOrganizationIDs adds the "organizations" edge to the Organization entity by IDs.
func (_u *PersonUpdateOne) AddOrganizationIDs(ids ...string) *PersonUpdateOne {
	_u.mutation.AddOrganizationIDs(ids...)
	return _u
}

// AddOrganizations adds the "organizations" edges to the Organization entity.
func (_u *PersonUpdateOne) AddOrganizations(v ...*Organization) *PersonUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrganizationIDs(ids...)
}

// Mutation returns the PersonMutation object of the builder.
func (_u *PersonUpdateOne) Mutation() *PersonMutation {
	return _u.mutation
}

// ClearOrganizations clears all "organizations" edges to the Organization entity.
func (_u *PersonUpdateOne) ClearOrganizations() *PersonUpdateOne {
	_u.mutation.ClearOrganizations()
	return _u
}

// RemoveOrganizationIDs removes the "organizations" edge to Organization entities by IDs.
func (_u *PersonUpdateOne) RemoveOrganizationIDs(ids ...string) *PersonUpdateOne {
	_u.mutation.RemoveOrganizationIDs(ids...)
	return _u
}

// RemoveOrganizations removes "organizations" edges to Organization entities.
func (_u *PersonUpdateOne) RemoveOrganizations(v ...*Organization) *PersonUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrganizationIDs(ids...)
}

// Where appends a list predicates to the PersonUpdate builder.
func (_u *PersonUpdateOne) Where(ps ...predicate.Person) *PersonUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PersonUpdateOne) Select(field string, fields ...string) *PersonUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Person entity.
func (_u *PersonUpdateOne) Save(ctx context.Context) (*Person, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonUpdateOne) SaveX(ctx context.Context) *Person {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PersonUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonUpdateOne) check() error {
	if v, ok := _u.mutation.GithubLogin(); ok {
		if err := person.GithubLoginValidator(v); err != nil {
			return &ValidationError{Name: "github_login", err: fmt.Errorf(`ent: validator failed for field "Person.github_login": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := person.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Person.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *PersonUpdateOne) sqlSave(ctx context.Context) (_node *Person, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(person.Table, person.Columns, sqlgraph.NewFieldSpec(person.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Person.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, person.FieldID)
		for _, f := range fields {
			if !person.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != person.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GithubLogin(); ok {
		_spec.SetField(person.FieldGithubLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(person.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(person.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.EmailIdentities(); ok {
		_spec.SetField(person.FieldEmailIdentities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmailIdentities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, person.FieldEmailIdentities, value)
		})
	}
	if _u.mutation.EmailIdentitiesCleared() {
		_spec.ClearField(person.FieldEmailIdentities, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(person.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(person.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.OrganizationsTable,
			Columns: person.OrganizationsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrganizationsIDs(); len(nodes) > 0 && !_u.mutation.OrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.OrganizationsTable,
			Columns: person.OrganizationsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.OrganizationsTable,
			Columns: person.OrganizationsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Person{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{person.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
