// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ProductBuildersHQ/visionstudio/ent/initiative"
	"github.com/ProductBuildersHQ/visionstudio/ent/phase"
	"github.com/ProductBuildersHQ/visionstudio/ent/roadmapitem"
)

// PhaseCreate is the builder for creating a Phase entity.
type PhaseCreate struct {
	config
	mutation *PhaseMutation
	hooks    []Hook
}

// SetSequenceNumber sets the "sequence_number" field.
func (_c *PhaseCreate) SetSequenceNumber(v int) *PhaseCreate {
	_c.mutation.SetSequenceNumber(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *PhaseCreate) SetTitle(v string) *PhaseCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetTheme sets the "theme" field.
func (_c *PhaseCreate) SetTheme(v string) *PhaseCreate {
	_c.mutation.SetTheme(v)
	return _c
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_c *PhaseCreate) SetNillableTheme(v *string) *PhaseCreate {
	if v != nil {
		_c.SetTheme(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PhaseCreate) SetID(v string) *PhaseCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetInitiativeID sets the "initiative" edge to the Initiative entity by ID.
func (_c *PhaseCreate) SetInitiativeID(id string) *PhaseCreate {
	_c.mutation.SetInitiativeID(id)
	return _c
}

// SetInitiative sets the "initiative" edge to the Initiative entity.
func (_c *PhaseCreate) SetInitiative(v *Initiative) *PhaseCreate {
	return _c.SetInitiativeID(v.ID)
}

// AddRoadmapItemIDs adds the "roadmap_items" edge to the RoadmapItem entity by IDs.
func (_c *PhaseCreate) AddRoadmapItemIDs(ids ...string) *PhaseCreate {
	_c.mutation.AddRoadmapItemIDs(ids...)
	return _c
}

// AddRoadmapItems adds the "roadmap_items" edges to the RoadmapItem entity.
func (_c *PhaseCreate) AddRoadmapItems(v ...*RoadmapItem) *PhaseCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRoadmapItemIDs(ids...)
}

// Mutation returns the PhaseMutation object of the builder.
func (_c *PhaseCreate) Mutation() *PhaseMutation {
	return _c.mutation
}

// Save creates the Phase in the database.
func (_c *PhaseCreate) Save(ctx context.Context) (*Phase, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PhaseCreate) SaveX(ctx context.Context) *Phase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PhaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PhaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PhaseCreate) check() error {
	if _, ok := _c.mutation.SequenceNumber(); !ok {
		return &ValidationError{Name: "sequence_number", err: errors.New(`ent: missing required field "Phase.sequence_number"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Phase.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := phase.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Phase.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Theme(); ok {
		if err := phase.ThemeValidator(v); err != nil {
			return &ValidationError{Name: "theme", err: fmt.Errorf(`ent: validator failed for field "Phase.theme": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := phase.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Phase.id": %w`, err)}
		}
	}
	if len(_c.mutation.InitiativeIDs()) == 0 {
		return &ValidationError{Name: "initiative", err: errors.New(`ent: missing required edge "Phase.initiative"`)}
	}
	return nil
}

func (_c *PhaseCreate) sqlSave(ctx context.Context) (*Phase, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Phase.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PhaseCreate) createSpec() (*Phase, *sqlgraph.CreateSpec) {
	var (
		_node = &Phase{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(phase.Table, sqlgraph.NewFieldSpec(phase.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.SequenceNumber(); ok {
		_spec.SetField(phase.FieldSequenceNumber, field.TypeInt, value)
		_node.SequenceNumber = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(phase.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Theme(); ok {
		_spec.SetField(phase.FieldTheme, field.TypeString, value)
		_node.Theme = value
	}
	if nodes := _c.mutation.InitiativeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   phase.InitiativeTable,
			Columns: []string{phase.InitiativeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(initiative.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.initiative_phases = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoadmapItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   phase.RoadmapItemsTable,
			Columns: []string{phase.RoadmapItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roadmapitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PhaseCreateBulk is the builder for creating many Phase entities in bulk.
type PhaseCreateBulk struct {
	config
	err      error
	builders []*PhaseCreate
}

// Save creates the Phase entities in the database.
func (_c *PhaseCreateBulk) Save(ctx context.Context) ([]*Phase, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Phase, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PhaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PhaseCreateBulk) SaveX(ctx context.Context) []*Phase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PhaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PhaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
