// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
	"github.com/ProductBuildersHQ/visionstudio/ent/prismdocument"
)

// PRISMDocumentUpdate is the builder for updating PRISMDocument entities.
type PRISMDocumentUpdate struct {
	config
	hooks    []Hook
	mutation *PRISMDocumentMutation
}

// Where appends a list predicates to the PRISMDocumentUpdate builder.
func (_u *PRISMDocumentUpdate) Where(ps ...predicate.PRISMDocument) *PRISMDocumentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrganization sets the "organization" field.
func (_u *PRISMDocumentUpdate) SetOrganization(v string) *PRISMDocumentUpdate {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *PRISMDocumentUpdate) SetNillableOrganization(v *string) *PRISMDocumentUpdate {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// ClearOrganization clears the value of the "organization" field.
func (_u *PRISMDocumentUpdate) ClearOrganization() *PRISMDocumentUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// SetRepositoryID sets the "repository_id" field.
func (_u *PRISMDocumentUpdate) SetRepositoryID(v string) *PRISMDocumentUpdate {
	_u.mutation.SetRepositoryID(v)
	return _u
}

// SetNillableRepositoryID sets the "repository_id" field if the given value is not nil.
func (_u *PRISMDocumentUpdate) SetNillableRepositoryID(v *string) *PRISMDocumentUpdate {
	if v != nil {
		_u.SetRepositoryID(*v)
	}
	return _u
}

// ClearRepositoryID clears the value of the "repository_id" field.
func (_u *PRISMDocumentUpdate) ClearRepositoryID() *PRISMDocumentUpdate {
	_u.mutation.ClearRepositoryID()
	return _u
}

// SetName sets the "name" field.
func (_u *PRISMDocumentUpdate) SetName(v string) *PRISMDocumentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PRISMDocumentUpdate) SetNillableName(v *string) *PRISMDocumentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PRISMDocumentUpdate) SetDescription(v string) *PRISMDocumentUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PRISMDocumentUpdate) SetNillableDescription(v *string) *PRISMDocumentUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PRISMDocumentUpdate) ClearDescription() *PRISMDocumentUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetVersion sets the "version" field.
func (_u *PRISMDocumentUpdate) SetVersion(v string) *PRISMDocumentUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PRISMDocumentUpdate) SetNillableVersion(v *string) *PRISMDocumentUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *PRISMDocumentUpdate) ClearVersion() *PRISMDocumentUpdate {
	_u.mutation.ClearVersion()
	return _u
}

// SetDomains sets the "domains" field.
func (_u *PRISMDocumentUpdate) SetDomains(v []interface{}) *PRISMDocumentUpdate {
	_u.mutation.SetDomains(v)
	return _u
}

// AppendDomains appends value to the "domains" field.
func (_u *PRISMDocumentUpdate) AppendDomains(v []interface{}) *PRISMDocumentUpdate {
	_u.mutation.AppendDomains(v)
	return _u
}

// ClearDomains clears the value of the "domains" field.
func (_u *PRISMDocumentUpdate) ClearDomains() *PRISMDocumentUpdate {
	_u.mutation.ClearDomains()
	return _u
}

// SetLayers sets the "layers" field.
func (_u *PRISMDocumentUpdate) SetLayers(v []interface{}) *PRISMDocumentUpdate {
	_u.mutation.SetLayers(v)
	return _u
}

// AppendLayers appends value to the "layers" field.
func (_u *PRISMDocumentUpdate) AppendLayers(v []interface{}) *PRISMDocumentUpdate {
	_u.mutation.AppendLayers(v)
	return _u
}

// ClearLayers clears the value of the "layers" field.
func (_u *PRISMDocumentUpdate) ClearLayers() *PRISMDocumentUpdate {
	_u.mutation.ClearLayers()
	return _u
}

// SetMetrics sets the "metrics" field.
func (_u *PRISMDocumentUpdate) SetMetrics(v []interface{}) *PRISMDocumentUpdate {
	_u.mutation.SetMetrics(v)
	return _u
}

// AppendMetrics appends value to the "metrics" field.
func (_u *PRISMDocumentUpdate) AppendMetrics(v []interface{}) *PRISMDocumentUpdate {
	_u.mutation.AppendMetrics(v)
	return _u
}

// ClearMetrics clears the value of the "metrics" field.
func (_u *PRISMDocumentUpdate) ClearMetrics() *PRISMDocumentUpdate {
	_u.mutation.ClearMetrics()
	return _u
}

// SetMaturity sets the "maturity" field.
func (_u *PRISMDocumentUpdate) SetMaturity(v map[string]interface{}) *PRISMDocumentUpdate {
	_u.mutation.SetMaturity(v)
	return _u
}

// ClearMaturity clears the value of the "maturity" field.
func (_u *PRISMDocumentUpdate) ClearMaturity() *PRISMDocumentUpdate {
	_u.mutation.ClearMaturity()
	return _u
}

// SetSliState sets the "sli_state" field.
func (_u *PRISMDocumentUpdate) SetSliState(v map[string]interface{}) *PRISMDocumentUpdate {
	_u.mutation.SetSliState(v)
	return _u
}

// ClearSliState clears the value of the "sli_state" field.
func (_u *PRISMDocumentUpdate) ClearSliState() *PRISMDocumentUpdate {
	_u.mutation.ClearSliState()
	return _u
}

// SetMaturityState sets the "maturity_state" field.
func (_u *PRISMDocumentUpdate) SetMaturityState(v map[string]interface{}) *PRISMDocumentUpdate {
	_u.mutation.SetMaturityState(v)
	return _u
}

// ClearMaturityState clears the value of the "maturity_state" field.
func (_u *PRISMDocumentUpdate) ClearMaturityState() *PRISMDocumentUpdate {
	_u.mutation.ClearMaturityState()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PRISMDocumentUpdate) SetCreatedAt(v time.Time) *PRISMDocumentUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PRISMDocumentUpdate) SetNillableCreatedAt(v *time.Time) *PRISMDocumentUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PRISMDocumentUpdate) SetUpdatedAt(v time.Time) *PRISMDocumentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PRISMDocumentUpdate) SetNillableUpdatedAt(v *time.Time) *PRISMDocumentUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the PRISMDocumentMutation object of the builder.
func (_u *PRISMDocumentUpdate) Mutation() *PRISMDocumentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PRISMDocumentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PRISMDocumentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PRISMDocumentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PRISMDocumentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PRISMDocumentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(prismdocument.Table, prismdocument.Columns, sqlgraph.NewFieldSpec(prismdocument.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(prismdocument.FieldOrganization, field.TypeString, value)
	}
	if _u.mutation.OrganizationCleared() {
		_spec.ClearField(prismdocument.FieldOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.RepositoryID(); ok {
		_spec.SetField(prismdocument.FieldRepositoryID, field.TypeString, value)
	}
	if _u.mutation.RepositoryIDCleared() {
		_spec.ClearField(prismdocument.FieldRepositoryID, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(prismdocument.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(prismdocument.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(prismdocument.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(prismdocument.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(prismdocument.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Domains(); ok {
		_spec.SetField(prismdocument.FieldDomains, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDomains(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prismdocument.FieldDomains, value)
		})
	}
	if _u.mutation.DomainsCleared() {
		_spec.ClearField(prismdocument.FieldDomains, field.TypeJSON)
	}
	if value, ok := _u.mutation.Layers(); ok {
		_spec.SetField(prismdocument.FieldLayers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLayers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prismdocument.FieldLayers, value)
		})
	}
	if _u.mutation.LayersCleared() {
		_spec.ClearField(prismdocument.FieldLayers, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metrics(); ok {
		_spec.SetField(prismdocument.FieldMetrics, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetrics(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prismdocument.FieldMetrics, value)
		})
	}
	if _u.mutation.MetricsCleared() {
		_spec.ClearField(prismdocument.FieldMetrics, field.TypeJSON)
	}
	if value, ok := _u.mutation.Maturity(); ok {
		_spec.SetField(prismdocument.FieldMaturity, field.TypeJSON, value)
	}
	if _u.mutation.MaturityCleared() {
		_spec.ClearField(prismdocument.FieldMaturity, field.TypeJSON)
	}
	if value, ok := _u.mutation.SliState(); ok {
		_spec.SetField(prismdocument.FieldSliState, field.TypeJSON, value)
	}
	if _u.mutation.SliStateCleared() {
		_spec.ClearField(prismdocument.FieldSliState, field.TypeJSON)
	}
	if value, ok := _u.mutation.MaturityState(); ok {
		_spec.SetField(prismdocument.FieldMaturityState, field.TypeJSON, value)
	}
	if _u.mutation.MaturityStateCleared() {
		_spec.ClearField(prismdocument.FieldMaturityState, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(prismdocument.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prismdocument.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prismdocument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PRISMDocumentUpdateOne is the builder for updating a single PRISMDocument entity.
type PRISMDocumentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PRISMDocumentMutation
}

// SetOrganization sets the "organization" field.
func (_u *PRISMDocumentUpdateOne) SetOrganization(v string) *PRISMDocumentUpdateOne {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *PRISMDocumentUpdateOne) SetNillableOrganization(v *string) *PRISMDocumentUpdateOne {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// ClearOrganization clears the value of the "organization" field.
func (_u *PRISMDocumentUpdateOne) ClearOrganization() *PRISMDocumentUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// SetRepositoryID sets the "repository_id" field.
func (_u *PRISMDocumentUpdateOne) SetRepositoryID(v string) *PRISMDocumentUpdateOne {
	_u.mutation.SetRepositoryID(v)
	return _u
}

// SetNillableRepositoryID sets the "repository_id" field if the given value is not nil.
func (_u *PRISMDocumentUpdateOne) SetNillableRepositoryID(v *string) *PRISMDocumentUpdateOne {
	if v != nil {
		_u.SetRepositoryID(*v)
	}
	return _u
}

// ClearRepositoryID clears the value of the "repository_id" field.
func (_u *PRISMDocumentUpdateOne) ClearRepositoryID() *PRISMDocumentUpdateOne {
	_u.mutation.ClearRepositoryID()
	return _u
}

// SetName sets the "name" field.
func (_u *PRISMDocumentUpdateOne) SetName(v string) *PRISMDocumentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PRISMDocumentUpdateOne) SetNillableName(v *string) *PRISMDocumentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PRISMDocumentUpdateOne) SetDescription(v string) *PRISMDocumentUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PRISMDocumentUpdateOne) SetNillableDescription(v *string) *PRISMDocumentUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PRISMDocumentUpdateOne) ClearDescription() *PRISMDocumentUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetVersion sets the "version" field.
func (_u *PRISMDocumentUpdateOne) SetVersion(v string) *PRISMDocumentUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PRISMDocumentUpdateOne) SetNillableVersion(v *string) *PRISMDocumentUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *PRISMDocumentUpdateOne) ClearVersion() *PRISMDocumentUpdateOne {
	_u.mutation.ClearVersion()
	return _u
}

// SetDomains sets the "domains" field.
func (_u *PRISMDocumentUpdateOne) SetDomains(v []interface{}) *PRISMDocumentUpdateOne {
	_u.mutation.SetDomains(v)
	return _u
}

// AppendDomains appends value to the "domains" field.
func (_u *PRISMDocumentUpdateOne) AppendDomains(v []interface{}) *PRISMDocumentUpdateOne {
	_u.mutation.AppendDomains(v)
	return _u
}

// ClearDomains clears the value of the "domains" field.
func (_u *PRISMDocumentUpdateOne) ClearDomains() *PRISMDocumentUpdateOne {
	_u.mutation.ClearDomains()
	return _u
}

// SetLayers sets the "layers" field.
func (_u *PRISMDocumentUpdateOne) SetLayers(v []interface{}) *PRISMDocumentUpdateOne {
	_u.mutation.SetLayers(v)
	return _u
}

// AppendLayers appends value to the "layers" field.
func (_u *PRISMDocumentUpdateOne) AppendLayers(v []interface{}) *PRISMDocumentUpdateOne {
	_u.mutation.AppendLayers(v)
	return _u
}

// ClearLayers clears the value of the "layers" field.
func (_u *PRISMDocumentUpdateOne) ClearLayers() *PRISMDocumentUpdateOne {
	_u.mutation.ClearLayers()
	return _u
}

// SetMetrics sets the "metrics" field.
func (_u *PRISMDocumentUpdateOne) SetMetrics(v []interface{}) *PRISMDocumentUpdateOne {
	_u.mutation.SetMetrics(v)
	return _u
}

// AppendMetrics appends value to the "metrics" field.
func (_u *PRISMDocumentUpdateOne) AppendMetrics(v []interface{}) *PRISMDocumentUpdateOne {
	_u.mutation.AppendMetrics(v)
	return _u
}

// ClearMetrics clears the value of the "metrics" field.
func (_u *PRISMDocumentUpdateOne) ClearMetrics() *PRISMDocumentUpdateOne {
	_u.mutation.ClearMetrics()
	return _u
}

// SetMaturity sets the "maturity" field.
func (_u *PRISMDocumentUpdateOne) SetMaturity(v map[string]interface{}) *PRISMDocumentUpdateOne {
	_u.mutation.SetMaturity(v)
	return _u
}

// ClearMaturity clears the value of the "maturity" field.
func (_u *PRISMDocumentUpdateOne) ClearMaturity() *PRISMDocumentUpdateOne {
	_u.mutation.ClearMaturity()
	return _u
}

// SetSliState sets the "sli_state" field.
func (_u *PRISMDocumentUpdateOne) SetSliState(v map[string]interface{}) *PRISMDocumentUpdateOne {
	_u.mutation.SetSliState(v)
	return _u
}

// ClearSliState clears the value of the "sli_state" field.
func (_u *PRISMDocumentUpdateOne) ClearSliState() *PRISMDocumentUpdateOne {
	_u.mutation.ClearSliState()
	return _u
}

// SetMaturityState sets the "maturity_state" field.
func (_u *PRISMDocumentUpdateOne) SetMaturityState(v map[string]interface{}) *PRISMDocumentUpdateOne {
	_u.mutation.SetMaturityState(v)
	return _u
}

// ClearMaturityState clears the value of the "maturity_state" field.
func (_u *PRISMDocumentUpdateOne) ClearMaturityState() *PRISMDocumentUpdateOne {
	_u.mutation.ClearMaturityState()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PRISMDocumentUpdateOne) SetCreatedAt(v time.Time) *PRISMDocumentUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PRISMDocumentUpdateOne) SetNillableCreatedAt(v *time.Time) *PRISMDocumentUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PRISMDocumentUpdateOne) SetUpdatedAt(v time.Time) *PRISMDocumentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PRISMDocumentUpdateOne) SetNillableUpdatedAt(v *time.Time) *PRISMDocumentUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the PRISMDocumentMutation object of the builder.
func (_u *PRISMDocumentUpdateOne) Mutation() *PRISMDocumentMutation {
	return _u.mutation
}

// Where appends a list predicates to the PRISMDocumentUpdate builder.
func (_u *PRISMDocumentUpdateOne) Where(ps ...predicate.PRISMDocument) *PRISMDocumentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PRISMDocumentUpdateOne) Select(field string, fields ...string) *PRISMDocumentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PRISMDocument entity.
func (_u *PRISMDocumentUpdateOne) Save(ctx context.Context) (*PRISMDocument, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PRISMDocumentUpdateOne) SaveX(ctx context.Context) *PRISMDocument {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PRISMDocumentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PRISMDocumentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PRISMDocumentUpdateOne) sqlSave(ctx context.Context) (_node *PRISMDocument, err error) {
	_spec := sqlgraph.NewUpdateSpec(prismdocument.Table, prismdocument.Columns, sqlgraph.NewFieldSpec(prismdocument.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PRISMDocument.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prismdocument.FieldID)
		for _, f := range fields {
			if !prismdocument.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != prismdocument.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(prismdocument.FieldOrganization, field.TypeString, value)
	}
	if _u.mutation.OrganizationCleared() {
		_spec.ClearField(prismdocument.FieldOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.RepositoryID(); ok {
		_spec.SetField(prismdocument.FieldRepositoryID, field.TypeString, value)
	}
	if _u.mutation.RepositoryIDCleared() {
		_spec.ClearField(prismdocument.FieldRepositoryID, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(prismdocument.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(prismdocument.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(prismdocument.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(prismdocument.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(prismdocument.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Domains(); ok {
		_spec.SetField(prismdocument.FieldDomains, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDomains(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prismdocument.FieldDomains, value)
		})
	}
	if _u.mutation.DomainsCleared() {
		_spec.ClearField(prismdocument.FieldDomains, field.TypeJSON)
	}
	if value, ok := _u.mutation.Layers(); ok {
		_spec.SetField(prismdocument.FieldLayers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLayers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prismdocument.FieldLayers, value)
		})
	}
	if _u.mutation.LayersCleared() {
		_spec.ClearField(prismdocument.FieldLayers, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metrics(); ok {
		_spec.SetField(prismdocument.FieldMetrics, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetrics(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prismdocument.FieldMetrics, value)
		})
	}
	if _u.mutation.MetricsCleared() {
		_spec.ClearField(prismdocument.FieldMetrics, field.TypeJSON)
	}
	if value, ok := _u.mutation.Maturity(); ok {
		_spec.SetField(prismdocument.FieldMaturity, field.TypeJSON, value)
	}
	if _u.mutation.MaturityCleared() {
		_spec.ClearField(prismdocument.FieldMaturity, field.TypeJSON)
	}
	if value, ok := _u.mutation.SliState(); ok {
		_spec.SetField(prismdocument.FieldSliState, field.TypeJSON, value)
	}
	if _u.mutation.SliStateCleared() {
		_spec.ClearField(prismdocument.FieldSliState, field.TypeJSON)
	}
	if value, ok := _u.mutation.MaturityState(); ok {
		_spec.SetField(prismdocument.FieldMaturityState, field.TypeJSON, value)
	}
	if _u.mutation.MaturityStateCleared() {
		_spec.ClearField(prismdocument.FieldMaturityState, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(prismdocument.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prismdocument.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PRISMDocument{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prismdocument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
