// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
	"github.com/ProductBuildersHQ/visionstudio/ent/prismgoal"
)

// PRISMGoalUpdate is the builder for updating PRISMGoal entities.
type PRISMGoalUpdate struct {
	config
	hooks    []Hook
	mutation *PRISMGoalMutation
}

// Where appends a list predicates to the PRISMGoalUpdate builder.
func (_u *PRISMGoalUpdate) Where(ps ...predicate.PRISMGoal) *PRISMGoalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrganization sets the "organization" field.
func (_u *PRISMGoalUpdate) SetOrganization(v string) *PRISMGoalUpdate {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *PRISMGoalUpdate) SetNillableOrganization(v *string) *PRISMGoalUpdate {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// ClearOrganization clears the value of the "organization" field.
func (_u *PRISMGoalUpdate) ClearOrganization() *PRISMGoalUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// SetRepositoryID sets the "repository_id" field.
func (_u *PRISMGoalUpdate) SetRepositoryID(v string) *PRISMGoalUpdate {
	_u.mutation.SetRepositoryID(v)
	return _u
}

// SetNillableRepositoryID sets the "repository_id" field if the given value is not nil.
func (_u *PRISMGoalUpdate) SetNillableRepositoryID(v *string) *PRISMGoalUpdate {
	if v != nil {
		_u.SetRepositoryID(*v)
	}
	return _u
}

// SetGoalType sets the "goal_type" field.
func (_u *PRISMGoalUpdate) SetGoalType(v string) *PRISMGoalUpdate {
	_u.mutation.SetGoalType(v)
	return _u
}

// SetNillableGoalType sets the "goal_type" field if the given value is not nil.
func (_u *PRISMGoalUpdate) SetNillableGoalType(v *string) *PRISMGoalUpdate {
	if v != nil {
		_u.SetGoalType(*v)
	}
	return _u
}

// SetDocument sets the "document" field.
func (_u *PRISMGoalUpdate) SetDocument(v map[string]interface{}) *PRISMGoalUpdate {
	_u.mutation.SetDocument(v)
	return _u
}

// ClearDocument clears the value of the "document" field.
func (_u *PRISMGoalUpdate) ClearDocument() *PRISMGoalUpdate {
	_u.mutation.ClearDocument()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PRISMGoalUpdate) SetCreatedAt(v time.Time) *PRISMGoalUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PRISMGoalUpdate) SetNillableCreatedAt(v *time.Time) *PRISMGoalUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PRISMGoalUpdate) SetUpdatedAt(v time.Time) *PRISMGoalUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PRISMGoalUpdate) SetNillableUpdatedAt(v *time.Time) *PRISMGoalUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the PRISMGoalMutation object of the builder.
func (_u *PRISMGoalUpdate) Mutation() *PRISMGoalMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PRISMGoalUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PRISMGoalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PRISMGoalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PRISMGoalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PRISMGoalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(prismgoal.Table, prismgoal.Columns, sqlgraph.NewFieldSpec(prismgoal.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(prismgoal.FieldOrganization, field.TypeString, value)
	}
	if _u.mutation.OrganizationCleared() {
		_spec.ClearField(prismgoal.FieldOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.RepositoryID(); ok {
		_spec.SetField(prismgoal.FieldRepositoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoalType(); ok {
		_spec.SetField(prismgoal.FieldGoalType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Document(); ok {
		_spec.SetField(prismgoal.FieldDocument, field.TypeJSON, value)
	}
	if _u.mutation.DocumentCleared() {
		_spec.ClearField(prismgoal.FieldDocument, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(prismgoal.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prismgoal.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prismgoal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PRISMGoalUpdateOne is the builder for updating a single PRISMGoal entity.
type PRISMGoalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PRISMGoalMutation
}

// SetOrganization sets the "organization" field.
func (_u *PRISMGoalUpdateOne) SetOrganization(v string) *PRISMGoalUpdateOne {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *PRISMGoalUpdateOne) SetNillableOrganization(v *string) *PRISMGoalUpdateOne {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// ClearOrganization clears the value of the "organization" field.
func (_u *PRISMGoalUpdateOne) ClearOrganization() *PRISMGoalUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// SetRepositoryID sets the "repository_id" field.
func (_u *PRISMGoalUpdateOne) SetRepositoryID(v string) *PRISMGoalUpdateOne {
	_u.mutation.SetRepositoryID(v)
	return _u
}

// SetNillableRepositoryID sets the "repository_id" field if the given value is not nil.
func (_u *PRISMGoalUpdateOne) SetNillableRepositoryID(v *string) *PRISMGoalUpdateOne {
	if v != nil {
		_u.SetRepositoryID(*v)
	}
	return _u
}

// SetGoalType sets the "goal_type" field.
func (_u *PRISMGoalUpdateOne) SetGoalType(v string) *PRISMGoalUpdateOne {
	_u.mutation.SetGoalType(v)
	return _u
}

// SetNillableGoalType sets the "goal_type" field if the given value is not nil.
func (_u *PRISMGoalUpdateOne) SetNillableGoalType(v *string) *PRISMGoalUpdateOne {
	if v != nil {
		_u.SetGoalType(*v)
	}
	return _u
}

// SetDocument sets the "document" field.
func (_u *PRISMGoalUpdateOne) SetDocument(v map[string]interface{}) *PRISMGoalUpdateOne {
	_u.mutation.SetDocument(v)
	return _u
}

// ClearDocument clears the value of the "document" field.
func (_u *PRISMGoalUpdateOne) ClearDocument() *PRISMGoalUpdateOne {
	_u.mutation.ClearDocument()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PRISMGoalUpdateOne) SetCreatedAt(v time.Time) *PRISMGoalUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PRISMGoalUpdateOne) SetNillableCreatedAt(v *time.Time) *PRISMGoalUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PRISMGoalUpdateOne) SetUpdatedAt(v time.Time) *PRISMGoalUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PRISMGoalUpdateOne) SetNillableUpdatedAt(v *time.Time) *PRISMGoalUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the PRISMGoalMutation object of the builder.
func (_u *PRISMGoalUpdateOne) Mutation() *PRISMGoalMutation {
	return _u.mutation
}

// Where appends a list predicates to the PRISMGoalUpdate builder.
func (_u *PRISMGoalUpdateOne) Where(ps ...predicate.PRISMGoal) *PRISMGoalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PRISMGoalUpdateOne) Select(field string, fields ...string) *PRISMGoalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PRISMGoal entity.
func (_u *PRISMGoalUpdateOne) Save(ctx context.Context) (*PRISMGoal, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PRISMGoalUpdateOne) SaveX(ctx context.Context) *PRISMGoal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PRISMGoalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PRISMGoalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PRISMGoalUpdateOne) sqlSave(ctx context.Context) (_node *PRISMGoal, err error) {
	_spec := sqlgraph.NewUpdateSpec(prismgoal.Table, prismgoal.Columns, sqlgraph.NewFieldSpec(prismgoal.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PRISMGoal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prismgoal.FieldID)
		for _, f := range fields {
			if !prismgoal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != prismgoal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(prismgoal.FieldOrganization, field.TypeString, value)
	}
	if _u.mutation.OrganizationCleared() {
		_spec.ClearField(prismgoal.FieldOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.RepositoryID(); ok {
		_spec.SetField(prismgoal.FieldRepositoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoalType(); ok {
		_spec.SetField(prismgoal.FieldGoalType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Document(); ok {
		_spec.SetField(prismgoal.FieldDocument, field.TypeJSON, value)
	}
	if _u.mutation.DocumentCleared() {
		_spec.ClearField(prismgoal.FieldDocument, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(prismgoal.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prismgoal.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PRISMGoal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prismgoal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
