// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ProductBuildersHQ/visionstudio/ent/repositorydependency"
)

// RepositoryDependency is the model entity for the RepositoryDependency schema.
type RepositoryDependency struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SourceRepositoryID holds the value of the "source_repository_id" field.
	SourceRepositoryID string `json:"source_repository_id,omitempty"`
	// TargetRepositoryID holds the value of the "target_repository_id" field.
	TargetRepositoryID string `json:"target_repository_id,omitempty"`
	// DependencyType holds the value of the "dependency_type" field.
	DependencyType string `json:"dependency_type,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RepositoryDependency) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case repositorydependency.FieldID:
			values[i] = new(sql.NullInt64)
		case repositorydependency.FieldSourceRepositoryID, repositorydependency.FieldTargetRepositoryID, repositorydependency.FieldDependencyType:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RepositoryDependency fields.
func (_m *RepositoryDependency) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case repositorydependency.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case repositorydependency.FieldSourceRepositoryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_repository_id", values[i])
			} else if value.Valid {
				_m.SourceRepositoryID = value.String
			}
		case repositorydependency.FieldTargetRepositoryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_repository_id", values[i])
			} else if value.Valid {
				_m.TargetRepositoryID = value.String
			}
		case repositorydependency.FieldDependencyType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dependency_type", values[i])
			} else if value.Valid {
				_m.DependencyType = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RepositoryDependency.
// This includes values selected through modifiers, order, etc.
func (_m *RepositoryDependency) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RepositoryDependency.
// Note that you need to call RepositoryDependency.Unwrap() before calling this method if this RepositoryDependency
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RepositoryDependency) Update() *RepositoryDependencyUpdateOne {
	return NewRepositoryDependencyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RepositoryDependency entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RepositoryDependency) Unwrap() *RepositoryDependency {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RepositoryDependency is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RepositoryDependency) String() string {
	var builder strings.Builder
	builder.WriteString("RepositoryDependency(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source_repository_id=")
	builder.WriteString(_m.SourceRepositoryID)
	builder.WriteString(", ")
	builder.WriteString("target_repository_id=")
	builder.WriteString(_m.TargetRepositoryID)
	builder.WriteString(", ")
	builder.WriteString("dependency_type=")
	builder.WriteString(_m.DependencyType)
	builder.WriteByte(')')
	return builder.String()
}

// RepositoryDependencies is a parsable slice of RepositoryDependency.
type RepositoryDependencies []*RepositoryDependency
