// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
	"github.com/ProductBuildersHQ/visionstudio/ent/specworkflow"
)

// SpecWorkflowDelete is the builder for deleting a SpecWorkflow entity.
type SpecWorkflowDelete struct {
	config
	hooks    []Hook
	mutation *SpecWorkflowMutation
}

// Where appends a list predicates to the SpecWorkflowDelete builder.
func (_d *SpecWorkflowDelete) Where(ps ...predicate.SpecWorkflow) *SpecWorkflowDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SpecWorkflowDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SpecWorkflowDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SpecWorkflowDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(specworkflow.Table, sqlgraph.NewFieldSpec(specworkflow.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SpecWorkflowDeleteOne is the builder for deleting a single SpecWorkflow entity.
type SpecWorkflowDeleteOne struct {
	_d *SpecWorkflowDelete
}

// Where appends a list predicates to the SpecWorkflowDelete builder.
func (_d *SpecWorkflowDeleteOne) Where(ps ...predicate.SpecWorkflow) *SpecWorkflowDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SpecWorkflowDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{specworkflow.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SpecWorkflowDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
