// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/ProductBuildersHQ/visionstudio/ent/initiative"
	"github.com/ProductBuildersHQ/visionstudio/ent/judgerubric"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
	"github.com/ProductBuildersHQ/visionstudio/ent/specworkflow"
)

// SpecWorkflowUpdate is the builder for updating SpecWorkflow entities.
type SpecWorkflowUpdate struct {
	config
	hooks    []Hook
	mutation *SpecWorkflowMutation
}

// Where appends a list predicates to the SpecWorkflowUpdate builder.
func (_u *SpecWorkflowUpdate) Where(ps ...predicate.SpecWorkflow) *SpecWorkflowUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SpecWorkflowUpdate) SetName(v string) *SpecWorkflowUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SpecWorkflowUpdate) SetNillableName(v *string) *SpecWorkflowUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SpecWorkflowUpdate) SetDescription(v string) *SpecWorkflowUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SpecWorkflowUpdate) SetNillableDescription(v *string) *SpecWorkflowUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SpecWorkflowUpdate) ClearDescription() *SpecWorkflowUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetSpecsRequired sets the "specs_required" field.
func (_u *SpecWorkflowUpdate) SetSpecsRequired(v []string) *SpecWorkflowUpdate {
	_u.mutation.SetSpecsRequired(v)
	return _u
}

// AppendSpecsRequired appends value to the "specs_required" field.
func (_u *SpecWorkflowUpdate) AppendSpecsRequired(v []string) *SpecWorkflowUpdate {
	_u.mutation.AppendSpecsRequired(v)
	return _u
}

// ClearSpecsRequired clears the value of the "specs_required" field.
func (_u *SpecWorkflowUpdate) ClearSpecsRequired() *SpecWorkflowUpdate {
	_u.mutation.ClearSpecsRequired()
	return _u
}

// SetSpecsOptional sets the "specs_optional" field.
func (_u *SpecWorkflowUpdate) SetSpecsOptional(v []string) *SpecWorkflowUpdate {
	_u.mutation.SetSpecsOptional(v)
	return _u
}

// AppendSpecsOptional appends value to the "specs_optional" field.
func (_u *SpecWorkflowUpdate) AppendSpecsOptional(v []string) *SpecWorkflowUpdate {
	_u.mutation.AppendSpecsOptional(v)
	return _u
}

// ClearSpecsOptional clears the value of the "specs_optional" field.
func (_u *SpecWorkflowUpdate) ClearSpecsOptional() *SpecWorkflowUpdate {
	_u.mutation.ClearSpecsOptional()
	return _u
}

// SetInitTypes sets the "init_types" field.
func (_u *SpecWorkflowUpdate) SetInitTypes(v []string) *SpecWorkflowUpdate {
	_u.mutation.SetInitTypes(v)
	return _u
}

// AppendInitTypes appends value to the "init_types" field.
func (_u *SpecWorkflowUpdate) AppendInitTypes(v []string) *SpecWorkflowUpdate {
	_u.mutation.AppendInitTypes(v)
	return _u
}

// ClearInitTypes clears the value of the "init_types" field.
func (_u *SpecWorkflowUpdate) ClearInitTypes() *SpecWorkflowUpdate {
	_u.mutation.ClearInitTypes()
	return _u
}

// AddInitiativeIDs adds the "initiatives" edge to the Initiative entity by IDs.
func (_u *SpecWorkflowUpdate) AddInitiativeIDs(ids ...string) *SpecWorkflowUpdate {
	_u.mutation.AddInitiativeIDs(ids...)
	return _u
}

// AddInitiatives adds the "initiatives" edges to the Initiative entity.
func (_u *SpecWorkflowUpdate) AddInitiatives(v ...*Initiative) *SpecWorkflowUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInitiativeIDs(ids...)
}

// AddRubricIDs adds the "rubrics" edge to the JudgeRubric entity by IDs.
func (_u *SpecWorkflowUpdate) AddRubricIDs(ids ...string) *SpecWorkflowUpdate {
	_u.mutation.AddRubricIDs(ids...)
	return _u
}

// AddRubrics adds the "rubrics" edges to the JudgeRubric entity.
func (_u *SpecWorkflowUpdate) AddRubrics(v ...*JudgeRubric) *SpecWorkflowUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRubricIDs(ids...)
}

// Mutation returns the SpecWorkflowMutation object of the builder.
func (_u *SpecWorkflowUpdate) Mutation() *SpecWorkflowMutation {
	return _u.mutation
}

// ClearInitiatives clears all "initiatives" edges to the Initiative entity.
func (_u *SpecWorkflowUpdate) ClearInitiatives() *SpecWorkflowUpdate {
	_u.mutation.ClearInitiatives()
	return _u
}

// RemoveInitiativeIDs removes the "initiatives" edge to Initiative entities by IDs.
func (_u *SpecWorkflowUpdate) RemoveInitiativeIDs(ids ...string) *SpecWorkflowUpdate {
	_u.mutation.RemoveInitiativeIDs(ids...)
	return _u
}

// RemoveInitiatives removes "initiatives" edges to Initiative entities.
func (_u *SpecWorkflowUpdate) RemoveInitiatives(v ...*Initiative) *SpecWorkflowUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInitiativeIDs(ids...)
}

// ClearRubrics clears all "rubrics" edges to the JudgeRubric entity.
func (_u *SpecWorkflowUpdate) ClearRubrics() *SpecWorkflowUpdate {
	_u.mutation.ClearRubrics()
	return _u
}

// RemoveRubricIDs removes the "rubrics" edge to JudgeRubric entities by IDs.
func (_u *SpecWorkflowUpdate) RemoveRubricIDs(ids ...string) *SpecWorkflowUpdate {
	_u.mutation.RemoveRubricIDs(ids...)
	return _u
}

// RemoveRubrics removes "rubrics" edges to JudgeRubric entities.
func (_u *SpecWorkflowUpdate) RemoveRubrics(v ...*JudgeRubric) *SpecWorkflowUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRubricIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SpecWorkflowUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SpecWorkflowUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SpecWorkflowUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SpecWorkflowUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SpecWorkflowUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := specworkflow.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SpecWorkflow.name": %w`, err)}
		}
	}
	return nil
}

func (_u *SpecWorkflowUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(specworkflow.Table, specworkflow.Columns, sqlgraph.NewFieldSpec(specworkflow.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(specworkflow.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(specworkflow.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(specworkflow.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SpecsRequired(); ok {
		_spec.SetField(specworkflow.FieldSpecsRequired, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecsRequired(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, specworkflow.FieldSpecsRequired, value)
		})
	}
	if _u.mutation.SpecsRequiredCleared() {
		_spec.ClearField(specworkflow.FieldSpecsRequired, field.TypeJSON)
	}
	if value, ok := _u.mutation.SpecsOptional(); ok {
		_spec.SetField(specworkflow.FieldSpecsOptional, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecsOptional(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, specworkflow.FieldSpecsOptional, value)
		})
	}
	if _u.mutation.SpecsOptionalCleared() {
		_spec.ClearField(specworkflow.FieldSpecsOptional, field.TypeJSON)
	}
	if value, ok := _u.mutation.InitTypes(); ok {
		_spec.SetField(specworkflow.FieldInitTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedInitTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, specworkflow.FieldInitTypes, value)
		})
	}
	if _u.mutation.InitTypesCleared() {
		_spec.ClearField(specworkflow.FieldInitTypes, field.TypeJSON)
	}
	if _u.mutation.InitiativesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specworkflow.InitiativesTable,
			Columns: []string{specworkflow.InitiativesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(initiative.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInitiativesIDs(); len(nodes) > 0 && !_u.mutation.InitiativesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specworkflow.InitiativesTable,
			Columns: []string{specworkflow.InitiativesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(initiative.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InitiativesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specworkflow.InitiativesTable,
			Columns: []string{specworkflow.InitiativesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(initiative.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RubricsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specworkflow.RubricsTable,
			Columns: []string{specworkflow.RubricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(judgerubric.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRubricsIDs(); len(nodes) > 0 && !_u.mutation.RubricsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specworkflow.RubricsTable,
			Columns: []string{specworkflow.RubricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(judgerubric.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RubricsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specworkflow.RubricsTable,
			Columns: []string{specworkflow.RubricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(judgerubric.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{specworkflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SpecWorkflowUpdateOne is the builder for updating a single SpecWorkflow entity.
type SpecWorkflowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SpecWorkflowMutation
}

// SetName sets the "name" field.
func (_u *SpecWorkflowUpdateOne) SetName(v string) *SpecWorkflowUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SpecWorkflowUpdateOne) SetNillableName(v *string) *SpecWorkflowUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SpecWorkflowUpdateOne) SetDescription(v string) *SpecWorkflowUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SpecWorkflowUpdateOne) SetNillableDescription(v *string) *SpecWorkflowUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SpecWorkflowUpdateOne) ClearDescription() *SpecWorkflowUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetSpecsRequired sets the "specs_required" field.
func (_u *SpecWorkflowUpdateOne) SetSpecsRequired(v []string) *SpecWorkflowUpdateOne {
	_u.mutation.SetSpecsRequired(v)
	return _u
}

// AppendSpecsRequired appends value to the "specs_required" field.
func (_u *SpecWorkflowUpdateOne) AppendSpecsRequired(v []string) *SpecWorkflowUpdateOne {
	_u.mutation.AppendSpecsRequired(v)
	return _u
}

// ClearSpecsRequired clears the value of the "specs_required" field.
func (_u *SpecWorkflowUpdateOne) ClearSpecsRequired() *SpecWorkflowUpdateOne {
	_u.mutation.ClearSpecsRequired()
	return _u
}

// SetSpecsOptional sets the "specs_optional" field.
func (_u *SpecWorkflowUpdateOne) SetSpecsOptional(v []string) *SpecWorkflowUpdateOne {
	_u.mutation.SetSpecsOptional(v)
	return _u
}

// AppendSpecsOptional appends value to the "specs_optional" field.
func (_u *SpecWorkflowUpdateOne) AppendSpecsOptional(v []string) *SpecWorkflowUpdateOne {
	_u.mutation.AppendSpecsOptional(v)
	return _u
}

// ClearSpecsOptional clears the value of the "specs_optional" field.
func (_u *SpecWorkflowUpdateOne) ClearSpecsOptional() *SpecWorkflowUpdateOne {
	_u.mutation.ClearSpecsOptional()
	return _u
}

// SetInitTypes sets the "init_types" field.
func (_u *SpecWorkflowUpdateOne) SetInitTypes(v []string) *SpecWorkflowUpdateOne {
	_u.mutation.SetInitTypes(v)
	return _u
}

// AppendInitTypes appends value to the "init_types" field.
func (_u *SpecWorkflowUpdateOne) AppendInitTypes(v []string) *SpecWorkflowUpdateOne {
	_u.mutation.AppendInitTypes(v)
	return _u
}

// ClearInitTypes clears the value of the "init_types" field.
func (_u *SpecWorkflowUpdateOne) ClearInitTypes() *SpecWorkflowUpdateOne {
	_u.mutation.ClearInitTypes()
	return _u
}

// AddInitiativeIDs adds the "initiatives" edge to the Initiative entity by IDs.
func (_u *SpecWorkflowUpdateOne) AddInitiativeIDs(ids ...string) *SpecWorkflowUpdateOne {
	_u.mutation.AddInitiativeIDs(ids...)
	return _u
}

// AddInitiatives adds the "initiatives" edges to the Initiative entity.
func (_u *SpecWorkflowUpdateOne) AddInitiatives(v ...*Initiative) *SpecWorkflowUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInitiativeIDs(ids...)
}

// AddRubricIDs adds the "rubrics" edge to the JudgeRubric entity by IDs.
func (_u *SpecWorkflowUpdateOne) AddRubricIDs(ids ...string) *SpecWorkflowUpdateOne {
	_u.mutation.AddRubricIDs(ids...)
	return _u
}

// AddRubrics adds the "rubrics" edges to the JudgeRubric entity.
func (_u *SpecWorkflowUpdateOne) AddRubrics(v ...*JudgeRubric) *SpecWorkflowUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRubricIDs(ids...)
}

// Mutation returns the SpecWorkflowMutation object of the builder.
func (_u *SpecWorkflowUpdateOne) Mutation() *SpecWorkflowMutation {
	return _u.mutation
}

// ClearInitiatives clears all "initiatives" edges to the Initiative entity.
func (_u *SpecWorkflowUpdateOne) ClearInitiatives() *SpecWorkflowUpdateOne {
	_u.mutation.ClearInitiatives()
	return _u
}

// RemoveInitiativeIDs removes the "initiatives" edge to Initiative entities by IDs.
func (_u *SpecWorkflowUpdateOne) RemoveInitiativeIDs(ids ...string) *SpecWorkflowUpdateOne {
	_u.mutation.RemoveInitiativeIDs(ids...)
	return _u
}

// RemoveInitiatives removes "initiatives" edges to Initiative entities.
func (_u *SpecWorkflowUpdateOne) RemoveInitiatives(v ...*Initiative) *SpecWorkflowUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInitiativeIDs(ids...)
}

// ClearRubrics clears all "rubrics" edges to the JudgeRubric entity.
func (_u *SpecWorkflowUpdateOne) ClearRubrics() *SpecWorkflowUpdateOne {
	_u.mutation.ClearRubrics()
	return _u
}

// RemoveRubricIDs removes the "rubrics" edge to JudgeRubric entities by IDs.
func (_u *SpecWorkflowUpdateOne) RemoveRubricIDs(ids ...string) *SpecWorkflowUpdateOne {
	_u.mutation.RemoveRubricIDs(ids...)
	return _u
}

// RemoveRubrics removes "rubrics" edges to JudgeRubric entities.
func (_u *SpecWorkflowUpdateOne) RemoveRubrics(v ...*JudgeRubric) *SpecWorkflowUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRubricIDs(ids...)
}

// Where appends a list predicates to the SpecWorkflowUpdate builder.
func (_u *SpecWorkflowUpdateOne) Where(ps ...predicate.SpecWorkflow) *SpecWorkflowUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SpecWorkflowUpdateOne) Select(field string, fields ...string) *SpecWorkflowUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SpecWorkflow entity.
func (_u *SpecWorkflowUpdateOne) Save(ctx context.Context) (*SpecWorkflow, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SpecWorkflowUpdateOne) SaveX(ctx context.Context) *SpecWorkflow {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SpecWorkflowUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SpecWorkflowUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SpecWorkflowUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := specworkflow.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SpecWorkflow.name": %w`, err)}
		}
	}
	return nil
}

func (_u *SpecWorkflowUpdateOne) sqlSave(ctx context.Context) (_node *SpecWorkflow, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(specworkflow.Table, specworkflow.Columns, sqlgraph.NewFieldSpec(specworkflow.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SpecWorkflow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, specworkflow.FieldID)
		for _, f := range fields {
			if !specworkflow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != specworkflow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(specworkflow.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(specworkflow.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(specworkflow.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SpecsRequired(); ok {
		_spec.SetField(specworkflow.FieldSpecsRequired, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecsRequired(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, specworkflow.FieldSpecsRequired, value)
		})
	}
	if _u.mutation.SpecsRequiredCleared() {
		_spec.ClearField(specworkflow.FieldSpecsRequired, field.TypeJSON)
	}
	if value, ok := _u.mutation.SpecsOptional(); ok {
		_spec.SetField(specworkflow.FieldSpecsOptional, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecsOptional(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, specworkflow.FieldSpecsOptional, value)
		})
	}
	if _u.mutation.SpecsOptionalCleared() {
		_spec.ClearField(specworkflow.FieldSpecsOptional, field.TypeJSON)
	}
	if value, ok := _u.mutation.InitTypes(); ok {
		_spec.SetField(specworkflow.FieldInitTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedInitTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, specworkflow.FieldInitTypes, value)
		})
	}
	if _u.mutation.InitTypesCleared() {
		_spec.ClearField(specworkflow.FieldInitTypes, field.TypeJSON)
	}
	if _u.mutation.InitiativesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specworkflow.InitiativesTable,
			Columns: []string{specworkflow.InitiativesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(initiative.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInitiativesIDs(); len(nodes) > 0 && !_u.mutation.InitiativesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specworkflow.InitiativesTable,
			Columns: []string{specworkflow.InitiativesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(initiative.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InitiativesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specworkflow.InitiativesTable,
			Columns: []string{specworkflow.InitiativesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(initiative.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RubricsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specworkflow.RubricsTable,
			Columns: []string{specworkflow.RubricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(judgerubric.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRubricsIDs(); len(nodes) > 0 && !_u.mutation.RubricsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specworkflow.RubricsTable,
			Columns: []string{specworkflow.RubricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(judgerubric.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RubricsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specworkflow.RubricsTable,
			Columns: []string{specworkflow.RubricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(judgerubric.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SpecWorkflow{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{specworkflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
