// Code generated by ent, DO NOT EDIT.

package judgerubric

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the judgerubric type in the database.
	Label = "judge_rubric"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "rubric_id"
	// FieldSpecType holds the string denoting the spec_type field in the database.
	FieldSpecType = "spec_type"
	// FieldCriteria holds the string denoting the criteria field in the database.
	FieldCriteria = "criteria"
	// FieldPromptTemplate holds the string denoting the prompt_template field in the database.
	FieldPromptTemplate = "prompt_template"
	// EdgeWorkflow holds the string denoting the workflow edge name in mutations.
	EdgeWorkflow = "workflow"
	// EdgeResults holds the string denoting the results edge name in mutations.
	EdgeResults = "results"
	// SpecWorkflowFieldID holds the string denoting the ID field of the SpecWorkflow.
	SpecWorkflowFieldID = "workflow_id"
	// JudgeResultFieldID holds the string denoting the ID field of the JudgeResult.
	JudgeResultFieldID = "result_id"
	// Table holds the table name of the judgerubric in the database.
	Table = "judge_rubrics"
	// WorkflowTable is the table that holds the workflow relation/edge.
	WorkflowTable = "judge_rubrics"
	// WorkflowInverseTable is the table name for the SpecWorkflow entity.
	// It exists in this package in order to avoid circular dependency with the "specworkflow" package.
	WorkflowInverseTable = "spec_workflows"
	// WorkflowColumn is the table column denoting the workflow relation/edge.
	WorkflowColumn = "spec_workflow_rubrics"
	// ResultsTable is the table that holds the results relation/edge.
	ResultsTable = "judge_results"
	// ResultsInverseTable is the table name for the JudgeResult entity.
	// It exists in this package in order to avoid circular dependency with the "judgeresult" package.
	ResultsInverseTable = "judge_results"
	// ResultsColumn is the table column denoting the results relation/edge.
	ResultsColumn = "judge_rubric_results"
)

// Columns holds all SQL columns for judgerubric fields.
var Columns = []string{
	FieldID,
	FieldSpecType,
	FieldCriteria,
	FieldPromptTemplate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "judge_rubrics"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"spec_workflow_rubrics",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// SpecTypeValidator is a validator for the "spec_type" field. It is called by the builders before save.
	SpecTypeValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the JudgeRubric queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySpecType orders the results by the spec_type field.
func BySpecType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpecType, opts...).ToFunc()
}

// ByPromptTemplate orders the results by the prompt_template field.
func ByPromptTemplate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptTemplate, opts...).ToFunc()
}

// ByWorkflowField orders the results by workflow field.
func ByWorkflowField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWorkflowStep(), sql.OrderByField(field, opts...))
	}
}

// ByResultsCount orders the results by results count.
func ByResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newResultsStep(), opts...)
	}
}

// ByResults orders the results by results terms.
func ByResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newWorkflowStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WorkflowInverseTable, SpecWorkflowFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WorkflowTable, WorkflowColumn),
	)
}
func newResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResultsInverseTable, JudgeResultFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ResultsTable, ResultsColumn),
	)
}
