// Code generated by ent, DO NOT EDIT.

package judgerubric

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldContainsFold(FieldID, id))
}

// SpecType applies equality check predicate on the "spec_type" field. It's identical to SpecTypeEQ.
func SpecType(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldEQ(FieldSpecType, v))
}

// PromptTemplate applies equality check predicate on the "prompt_template" field. It's identical to PromptTemplateEQ.
func PromptTemplate(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldEQ(FieldPromptTemplate, v))
}

// SpecTypeEQ applies the EQ predicate on the "spec_type" field.
func SpecTypeEQ(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldEQ(FieldSpecType, v))
}

// SpecTypeNEQ applies the NEQ predicate on the "spec_type" field.
func SpecTypeNEQ(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldNEQ(FieldSpecType, v))
}

// SpecTypeIn applies the In predicate on the "spec_type" field.
func SpecTypeIn(vs ...string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldIn(FieldSpecType, vs...))
}

// SpecTypeNotIn applies the NotIn predicate on the "spec_type" field.
func SpecTypeNotIn(vs ...string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldNotIn(FieldSpecType, vs...))
}

// SpecTypeGT applies the GT predicate on the "spec_type" field.
func SpecTypeGT(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldGT(FieldSpecType, v))
}

// SpecTypeGTE applies the GTE predicate on the "spec_type" field.
func SpecTypeGTE(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldGTE(FieldSpecType, v))
}

// SpecTypeLT applies the LT predicate on the "spec_type" field.
func SpecTypeLT(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldLT(FieldSpecType, v))
}

// SpecTypeLTE applies the LTE predicate on the "spec_type" field.
func SpecTypeLTE(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldLTE(FieldSpecType, v))
}

// SpecTypeContains applies the Contains predicate on the "spec_type" field.
func SpecTypeContains(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldContains(FieldSpecType, v))
}

// SpecTypeHasPrefix applies the HasPrefix predicate on the "spec_type" field.
func SpecTypeHasPrefix(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldHasPrefix(FieldSpecType, v))
}

// SpecTypeHasSuffix applies the HasSuffix predicate on the "spec_type" field.
func SpecTypeHasSuffix(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldHasSuffix(FieldSpecType, v))
}

// SpecTypeEqualFold applies the EqualFold predicate on the "spec_type" field.
func SpecTypeEqualFold(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldEqualFold(FieldSpecType, v))
}

// SpecTypeContainsFold applies the ContainsFold predicate on the "spec_type" field.
func SpecTypeContainsFold(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldContainsFold(FieldSpecType, v))
}

// CriteriaIsNil applies the IsNil predicate on the "criteria" field.
func CriteriaIsNil() predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldIsNull(FieldCriteria))
}

// CriteriaNotNil applies the NotNil predicate on the "criteria" field.
func CriteriaNotNil() predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldNotNull(FieldCriteria))
}

// PromptTemplateEQ applies the EQ predicate on the "prompt_template" field.
func PromptTemplateEQ(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldEQ(FieldPromptTemplate, v))
}

// PromptTemplateNEQ applies the NEQ predicate on the "prompt_template" field.
func PromptTemplateNEQ(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldNEQ(FieldPromptTemplate, v))
}

// PromptTemplateIn applies the In predicate on the "prompt_template" field.
func PromptTemplateIn(vs ...string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldIn(FieldPromptTemplate, vs...))
}

// PromptTemplateNotIn applies the NotIn predicate on the "prompt_template" field.
func PromptTemplateNotIn(vs ...string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldNotIn(FieldPromptTemplate, vs...))
}

// PromptTemplateGT applies the GT predicate on the "prompt_template" field.
func PromptTemplateGT(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldGT(FieldPromptTemplate, v))
}

// PromptTemplateGTE applies the GTE predicate on the "prompt_template" field.
func PromptTemplateGTE(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldGTE(FieldPromptTemplate, v))
}

// PromptTemplateLT applies the LT predicate on the "prompt_template" field.
func PromptTemplateLT(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldLT(FieldPromptTemplate, v))
}

// PromptTemplateLTE applies the LTE predicate on the "prompt_template" field.
func PromptTemplateLTE(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldLTE(FieldPromptTemplate, v))
}

// PromptTemplateContains applies the Contains predicate on the "prompt_template" field.
func PromptTemplateContains(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldContains(FieldPromptTemplate, v))
}

// PromptTemplateHasPrefix applies the HasPrefix predicate on the "prompt_template" field.
func PromptTemplateHasPrefix(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldHasPrefix(FieldPromptTemplate, v))
}

// PromptTemplateHasSuffix applies the HasSuffix predicate on the "prompt_template" field.
func PromptTemplateHasSuffix(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldHasSuffix(FieldPromptTemplate, v))
}

// PromptTemplateIsNil applies the IsNil predicate on the "prompt_template" field.
func PromptTemplateIsNil() predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldIsNull(FieldPromptTemplate))
}

// PromptTemplateNotNil applies the NotNil predicate on the "prompt_template" field.
func PromptTemplateNotNil() predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldNotNull(FieldPromptTemplate))
}

// PromptTemplateEqualFold applies the EqualFold predicate on the "prompt_template" field.
func PromptTemplateEqualFold(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldEqualFold(FieldPromptTemplate, v))
}

// PromptTemplateContainsFold applies the ContainsFold predicate on the "prompt_template" field.
func PromptTemplateContainsFold(v string) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.FieldContainsFold(FieldPromptTemplate, v))
}

// HasWorkflow applies the HasEdge predicate on the "workflow" edge.
func HasWorkflow() predicate.JudgeRubric {
	return predicate.JudgeRubric(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkflowTable, WorkflowColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkflowWith applies the HasEdge predicate on the "workflow" edge with a given conditions (other predicates).
func HasWorkflowWith(preds ...predicate.SpecWorkflow) predicate.JudgeRubric {
	return predicate.JudgeRubric(func(s *sql.Selector) {
		step := newWorkflowStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResults applies the HasEdge predicate on the "results" edge.
func HasResults() predicate.JudgeRubric {
	return predicate.JudgeRubric(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResultsTable, ResultsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResultsWith applies the HasEdge predicate on the "results" edge with a given conditions (other predicates).
func HasResultsWith(preds ...predicate.JudgeResult) predicate.JudgeRubric {
	return predicate.JudgeRubric(func(s *sql.Selector) {
		step := newResultsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.JudgeRubric) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.JudgeRubric) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.JudgeRubric) predicate.JudgeRubric {
	return predicate.JudgeRubric(sql.NotPredicates(p))
}
