// Code generated by ent, DO NOT EDIT.

package judgeresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldContainsFold(FieldID, id))
}

// InitiativeID applies equality check predicate on the "initiative_id" field. It's identical to InitiativeIDEQ.
func InitiativeID(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldInitiativeID, v))
}

// SpecPath applies equality check predicate on the "spec_path" field. It's identical to SpecPathEQ.
func SpecPath(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldSpecPath, v))
}

// SpecType applies equality check predicate on the "spec_type" field. It's identical to SpecTypeEQ.
func SpecType(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldSpecType, v))
}

// EvaluatedAt applies equality check predicate on the "evaluated_at" field. It's identical to EvaluatedAtEQ.
func EvaluatedAt(v time.Time) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldEvaluatedAt, v))
}

// IntScore applies equality check predicate on the "int_score" field. It's identical to IntScoreEQ.
func IntScore(v int) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldIntScore, v))
}

// Pass applies equality check predicate on the "pass" field. It's identical to PassEQ.
func Pass(v bool) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldPass, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldModel, v))
}

// RubricID applies equality check predicate on the "rubric_id" field. It's identical to RubricIDEQ.
func RubricID(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldRubricID, v))
}

// InitiativeIDEQ applies the EQ predicate on the "initiative_id" field.
func InitiativeIDEQ(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldInitiativeID, v))
}

// InitiativeIDNEQ applies the NEQ predicate on the "initiative_id" field.
func InitiativeIDNEQ(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNEQ(FieldInitiativeID, v))
}

// InitiativeIDIn applies the In predicate on the "initiative_id" field.
func InitiativeIDIn(vs ...string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldIn(FieldInitiativeID, vs...))
}

// InitiativeIDNotIn applies the NotIn predicate on the "initiative_id" field.
func InitiativeIDNotIn(vs ...string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNotIn(FieldInitiativeID, vs...))
}

// InitiativeIDGT applies the GT predicate on the "initiative_id" field.
func InitiativeIDGT(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGT(FieldInitiativeID, v))
}

// InitiativeIDGTE applies the GTE predicate on the "initiative_id" field.
func InitiativeIDGTE(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGTE(FieldInitiativeID, v))
}

// InitiativeIDLT applies the LT predicate on the "initiative_id" field.
func InitiativeIDLT(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLT(FieldInitiativeID, v))
}

// InitiativeIDLTE applies the LTE predicate on the "initiative_id" field.
func InitiativeIDLTE(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLTE(FieldInitiativeID, v))
}

// InitiativeIDContains applies the Contains predicate on the "initiative_id" field.
func InitiativeIDContains(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldContains(FieldInitiativeID, v))
}

// InitiativeIDHasPrefix applies the HasPrefix predicate on the "initiative_id" field.
func InitiativeIDHasPrefix(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldHasPrefix(FieldInitiativeID, v))
}

// InitiativeIDHasSuffix applies the HasSuffix predicate on the "initiative_id" field.
func InitiativeIDHasSuffix(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldHasSuffix(FieldInitiativeID, v))
}

// InitiativeIDEqualFold applies the EqualFold predicate on the "initiative_id" field.
func InitiativeIDEqualFold(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEqualFold(FieldInitiativeID, v))
}

// InitiativeIDContainsFold applies the ContainsFold predicate on the "initiative_id" field.
func InitiativeIDContainsFold(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldContainsFold(FieldInitiativeID, v))
}

// SpecPathEQ applies the EQ predicate on the "spec_path" field.
func SpecPathEQ(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldSpecPath, v))
}

// SpecPathNEQ applies the NEQ predicate on the "spec_path" field.
func SpecPathNEQ(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNEQ(FieldSpecPath, v))
}

// SpecPathIn applies the In predicate on the "spec_path" field.
func SpecPathIn(vs ...string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldIn(FieldSpecPath, vs...))
}

// SpecPathNotIn applies the NotIn predicate on the "spec_path" field.
func SpecPathNotIn(vs ...string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNotIn(FieldSpecPath, vs...))
}

// SpecPathGT applies the GT predicate on the "spec_path" field.
func SpecPathGT(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGT(FieldSpecPath, v))
}

// SpecPathGTE applies the GTE predicate on the "spec_path" field.
func SpecPathGTE(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGTE(FieldSpecPath, v))
}

// SpecPathLT applies the LT predicate on the "spec_path" field.
func SpecPathLT(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLT(FieldSpecPath, v))
}

// SpecPathLTE applies the LTE predicate on the "spec_path" field.
func SpecPathLTE(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLTE(FieldSpecPath, v))
}

// SpecPathContains applies the Contains predicate on the "spec_path" field.
func SpecPathContains(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldContains(FieldSpecPath, v))
}

// SpecPathHasPrefix applies the HasPrefix predicate on the "spec_path" field.
func SpecPathHasPrefix(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldHasPrefix(FieldSpecPath, v))
}

// SpecPathHasSuffix applies the HasSuffix predicate on the "spec_path" field.
func SpecPathHasSuffix(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldHasSuffix(FieldSpecPath, v))
}

// SpecPathEqualFold applies the EqualFold predicate on the "spec_path" field.
func SpecPathEqualFold(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEqualFold(FieldSpecPath, v))
}

// SpecPathContainsFold applies the ContainsFold predicate on the "spec_path" field.
func SpecPathContainsFold(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldContainsFold(FieldSpecPath, v))
}

// SpecTypeEQ applies the EQ predicate on the "spec_type" field.
func SpecTypeEQ(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldSpecType, v))
}

// SpecTypeNEQ applies the NEQ predicate on the "spec_type" field.
func SpecTypeNEQ(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNEQ(FieldSpecType, v))
}

// SpecTypeIn applies the In predicate on the "spec_type" field.
func SpecTypeIn(vs ...string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldIn(FieldSpecType, vs...))
}

// SpecTypeNotIn applies the NotIn predicate on the "spec_type" field.
func SpecTypeNotIn(vs ...string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNotIn(FieldSpecType, vs...))
}

// SpecTypeGT applies the GT predicate on the "spec_type" field.
func SpecTypeGT(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGT(FieldSpecType, v))
}

// SpecTypeGTE applies the GTE predicate on the "spec_type" field.
func SpecTypeGTE(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGTE(FieldSpecType, v))
}

// SpecTypeLT applies the LT predicate on the "spec_type" field.
func SpecTypeLT(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLT(FieldSpecType, v))
}

// SpecTypeLTE applies the LTE predicate on the "spec_type" field.
func SpecTypeLTE(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLTE(FieldSpecType, v))
}

// SpecTypeContains applies the Contains predicate on the "spec_type" field.
func SpecTypeContains(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldContains(FieldSpecType, v))
}

// SpecTypeHasPrefix applies the HasPrefix predicate on the "spec_type" field.
func SpecTypeHasPrefix(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldHasPrefix(FieldSpecType, v))
}

// SpecTypeHasSuffix applies the HasSuffix predicate on the "spec_type" field.
func SpecTypeHasSuffix(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldHasSuffix(FieldSpecType, v))
}

// SpecTypeIsNil applies the IsNil predicate on the "spec_type" field.
func SpecTypeIsNil() predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldIsNull(FieldSpecType))
}

// SpecTypeNotNil applies the NotNil predicate on the "spec_type" field.
func SpecTypeNotNil() predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNotNull(FieldSpecType))
}

// SpecTypeEqualFold applies the EqualFold predicate on the "spec_type" field.
func SpecTypeEqualFold(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEqualFold(FieldSpecType, v))
}

// SpecTypeContainsFold applies the ContainsFold predicate on the "spec_type" field.
func SpecTypeContainsFold(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldContainsFold(FieldSpecType, v))
}

// EvaluatedAtEQ applies the EQ predicate on the "evaluated_at" field.
func EvaluatedAtEQ(v time.Time) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldEvaluatedAt, v))
}

// EvaluatedAtNEQ applies the NEQ predicate on the "evaluated_at" field.
func EvaluatedAtNEQ(v time.Time) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNEQ(FieldEvaluatedAt, v))
}

// EvaluatedAtIn applies the In predicate on the "evaluated_at" field.
func EvaluatedAtIn(vs ...time.Time) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldIn(FieldEvaluatedAt, vs...))
}

// EvaluatedAtNotIn applies the NotIn predicate on the "evaluated_at" field.
func EvaluatedAtNotIn(vs ...time.Time) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNotIn(FieldEvaluatedAt, vs...))
}

// EvaluatedAtGT applies the GT predicate on the "evaluated_at" field.
func EvaluatedAtGT(v time.Time) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGT(FieldEvaluatedAt, v))
}

// EvaluatedAtGTE applies the GTE predicate on the "evaluated_at" field.
func EvaluatedAtGTE(v time.Time) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGTE(FieldEvaluatedAt, v))
}

// EvaluatedAtLT applies the LT predicate on the "evaluated_at" field.
func EvaluatedAtLT(v time.Time) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLT(FieldEvaluatedAt, v))
}

// EvaluatedAtLTE applies the LTE predicate on the "evaluated_at" field.
func EvaluatedAtLTE(v time.Time) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLTE(FieldEvaluatedAt, v))
}

// ReportIsNil applies the IsNil predicate on the "report" field.
func ReportIsNil() predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldIsNull(FieldReport))
}

// ReportNotNil applies the NotNil predicate on the "report" field.
func ReportNotNil() predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNotNull(FieldReport))
}

// IntScoreEQ applies the EQ predicate on the "int_score" field.
func IntScoreEQ(v int) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldIntScore, v))
}

// IntScoreNEQ applies the NEQ predicate on the "int_score" field.
func IntScoreNEQ(v int) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNEQ(FieldIntScore, v))
}

// IntScoreIn applies the In predicate on the "int_score" field.
func IntScoreIn(vs ...int) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldIn(FieldIntScore, vs...))
}

// IntScoreNotIn applies the NotIn predicate on the "int_score" field.
func IntScoreNotIn(vs ...int) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNotIn(FieldIntScore, vs...))
}

// IntScoreGT applies the GT predicate on the "int_score" field.
func IntScoreGT(v int) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGT(FieldIntScore, v))
}

// IntScoreGTE applies the GTE predicate on the "int_score" field.
func IntScoreGTE(v int) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGTE(FieldIntScore, v))
}

// IntScoreLT applies the LT predicate on the "int_score" field.
func IntScoreLT(v int) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLT(FieldIntScore, v))
}

// IntScoreLTE applies the LTE predicate on the "int_score" field.
func IntScoreLTE(v int) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLTE(FieldIntScore, v))
}

// IntScoreIsNil applies the IsNil predicate on the "int_score" field.
func IntScoreIsNil() predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldIsNull(FieldIntScore))
}

// IntScoreNotNil applies the NotNil predicate on the "int_score" field.
func IntScoreNotNil() predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNotNull(FieldIntScore))
}

// PassEQ applies the EQ predicate on the "pass" field.
func PassEQ(v bool) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldPass, v))
}

// PassNEQ applies the NEQ predicate on the "pass" field.
func PassNEQ(v bool) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNEQ(FieldPass, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldContainsFold(FieldModel, v))
}

// RubricIDEQ applies the EQ predicate on the "rubric_id" field.
func RubricIDEQ(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEQ(FieldRubricID, v))
}

// RubricIDNEQ applies the NEQ predicate on the "rubric_id" field.
func RubricIDNEQ(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNEQ(FieldRubricID, v))
}

// RubricIDIn applies the In predicate on the "rubric_id" field.
func RubricIDIn(vs ...string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldIn(FieldRubricID, vs...))
}

// RubricIDNotIn applies the NotIn predicate on the "rubric_id" field.
func RubricIDNotIn(vs ...string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNotIn(FieldRubricID, vs...))
}

// RubricIDGT applies the GT predicate on the "rubric_id" field.
func RubricIDGT(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGT(FieldRubricID, v))
}

// RubricIDGTE applies the GTE predicate on the "rubric_id" field.
func RubricIDGTE(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldGTE(FieldRubricID, v))
}

// RubricIDLT applies the LT predicate on the "rubric_id" field.
func RubricIDLT(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLT(FieldRubricID, v))
}

// RubricIDLTE applies the LTE predicate on the "rubric_id" field.
func RubricIDLTE(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldLTE(FieldRubricID, v))
}

// RubricIDContains applies the Contains predicate on the "rubric_id" field.
func RubricIDContains(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldContains(FieldRubricID, v))
}

// RubricIDHasPrefix applies the HasPrefix predicate on the "rubric_id" field.
func RubricIDHasPrefix(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldHasPrefix(FieldRubricID, v))
}

// RubricIDHasSuffix applies the HasSuffix predicate on the "rubric_id" field.
func RubricIDHasSuffix(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldHasSuffix(FieldRubricID, v))
}

// RubricIDIsNil applies the IsNil predicate on the "rubric_id" field.
func RubricIDIsNil() predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldIsNull(FieldRubricID))
}

// RubricIDNotNil applies the NotNil predicate on the "rubric_id" field.
func RubricIDNotNil() predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldNotNull(FieldRubricID))
}

// RubricIDEqualFold applies the EqualFold predicate on the "rubric_id" field.
func RubricIDEqualFold(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldEqualFold(FieldRubricID, v))
}

// RubricIDContainsFold applies the ContainsFold predicate on the "rubric_id" field.
func RubricIDContainsFold(v string) predicate.JudgeResult {
	return predicate.JudgeResult(sql.FieldContainsFold(FieldRubricID, v))
}

// HasInitiative applies the HasEdge predicate on the "initiative" edge.
func HasInitiative() predicate.JudgeResult {
	return predicate.JudgeResult(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InitiativeTable, InitiativeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInitiativeWith applies the HasEdge predicate on the "initiative" edge with a given conditions (other predicates).
func HasInitiativeWith(preds ...predicate.Initiative) predicate.JudgeResult {
	return predicate.JudgeResult(func(s *sql.Selector) {
		step := newInitiativeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.JudgeResult) predicate.JudgeResult {
	return predicate.JudgeResult(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.JudgeResult) predicate.JudgeResult {
	return predicate.JudgeResult(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.JudgeResult) predicate.JudgeResult {
	return predicate.JudgeResult(sql.NotPredicates(p))
}
