// Code generated by ent, DO NOT EDIT.

package deliveryevidence

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldContainsFold(FieldID, id))
}

// EvidenceType applies equality check predicate on the "evidence_type" field. It's identical to EvidenceTypeEQ.
func EvidenceType(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldEvidenceType, v))
}

// Reference applies equality check predicate on the "reference" field. It's identical to ReferenceEQ.
func Reference(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldReference, v))
}

// CommitType applies equality check predicate on the "commit_type" field. It's identical to CommitTypeEQ.
func CommitType(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldCommitType, v))
}

// CommitScope applies equality check predicate on the "commit_scope" field. It's identical to CommitScopeEQ.
func CommitScope(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldCommitScope, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldOccurredAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldCreatedAt, v))
}

// EvidenceTypeEQ applies the EQ predicate on the "evidence_type" field.
func EvidenceTypeEQ(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldEvidenceType, v))
}

// EvidenceTypeNEQ applies the NEQ predicate on the "evidence_type" field.
func EvidenceTypeNEQ(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNEQ(FieldEvidenceType, v))
}

// EvidenceTypeIn applies the In predicate on the "evidence_type" field.
func EvidenceTypeIn(vs ...string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldIn(FieldEvidenceType, vs...))
}

// EvidenceTypeNotIn applies the NotIn predicate on the "evidence_type" field.
func EvidenceTypeNotIn(vs ...string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNotIn(FieldEvidenceType, vs...))
}

// EvidenceTypeGT applies the GT predicate on the "evidence_type" field.
func EvidenceTypeGT(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGT(FieldEvidenceType, v))
}

// EvidenceTypeGTE applies the GTE predicate on the "evidence_type" field.
func EvidenceTypeGTE(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGTE(FieldEvidenceType, v))
}

// EvidenceTypeLT applies the LT predicate on the "evidence_type" field.
func EvidenceTypeLT(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLT(FieldEvidenceType, v))
}

// EvidenceTypeLTE applies the LTE predicate on the "evidence_type" field.
func EvidenceTypeLTE(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLTE(FieldEvidenceType, v))
}

// EvidenceTypeContains applies the Contains predicate on the "evidence_type" field.
func EvidenceTypeContains(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldContains(FieldEvidenceType, v))
}

// EvidenceTypeHasPrefix applies the HasPrefix predicate on the "evidence_type" field.
func EvidenceTypeHasPrefix(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldHasPrefix(FieldEvidenceType, v))
}

// EvidenceTypeHasSuffix applies the HasSuffix predicate on the "evidence_type" field.
func EvidenceTypeHasSuffix(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldHasSuffix(FieldEvidenceType, v))
}

// EvidenceTypeEqualFold applies the EqualFold predicate on the "evidence_type" field.
func EvidenceTypeEqualFold(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEqualFold(FieldEvidenceType, v))
}

// EvidenceTypeContainsFold applies the ContainsFold predicate on the "evidence_type" field.
func EvidenceTypeContainsFold(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldContainsFold(FieldEvidenceType, v))
}

// ReferenceEQ applies the EQ predicate on the "reference" field.
func ReferenceEQ(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldReference, v))
}

// ReferenceNEQ applies the NEQ predicate on the "reference" field.
func ReferenceNEQ(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNEQ(FieldReference, v))
}

// ReferenceIn applies the In predicate on the "reference" field.
func ReferenceIn(vs ...string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldIn(FieldReference, vs...))
}

// ReferenceNotIn applies the NotIn predicate on the "reference" field.
func ReferenceNotIn(vs ...string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNotIn(FieldReference, vs...))
}

// ReferenceGT applies the GT predicate on the "reference" field.
func ReferenceGT(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGT(FieldReference, v))
}

// ReferenceGTE applies the GTE predicate on the "reference" field.
func ReferenceGTE(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGTE(FieldReference, v))
}

// ReferenceLT applies the LT predicate on the "reference" field.
func ReferenceLT(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLT(FieldReference, v))
}

// ReferenceLTE applies the LTE predicate on the "reference" field.
func ReferenceLTE(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLTE(FieldReference, v))
}

// ReferenceContains applies the Contains predicate on the "reference" field.
func ReferenceContains(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldContains(FieldReference, v))
}

// ReferenceHasPrefix applies the HasPrefix predicate on the "reference" field.
func ReferenceHasPrefix(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldHasPrefix(FieldReference, v))
}

// ReferenceHasSuffix applies the HasSuffix predicate on the "reference" field.
func ReferenceHasSuffix(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldHasSuffix(FieldReference, v))
}

// ReferenceEqualFold applies the EqualFold predicate on the "reference" field.
func ReferenceEqualFold(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEqualFold(FieldReference, v))
}

// ReferenceContainsFold applies the ContainsFold predicate on the "reference" field.
func ReferenceContainsFold(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldContainsFold(FieldReference, v))
}

// CommitTypeEQ applies the EQ predicate on the "commit_type" field.
func CommitTypeEQ(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldCommitType, v))
}

// CommitTypeNEQ applies the NEQ predicate on the "commit_type" field.
func CommitTypeNEQ(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNEQ(FieldCommitType, v))
}

// CommitTypeIn applies the In predicate on the "commit_type" field.
func CommitTypeIn(vs ...string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldIn(FieldCommitType, vs...))
}

// CommitTypeNotIn applies the NotIn predicate on the "commit_type" field.
func CommitTypeNotIn(vs ...string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNotIn(FieldCommitType, vs...))
}

// CommitTypeGT applies the GT predicate on the "commit_type" field.
func CommitTypeGT(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGT(FieldCommitType, v))
}

// CommitTypeGTE applies the GTE predicate on the "commit_type" field.
func CommitTypeGTE(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGTE(FieldCommitType, v))
}

// CommitTypeLT applies the LT predicate on the "commit_type" field.
func CommitTypeLT(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLT(FieldCommitType, v))
}

// CommitTypeLTE applies the LTE predicate on the "commit_type" field.
func CommitTypeLTE(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLTE(FieldCommitType, v))
}

// CommitTypeContains applies the Contains predicate on the "commit_type" field.
func CommitTypeContains(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldContains(FieldCommitType, v))
}

// CommitTypeHasPrefix applies the HasPrefix predicate on the "commit_type" field.
func CommitTypeHasPrefix(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldHasPrefix(FieldCommitType, v))
}

// CommitTypeHasSuffix applies the HasSuffix predicate on the "commit_type" field.
func CommitTypeHasSuffix(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldHasSuffix(FieldCommitType, v))
}

// CommitTypeIsNil applies the IsNil predicate on the "commit_type" field.
func CommitTypeIsNil() predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldIsNull(FieldCommitType))
}

// CommitTypeNotNil applies the NotNil predicate on the "commit_type" field.
func CommitTypeNotNil() predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNotNull(FieldCommitType))
}

// CommitTypeEqualFold applies the EqualFold predicate on the "commit_type" field.
func CommitTypeEqualFold(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEqualFold(FieldCommitType, v))
}

// CommitTypeContainsFold applies the ContainsFold predicate on the "commit_type" field.
func CommitTypeContainsFold(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldContainsFold(FieldCommitType, v))
}

// CommitScopeEQ applies the EQ predicate on the "commit_scope" field.
func CommitScopeEQ(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldCommitScope, v))
}

// CommitScopeNEQ applies the NEQ predicate on the "commit_scope" field.
func CommitScopeNEQ(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNEQ(FieldCommitScope, v))
}

// CommitScopeIn applies the In predicate on the "commit_scope" field.
func CommitScopeIn(vs ...string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldIn(FieldCommitScope, vs...))
}

// CommitScopeNotIn applies the NotIn predicate on the "commit_scope" field.
func CommitScopeNotIn(vs ...string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNotIn(FieldCommitScope, vs...))
}

// CommitScopeGT applies the GT predicate on the "commit_scope" field.
func CommitScopeGT(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGT(FieldCommitScope, v))
}

// CommitScopeGTE applies the GTE predicate on the "commit_scope" field.
func CommitScopeGTE(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGTE(FieldCommitScope, v))
}

// CommitScopeLT applies the LT predicate on the "commit_scope" field.
func CommitScopeLT(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLT(FieldCommitScope, v))
}

// CommitScopeLTE applies the LTE predicate on the "commit_scope" field.
func CommitScopeLTE(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLTE(FieldCommitScope, v))
}

// CommitScopeContains applies the Contains predicate on the "commit_scope" field.
func CommitScopeContains(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldContains(FieldCommitScope, v))
}

// CommitScopeHasPrefix applies the HasPrefix predicate on the "commit_scope" field.
func CommitScopeHasPrefix(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldHasPrefix(FieldCommitScope, v))
}

// CommitScopeHasSuffix applies the HasSuffix predicate on the "commit_scope" field.
func CommitScopeHasSuffix(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldHasSuffix(FieldCommitScope, v))
}

// CommitScopeIsNil applies the IsNil predicate on the "commit_scope" field.
func CommitScopeIsNil() predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldIsNull(FieldCommitScope))
}

// CommitScopeNotNil applies the NotNil predicate on the "commit_scope" field.
func CommitScopeNotNil() predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNotNull(FieldCommitScope))
}

// CommitScopeEqualFold applies the EqualFold predicate on the "commit_scope" field.
func CommitScopeEqualFold(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEqualFold(FieldCommitScope, v))
}

// CommitScopeContainsFold applies the ContainsFold predicate on the "commit_scope" field.
func CommitScopeContainsFold(v string) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldContainsFold(FieldCommitScope, v))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLTE(FieldOccurredAt, v))
}

// OccurredAtIsNil applies the IsNil predicate on the "occurred_at" field.
func OccurredAtIsNil() predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldIsNull(FieldOccurredAt))
}

// OccurredAtNotNil applies the NotNil predicate on the "occurred_at" field.
func OccurredAtNotNil() predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNotNull(FieldOccurredAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.FieldLTE(FieldCreatedAt, v))
}

// HasRoadmapItem applies the HasEdge predicate on the "roadmap_item" edge.
func HasRoadmapItem() predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoadmapItemTable, RoadmapItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoadmapItemWith applies the HasEdge predicate on the "roadmap_item" edge with a given conditions (other predicates).
func HasRoadmapItemWith(preds ...predicate.RoadmapItem) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(func(s *sql.Selector) {
		step := newRoadmapItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeliveryEvidence) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeliveryEvidence) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeliveryEvidence) predicate.DeliveryEvidence {
	return predicate.DeliveryEvidence(sql.NotPredicates(p))
}
