// Code generated by ent, DO NOT EDIT.

package specdocument

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ProductBuildersHQ/visionstudio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContainsFold(FieldID, id))
}

// Organization applies equality check predicate on the "organization" field. It's identical to OrganizationEQ.
func Organization(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldOrganization, v))
}

// RepositoryID applies equality check predicate on the "repository_id" field. It's identical to RepositoryIDEQ.
func RepositoryID(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldRepositoryID, v))
}

// InitiativeID applies equality check predicate on the "initiative_id" field. It's identical to InitiativeIDEQ.
func InitiativeID(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldInitiativeID, v))
}

// SpecType applies equality check predicate on the "spec_type" field. It's identical to SpecTypeEQ.
func SpecType(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldSpecType, v))
}

// FilePath applies equality check predicate on the "file_path" field. It's identical to FilePathEQ.
func FilePath(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldFilePath, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldTitle, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldStatus, v))
}

// ContentHash applies equality check predicate on the "content_hash" field. It's identical to ContentHashEQ.
func ContentHash(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldContentHash, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrganizationEQ applies the EQ predicate on the "organization" field.
func OrganizationEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldOrganization, v))
}

// OrganizationNEQ applies the NEQ predicate on the "organization" field.
func OrganizationNEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNEQ(FieldOrganization, v))
}

// OrganizationIn applies the In predicate on the "organization" field.
func OrganizationIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIn(FieldOrganization, vs...))
}

// OrganizationNotIn applies the NotIn predicate on the "organization" field.
func OrganizationNotIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotIn(FieldOrganization, vs...))
}

// OrganizationGT applies the GT predicate on the "organization" field.
func OrganizationGT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGT(FieldOrganization, v))
}

// OrganizationGTE applies the GTE predicate on the "organization" field.
func OrganizationGTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGTE(FieldOrganization, v))
}

// OrganizationLT applies the LT predicate on the "organization" field.
func OrganizationLT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLT(FieldOrganization, v))
}

// OrganizationLTE applies the LTE predicate on the "organization" field.
func OrganizationLTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLTE(FieldOrganization, v))
}

// OrganizationContains applies the Contains predicate on the "organization" field.
func OrganizationContains(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContains(FieldOrganization, v))
}

// OrganizationHasPrefix applies the HasPrefix predicate on the "organization" field.
func OrganizationHasPrefix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasPrefix(FieldOrganization, v))
}

// OrganizationHasSuffix applies the HasSuffix predicate on the "organization" field.
func OrganizationHasSuffix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasSuffix(FieldOrganization, v))
}

// OrganizationIsNil applies the IsNil predicate on the "organization" field.
func OrganizationIsNil() predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIsNull(FieldOrganization))
}

// OrganizationNotNil applies the NotNil predicate on the "organization" field.
func OrganizationNotNil() predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotNull(FieldOrganization))
}

// OrganizationEqualFold applies the EqualFold predicate on the "organization" field.
func OrganizationEqualFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEqualFold(FieldOrganization, v))
}

// OrganizationContainsFold applies the ContainsFold predicate on the "organization" field.
func OrganizationContainsFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContainsFold(FieldOrganization, v))
}

// RepositoryIDEQ applies the EQ predicate on the "repository_id" field.
func RepositoryIDEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldRepositoryID, v))
}

// RepositoryIDNEQ applies the NEQ predicate on the "repository_id" field.
func RepositoryIDNEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNEQ(FieldRepositoryID, v))
}

// RepositoryIDIn applies the In predicate on the "repository_id" field.
func RepositoryIDIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIn(FieldRepositoryID, vs...))
}

// RepositoryIDNotIn applies the NotIn predicate on the "repository_id" field.
func RepositoryIDNotIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotIn(FieldRepositoryID, vs...))
}

// RepositoryIDGT applies the GT predicate on the "repository_id" field.
func RepositoryIDGT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGT(FieldRepositoryID, v))
}

// RepositoryIDGTE applies the GTE predicate on the "repository_id" field.
func RepositoryIDGTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGTE(FieldRepositoryID, v))
}

// RepositoryIDLT applies the LT predicate on the "repository_id" field.
func RepositoryIDLT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLT(FieldRepositoryID, v))
}

// RepositoryIDLTE applies the LTE predicate on the "repository_id" field.
func RepositoryIDLTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLTE(FieldRepositoryID, v))
}

// RepositoryIDContains applies the Contains predicate on the "repository_id" field.
func RepositoryIDContains(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContains(FieldRepositoryID, v))
}

// RepositoryIDHasPrefix applies the HasPrefix predicate on the "repository_id" field.
func RepositoryIDHasPrefix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasPrefix(FieldRepositoryID, v))
}

// RepositoryIDHasSuffix applies the HasSuffix predicate on the "repository_id" field.
func RepositoryIDHasSuffix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasSuffix(FieldRepositoryID, v))
}

// RepositoryIDEqualFold applies the EqualFold predicate on the "repository_id" field.
func RepositoryIDEqualFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEqualFold(FieldRepositoryID, v))
}

// RepositoryIDContainsFold applies the ContainsFold predicate on the "repository_id" field.
func RepositoryIDContainsFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContainsFold(FieldRepositoryID, v))
}

// InitiativeIDEQ applies the EQ predicate on the "initiative_id" field.
func InitiativeIDEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldInitiativeID, v))
}

// InitiativeIDNEQ applies the NEQ predicate on the "initiative_id" field.
func InitiativeIDNEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNEQ(FieldInitiativeID, v))
}

// InitiativeIDIn applies the In predicate on the "initiative_id" field.
func InitiativeIDIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIn(FieldInitiativeID, vs...))
}

// InitiativeIDNotIn applies the NotIn predicate on the "initiative_id" field.
func InitiativeIDNotIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotIn(FieldInitiativeID, vs...))
}

// InitiativeIDGT applies the GT predicate on the "initiative_id" field.
func InitiativeIDGT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGT(FieldInitiativeID, v))
}

// InitiativeIDGTE applies the GTE predicate on the "initiative_id" field.
func InitiativeIDGTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGTE(FieldInitiativeID, v))
}

// InitiativeIDLT applies the LT predicate on the "initiative_id" field.
func InitiativeIDLT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLT(FieldInitiativeID, v))
}

// InitiativeIDLTE applies the LTE predicate on the "initiative_id" field.
func InitiativeIDLTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLTE(FieldInitiativeID, v))
}

// InitiativeIDContains applies the Contains predicate on the "initiative_id" field.
func InitiativeIDContains(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContains(FieldInitiativeID, v))
}

// InitiativeIDHasPrefix applies the HasPrefix predicate on the "initiative_id" field.
func InitiativeIDHasPrefix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasPrefix(FieldInitiativeID, v))
}

// InitiativeIDHasSuffix applies the HasSuffix predicate on the "initiative_id" field.
func InitiativeIDHasSuffix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasSuffix(FieldInitiativeID, v))
}

// InitiativeIDIsNil applies the IsNil predicate on the "initiative_id" field.
func InitiativeIDIsNil() predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIsNull(FieldInitiativeID))
}

// InitiativeIDNotNil applies the NotNil predicate on the "initiative_id" field.
func InitiativeIDNotNil() predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotNull(FieldInitiativeID))
}

// InitiativeIDEqualFold applies the EqualFold predicate on the "initiative_id" field.
func InitiativeIDEqualFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEqualFold(FieldInitiativeID, v))
}

// InitiativeIDContainsFold applies the ContainsFold predicate on the "initiative_id" field.
func InitiativeIDContainsFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContainsFold(FieldInitiativeID, v))
}

// SpecTypeEQ applies the EQ predicate on the "spec_type" field.
func SpecTypeEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldSpecType, v))
}

// SpecTypeNEQ applies the NEQ predicate on the "spec_type" field.
func SpecTypeNEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNEQ(FieldSpecType, v))
}

// SpecTypeIn applies the In predicate on the "spec_type" field.
func SpecTypeIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIn(FieldSpecType, vs...))
}

// SpecTypeNotIn applies the NotIn predicate on the "spec_type" field.
func SpecTypeNotIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotIn(FieldSpecType, vs...))
}

// SpecTypeGT applies the GT predicate on the "spec_type" field.
func SpecTypeGT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGT(FieldSpecType, v))
}

// SpecTypeGTE applies the GTE predicate on the "spec_type" field.
func SpecTypeGTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGTE(FieldSpecType, v))
}

// SpecTypeLT applies the LT predicate on the "spec_type" field.
func SpecTypeLT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLT(FieldSpecType, v))
}

// SpecTypeLTE applies the LTE predicate on the "spec_type" field.
func SpecTypeLTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLTE(FieldSpecType, v))
}

// SpecTypeContains applies the Contains predicate on the "spec_type" field.
func SpecTypeContains(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContains(FieldSpecType, v))
}

// SpecTypeHasPrefix applies the HasPrefix predicate on the "spec_type" field.
func SpecTypeHasPrefix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasPrefix(FieldSpecType, v))
}

// SpecTypeHasSuffix applies the HasSuffix predicate on the "spec_type" field.
func SpecTypeHasSuffix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasSuffix(FieldSpecType, v))
}

// SpecTypeEqualFold applies the EqualFold predicate on the "spec_type" field.
func SpecTypeEqualFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEqualFold(FieldSpecType, v))
}

// SpecTypeContainsFold applies the ContainsFold predicate on the "spec_type" field.
func SpecTypeContainsFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContainsFold(FieldSpecType, v))
}

// FilePathEQ applies the EQ predicate on the "file_path" field.
func FilePathEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldFilePath, v))
}

// FilePathNEQ applies the NEQ predicate on the "file_path" field.
func FilePathNEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNEQ(FieldFilePath, v))
}

// FilePathIn applies the In predicate on the "file_path" field.
func FilePathIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIn(FieldFilePath, vs...))
}

// FilePathNotIn applies the NotIn predicate on the "file_path" field.
func FilePathNotIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotIn(FieldFilePath, vs...))
}

// FilePathGT applies the GT predicate on the "file_path" field.
func FilePathGT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGT(FieldFilePath, v))
}

// FilePathGTE applies the GTE predicate on the "file_path" field.
func FilePathGTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGTE(FieldFilePath, v))
}

// FilePathLT applies the LT predicate on the "file_path" field.
func FilePathLT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLT(FieldFilePath, v))
}

// FilePathLTE applies the LTE predicate on the "file_path" field.
func FilePathLTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLTE(FieldFilePath, v))
}

// FilePathContains applies the Contains predicate on the "file_path" field.
func FilePathContains(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContains(FieldFilePath, v))
}

// FilePathHasPrefix applies the HasPrefix predicate on the "file_path" field.
func FilePathHasPrefix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasPrefix(FieldFilePath, v))
}

// FilePathHasSuffix applies the HasSuffix predicate on the "file_path" field.
func FilePathHasSuffix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasSuffix(FieldFilePath, v))
}

// FilePathEqualFold applies the EqualFold predicate on the "file_path" field.
func FilePathEqualFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEqualFold(FieldFilePath, v))
}

// FilePathContainsFold applies the ContainsFold predicate on the "file_path" field.
func FilePathContainsFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContainsFold(FieldFilePath, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "title" field.
func TitleIsNil() predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "title" field.
func TitleNotNil() predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContainsFold(FieldTitle, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotNull(FieldStatus))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContainsFold(FieldStatus, v))
}

// ContentHashEQ applies the EQ predicate on the "content_hash" field.
func ContentHashEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldContentHash, v))
}

// ContentHashNEQ applies the NEQ predicate on the "content_hash" field.
func ContentHashNEQ(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNEQ(FieldContentHash, v))
}

// ContentHashIn applies the In predicate on the "content_hash" field.
func ContentHashIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIn(FieldContentHash, vs...))
}

// ContentHashNotIn applies the NotIn predicate on the "content_hash" field.
func ContentHashNotIn(vs ...string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotIn(FieldContentHash, vs...))
}

// ContentHashGT applies the GT predicate on the "content_hash" field.
func ContentHashGT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGT(FieldContentHash, v))
}

// ContentHashGTE applies the GTE predicate on the "content_hash" field.
func ContentHashGTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGTE(FieldContentHash, v))
}

// ContentHashLT applies the LT predicate on the "content_hash" field.
func ContentHashLT(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLT(FieldContentHash, v))
}

// ContentHashLTE applies the LTE predicate on the "content_hash" field.
func ContentHashLTE(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLTE(FieldContentHash, v))
}

// ContentHashContains applies the Contains predicate on the "content_hash" field.
func ContentHashContains(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContains(FieldContentHash, v))
}

// ContentHashHasPrefix applies the HasPrefix predicate on the "content_hash" field.
func ContentHashHasPrefix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasPrefix(FieldContentHash, v))
}

// ContentHashHasSuffix applies the HasSuffix predicate on the "content_hash" field.
func ContentHashHasSuffix(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldHasSuffix(FieldContentHash, v))
}

// ContentHashIsNil applies the IsNil predicate on the "content_hash" field.
func ContentHashIsNil() predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIsNull(FieldContentHash))
}

// ContentHashNotNil applies the NotNil predicate on the "content_hash" field.
func ContentHashNotNil() predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotNull(FieldContentHash))
}

// ContentHashEqualFold applies the EqualFold predicate on the "content_hash" field.
func ContentHashEqualFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEqualFold(FieldContentHash, v))
}

// ContentHashContainsFold applies the ContainsFold predicate on the "content_hash" field.
func ContentHashContainsFold(v string) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldContainsFold(FieldContentHash, v))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLTE(FieldSyncedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SpecDocument {
	return predicate.SpecDocument(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SpecDocument) predicate.SpecDocument {
	return predicate.SpecDocument(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SpecDocument) predicate.SpecDocument {
	return predicate.SpecDocument(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SpecDocument) predicate.SpecDocument {
	return predicate.SpecDocument(sql.NotPredicates(p))
}
