// Code generated by ent, DO NOT EDIT.

package repository

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the repository type in the database.
	Label = "repository"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "repository_id"
	// FieldOrganization holds the string denoting the organization field in the database.
	FieldOrganization = "organization"
	// FieldRepositoryName holds the string denoting the repository_name field in the database.
	FieldRepositoryName = "repository_name"
	// FieldDefaultBranch holds the string denoting the default_branch field in the database.
	FieldDefaultBranch = "default_branch"
	// FieldLocalPath holds the string denoting the local_path field in the database.
	FieldLocalPath = "local_path"
	// FieldGoModule holds the string denoting the go_module field in the database.
	FieldGoModule = "go_module"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIngestHighWater holds the string denoting the ingest_high_water field in the database.
	FieldIngestHighWater = "ingest_high_water"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldVisibility holds the string denoting the visibility field in the database.
	FieldVisibility = "visibility"
	// FieldSupersededBy holds the string denoting the superseded_by field in the database.
	FieldSupersededBy = "superseded_by"
	// EdgeRoadmapItems holds the string denoting the roadmap_items edge name in mutations.
	EdgeRoadmapItems = "roadmap_items"
	// EdgeSpecDocuments holds the string denoting the spec_documents edge name in mutations.
	EdgeSpecDocuments = "spec_documents"
	// EdgeReleases holds the string denoting the releases edge name in mutations.
	EdgeReleases = "releases"
	// EdgeOrg holds the string denoting the org edge name in mutations.
	EdgeOrg = "org"
	// RoadmapItemFieldID holds the string denoting the ID field of the RoadmapItem.
	RoadmapItemFieldID = "rmi_id"
	// SpecDocumentFieldID holds the string denoting the ID field of the SpecDocument.
	SpecDocumentFieldID = "id"
	// ReleaseFieldID holds the string denoting the ID field of the Release.
	ReleaseFieldID = "release_id"
	// OrganizationFieldID holds the string denoting the ID field of the Organization.
	OrganizationFieldID = "org_entity_id"
	// Table holds the table name of the repository in the database.
	Table = "repositories"
	// RoadmapItemsTable is the table that holds the roadmap_items relation/edge.
	RoadmapItemsTable = "roadmap_items"
	// RoadmapItemsInverseTable is the table name for the RoadmapItem entity.
	// It exists in this package in order to avoid circular dependency with the "roadmapitem" package.
	RoadmapItemsInverseTable = "roadmap_items"
	// RoadmapItemsColumn is the table column denoting the roadmap_items relation/edge.
	RoadmapItemsColumn = "repository_roadmap_items"
	// SpecDocumentsTable is the table that holds the spec_documents relation/edge.
	SpecDocumentsTable = "spec_documents"
	// SpecDocumentsInverseTable is the table name for the SpecDocument entity.
	// It exists in this package in order to avoid circular dependency with the "specdocument" package.
	SpecDocumentsInverseTable = "spec_documents"
	// SpecDocumentsColumn is the table column denoting the spec_documents relation/edge.
	SpecDocumentsColumn = "repository_id"
	// ReleasesTable is the table that holds the releases relation/edge.
	ReleasesTable = "releases"
	// ReleasesInverseTable is the table name for the Release entity.
	// It exists in this package in order to avoid circular dependency with the "release" package.
	ReleasesInverseTable = "releases"
	// ReleasesColumn is the table column denoting the releases relation/edge.
	ReleasesColumn = "repository_id"
	// OrgTable is the table that holds the org relation/edge.
	OrgTable = "repositories"
	// OrgInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrgInverseTable = "organizations"
	// OrgColumn is the table column denoting the org relation/edge.
	OrgColumn = "organization_id"
)

// Columns holds all SQL columns for repository fields.
var Columns = []string{
	FieldID,
	FieldOrganization,
	FieldRepositoryName,
	FieldDefaultBranch,
	FieldLocalPath,
	FieldGoModule,
	FieldDomain,
	FieldStatus,
	FieldIngestHighWater,
	FieldOrganizationID,
	FieldVisibility,
	FieldSupersededBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OrganizationValidator is a validator for the "organization" field. It is called by the builders before save.
	OrganizationValidator func(string) error
	// RepositoryNameValidator is a validator for the "repository_name" field. It is called by the builders before save.
	RepositoryNameValidator func(string) error
	// DefaultDefaultBranch holds the default value on creation for the "default_branch" field.
	DefaultDefaultBranch string
	// DefaultBranchValidator is a validator for the "default_branch" field. It is called by the builders before save.
	DefaultBranchValidator func(string) error
	// LocalPathValidator is a validator for the "local_path" field. It is called by the builders before save.
	LocalPathValidator func(string) error
	// GoModuleValidator is a validator for the "go_module" field. It is called by the builders before save.
	GoModuleValidator func(string) error
	// DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	DomainValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// IngestHighWaterValidator is a validator for the "ingest_high_water" field. It is called by the builders before save.
	IngestHighWaterValidator func(string) error
	// OrganizationIDValidator is a validator for the "organization_id" field. It is called by the builders before save.
	OrganizationIDValidator func(string) error
	// DefaultVisibility holds the default value on creation for the "visibility" field.
	DefaultVisibility string
	// VisibilityValidator is a validator for the "visibility" field. It is called by the builders before save.
	VisibilityValidator func(string) error
	// SupersededByValidator is a validator for the "superseded_by" field. It is called by the builders before save.
	SupersededByValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Repository queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrganization orders the results by the organization field.
func ByOrganization(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganization, opts...).ToFunc()
}

// ByRepositoryName orders the results by the repository_name field.
func ByRepositoryName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositoryName, opts...).ToFunc()
}

// ByDefaultBranch orders the results by the default_branch field.
func ByDefaultBranch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultBranch, opts...).ToFunc()
}

// ByLocalPath orders the results by the local_path field.
func ByLocalPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalPath, opts...).ToFunc()
}

// ByGoModule orders the results by the go_module field.
func ByGoModule(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoModule, opts...).ToFunc()
}

// ByDomain orders the results by the domain field.
func ByDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomain, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIngestHighWater orders the results by the ingest_high_water field.
func ByIngestHighWater(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIngestHighWater, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByVisibility orders the results by the visibility field.
func ByVisibility(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisibility, opts...).ToFunc()
}

// BySupersededBy orders the results by the superseded_by field.
func BySupersededBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupersededBy, opts...).ToFunc()
}

// ByRoadmapItemsCount orders the results by roadmap_items count.
func ByRoadmapItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRoadmapItemsStep(), opts...)
	}
}

// ByRoadmapItems orders the results by roadmap_items terms.
func ByRoadmapItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoadmapItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySpecDocumentsCount orders the results by spec_documents count.
func BySpecDocumentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSpecDocumentsStep(), opts...)
	}
}

// BySpecDocuments orders the results by spec_documents terms.
func BySpecDocuments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSpecDocumentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReleasesCount orders the results by releases count.
func ByReleasesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReleasesStep(), opts...)
	}
}

// ByReleases orders the results by releases terms.
func ByReleases(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReleasesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOrgField orders the results by org field.
func ByOrgField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrgStep(), sql.OrderByField(field, opts...))
	}
}
func newRoadmapItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoadmapItemsInverseTable, RoadmapItemFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RoadmapItemsTable, RoadmapItemsColumn),
	)
}
func newSpecDocumentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SpecDocumentsInverseTable, SpecDocumentFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SpecDocumentsTable, SpecDocumentsColumn),
	)
}
func newReleasesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReleasesInverseTable, ReleaseFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReleasesTable, ReleasesColumn),
	)
}
func newOrgStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrgInverseTable, OrganizationFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrgTable, OrgColumn),
	)
}
