// Code generated by ent, DO NOT EDIT.

package specworkflow

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the specworkflow type in the database.
	Label = "spec_workflow"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "workflow_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSpecsRequired holds the string denoting the specs_required field in the database.
	FieldSpecsRequired = "specs_required"
	// FieldSpecsOptional holds the string denoting the specs_optional field in the database.
	FieldSpecsOptional = "specs_optional"
	// FieldInitTypes holds the string denoting the init_types field in the database.
	FieldInitTypes = "init_types"
	// EdgeInitiatives holds the string denoting the initiatives edge name in mutations.
	EdgeInitiatives = "initiatives"
	// EdgeSpecDocuments holds the string denoting the spec_documents edge name in mutations.
	EdgeSpecDocuments = "spec_documents"
	// InitiativeFieldID holds the string denoting the ID field of the Initiative.
	InitiativeFieldID = "initiative_id"
	// SpecDocumentFieldID holds the string denoting the ID field of the SpecDocument.
	SpecDocumentFieldID = "id"
	// Table holds the table name of the specworkflow in the database.
	Table = "spec_workflows"
	// InitiativesTable is the table that holds the initiatives relation/edge.
	InitiativesTable = "initiatives"
	// InitiativesInverseTable is the table name for the Initiative entity.
	// It exists in this package in order to avoid circular dependency with the "initiative" package.
	InitiativesInverseTable = "initiatives"
	// InitiativesColumn is the table column denoting the initiatives relation/edge.
	InitiativesColumn = "spec_workflow_initiatives"
	// SpecDocumentsTable is the table that holds the spec_documents relation/edge.
	SpecDocumentsTable = "spec_documents"
	// SpecDocumentsInverseTable is the table name for the SpecDocument entity.
	// It exists in this package in order to avoid circular dependency with the "specdocument" package.
	SpecDocumentsInverseTable = "spec_documents"
	// SpecDocumentsColumn is the table column denoting the spec_documents relation/edge.
	SpecDocumentsColumn = "workflow_id"
)

// Columns holds all SQL columns for specworkflow fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldSpecsRequired,
	FieldSpecsOptional,
	FieldInitTypes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the SpecWorkflow queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByInitiativesCount orders the results by initiatives count.
func ByInitiativesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInitiativesStep(), opts...)
	}
}

// ByInitiatives orders the results by initiatives terms.
func ByInitiatives(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInitiativesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySpecDocumentsCount orders the results by spec_documents count.
func BySpecDocumentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSpecDocumentsStep(), opts...)
	}
}

// BySpecDocuments orders the results by spec_documents terms.
func BySpecDocuments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSpecDocumentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newInitiativesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InitiativesInverseTable, InitiativeFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InitiativesTable, InitiativesColumn),
	)
}
func newSpecDocumentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SpecDocumentsInverseTable, SpecDocumentFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SpecDocumentsTable, SpecDocumentsColumn),
	)
}
